import { TooltipData } from 'pages/stats/types'
import { TableSetting } from 'state/ui/stats/types'

import { CampaignTableColumn } from '../../types/CampaignTableColumn'
import { CampaignTableKeys } from '../../types/enums/CampaignTableKeys.enum'
import { CampaignTableValueFormat } from '../../types/enums/CampaignTableValueFormat.enum'

export const enum CampaignSettingType {
    PerformanceReportVisibleFields = 'performance_report_visible_fields',
    EmailDisclaimer = 'email_disclaimer',
    CampaignFrequency = 'campaign_frequency',
}

export const CampaignTableColumnDefaultSelect: CampaignTableKeys[] = [
    CampaignTableKeys.CampaignName,
    CampaignTableKeys.CampaignCurrentStatus,
    CampaignTableKeys.TotalRevenue,
    CampaignTableKeys.Impressions,
    CampaignTableKeys.Engagement,
    CampaignTableKeys.Conversions,
]

export const CAMPAIGN_TABLE_COLUMN_TITLES: Record<CampaignTableKeys, string> = {
    [CampaignTableKeys.CampaignName]: 'Campaign name',
    [CampaignTableKeys.CampaignCurrentStatus]: 'Status',
    [CampaignTableKeys.TotalRevenue]: 'Total revenue',
    [CampaignTableKeys.Impressions]: 'Impressions',
    [CampaignTableKeys.Engagement]: 'Engagement',
    [CampaignTableKeys.ClickThroughRate]: 'Click-through rate',
    [CampaignTableKeys.Conversions]: 'Orders',
    [CampaignTableKeys.TotalConversionRate]: 'Total conversion rate',
    [CampaignTableKeys.TicketsCreated]: 'Tickets created',
    [CampaignTableKeys.TicketsCreationRate]: 'Tickets creation rate',
    [CampaignTableKeys.TicketsConverted]: 'Tickets converted',
    [CampaignTableKeys.TicketConversionRate]: 'Tickets conversion rate',
    [CampaignTableKeys.RevenueGeneratedTickets]: 'Revenue generated by tickets',
    [CampaignTableKeys.NumberOfClicks]: 'Clicks',
    [CampaignTableKeys.ClicksRate]: 'Click rate',
    [CampaignTableKeys.ClicksConverted]: 'Clicks converted',
    [CampaignTableKeys.ClicksConversionRate]: 'Clicks conversion rate',
    [CampaignTableKeys.ClicksRevenue]: 'Revenue generated by campaign clicks',
    [CampaignTableKeys.DiscountCodeUsed]: 'Discount codes used',
    [CampaignTableKeys.RevenueGeneratedDiscountCode]:
        'Revenue generated by discount codes',
}

export const CAMPAIGN_TABLE_CELLS: CampaignTableColumn[] = [
    {
        key: CampaignTableKeys.CampaignName,
        title: CAMPAIGN_TABLE_COLUMN_TITLES[CampaignTableKeys.CampaignName],
    },
    {
        key: CampaignTableKeys.CampaignCurrentStatus,
        title: CAMPAIGN_TABLE_COLUMN_TITLES[
            CampaignTableKeys.CampaignCurrentStatus
        ],
        hint: {
            title: 'Current status of the campaign',
        },
    },
    {
        key: CampaignTableKeys.TotalRevenue,
        title: CAMPAIGN_TABLE_COLUMN_TITLES[CampaignTableKeys.TotalRevenue],
        format: CampaignTableValueFormat.Currency,
        hint: {
            title: 'Sum of revenue from all potential revenue sources for a campaign: tickets converted, products recommended bought, links visited followed by an order, discount codes applied',
        },
    },
    {
        key: CampaignTableKeys.Impressions,
        title: CAMPAIGN_TABLE_COLUMN_TITLES[CampaignTableKeys.Impressions],
        format: CampaignTableValueFormat.Number,
        hint: {
            title: 'How often the campaign was displayed',
        },
    },
    {
        key: CampaignTableKeys.Engagement,
        title: CAMPAIGN_TABLE_COLUMN_TITLES[CampaignTableKeys.Engagement],
        format: CampaignTableValueFormat.Number,
        hint: {
            title: 'How often shoppers interacted with the campaign including starting a chat conversation, clicking on a link, clicking on a product recommended, or using a discount code displayed in the campaign. Calculated here as Tickets created + Clicks + Discount codes used',
        },
    },
    {
        key: CampaignTableKeys.ClickThroughRate,
        title: CAMPAIGN_TABLE_COLUMN_TITLES[CampaignTableKeys.ClickThroughRate],
        format: CampaignTableValueFormat.Percentage,
        hint: {
            title: 'It measures the attractiveness of the campaign, calculated as engagement divided by impressions',
        },
        className: 'clickThroughRate',
    },
    {
        key: CampaignTableKeys.Conversions,
        title: CAMPAIGN_TABLE_COLUMN_TITLES[CampaignTableKeys.Conversions],
        format: CampaignTableValueFormat.Number,
        hint: {
            title: 'Numbers of orders following an engagement with the campaign',
        },
    },
    {
        key: CampaignTableKeys.TotalConversionRate,
        title: CAMPAIGN_TABLE_COLUMN_TITLES[
            CampaignTableKeys.TotalConversionRate
        ],
        format: CampaignTableValueFormat.Percentage,
        hint: {
            title: 'Calculated as orders divided by engagement',
        },
        className: 'totalConversionRate',
    },
    {
        key: CampaignTableKeys.TicketsCreated,
        title: CAMPAIGN_TABLE_COLUMN_TITLES[CampaignTableKeys.TicketsCreated],
        format: CampaignTableValueFormat.Number,
        className: 'ticketCreated',
    },
    {
        key: CampaignTableKeys.TicketsCreationRate,
        title: CAMPAIGN_TABLE_COLUMN_TITLES[
            CampaignTableKeys.TicketsCreationRate
        ],
        format: CampaignTableValueFormat.Percentage,
        hint: {
            title: 'Tickets created divided by Impressions',
        },
        className: 'ticketCreationRate',
    },
    {
        key: CampaignTableKeys.TicketsConverted,
        title: CAMPAIGN_TABLE_COLUMN_TITLES[CampaignTableKeys.TicketsConverted],
        format: CampaignTableValueFormat.Number,
        hint: {
            title: 'A ticket is converted when an order is placed by the shopper less than 5 days after the last message of the ticket',
        },
        className: 'ticketsConverted',
    },
    {
        key: CampaignTableKeys.TicketConversionRate,
        title: CAMPAIGN_TABLE_COLUMN_TITLES[
            CampaignTableKeys.TicketConversionRate
        ],
        format: CampaignTableValueFormat.Percentage,
        className: 'ticketConversionRate',
    },
    {
        key: CampaignTableKeys.RevenueGeneratedTickets,
        title: CAMPAIGN_TABLE_COLUMN_TITLES[
            CampaignTableKeys.RevenueGeneratedTickets
        ],
        format: CampaignTableValueFormat.Currency,
        className: 'revenueGeneratedTickets',
    },
    {
        key: CampaignTableKeys.NumberOfClicks,
        title: CAMPAIGN_TABLE_COLUMN_TITLES[CampaignTableKeys.NumberOfClicks],
        format: CampaignTableValueFormat.Number,
        hint: {
            title: 'Clicks on any content of the campaign (links or product cards)',
        },
        className: 'numberOfClicks',
    },
    {
        key: CampaignTableKeys.ClicksRate,
        title: CAMPAIGN_TABLE_COLUMN_TITLES[CampaignTableKeys.ClicksRate],
        format: CampaignTableValueFormat.Percentage,
        hint: {
            title: 'Campaign clicks divide by impressions',
        },
    },
    {
        key: CampaignTableKeys.ClicksConverted,
        title: CAMPAIGN_TABLE_COLUMN_TITLES[CampaignTableKeys.ClicksConverted],
        format: CampaignTableValueFormat.Number,
        hint: {
            title: 'A click is considered converted when an order is placed by the shopper during the session',
        },
        className: 'clicksConverted',
    },
    {
        key: CampaignTableKeys.ClicksConversionRate,
        title: CAMPAIGN_TABLE_COLUMN_TITLES[
            CampaignTableKeys.ClicksConversionRate
        ],
        format: CampaignTableValueFormat.Percentage,
        className: 'clicksConversionRate',
    },
    {
        key: CampaignTableKeys.ClicksRevenue,
        title: CAMPAIGN_TABLE_COLUMN_TITLES[CampaignTableKeys.ClicksRevenue],
        format: CampaignTableValueFormat.Currency,
        className: 'revenueGeneratedCampaignClicks',
    },
    {
        key: CampaignTableKeys.DiscountCodeUsed,
        title: CAMPAIGN_TABLE_COLUMN_TITLES[CampaignTableKeys.DiscountCodeUsed],
        format: CampaignTableValueFormat.Number,
        hint: {
            title: 'If a discount code is displayed in the campaign message, the number of times the discount code was applied to an order placed during the selected period',
        },
        className: 'discountCodeUsed',
    },
    {
        key: CampaignTableKeys.RevenueGeneratedDiscountCode,
        title: CAMPAIGN_TABLE_COLUMN_TITLES[
            CampaignTableKeys.RevenueGeneratedDiscountCode
        ],
        format: CampaignTableValueFormat.Currency,
        hint: {
            title: 'Sum of the order amount for all orders using the discount code displayed',
        },
        className: 'revenueDiscountCode',
    },
]

export const CampaignTableColumnOrder: CampaignTableKeys[] =
    CAMPAIGN_TABLE_CELLS.map((column) => column.key)

export const campaignPerformanceMetrics = CampaignTableColumnOrder.map(
    (column) => ({
        id: column,
        visibility: CampaignTableColumnDefaultSelect.includes(column),
    }),
)

export const CampaignPerformanceTableViews: TableSetting<CampaignTableKeys> = {
    active_view: 'Campaign Performance Table',
    views: [],
}

export const CampaignPerformanceTableDefaultConfigurationViews = {
    type: CampaignSettingType.PerformanceReportVisibleFields,
    metrics: campaignPerformanceMetrics,
}

// Convert CAMPAIGN_TABLE_CELLS into EditColumn required format and type
export const CampaignPerformanceTooltipConfig = CAMPAIGN_TABLE_CELLS.reduce(
    (obj, item) => Object.assign(obj, { [item.key]: item }),
    {} as Record<CampaignTableKeys, { hint: TooltipData | null }>,
)

export const CampaignPerformanceConfig = CAMPAIGN_TABLE_CELLS.reduce(
    (obj, item) => Object.assign(obj, { [item.key]: item }),
    {} as Record<CampaignTableKeys, CampaignTableColumn>,
)
