name: Install dependencies
description: Installs dependencies

inputs:
  npm-token:
    description: Read token for packages
    required: true
  node-version:
    description: Version Spec of the version to use
    required: true

runs:
  using: composite
  steps:
    - name: Set cache key as environment variable
      shell: bash
      run: echo "CACHE_KEY=pnpm-store-${{ runner.os }}-${{ hashFiles('pnpm-lock.yaml') }}" >> $GITHUB_ENV

    - name: Setup workspace
      uses: ./.github/actions/setup-workspace
      with:
        node-version: ${{ inputs.node-version }}
        cache-key: pnpm-store-${{ runner.os }}-${{ hashFiles('pnpm-lock.yaml') }}
        npm-token: ${{ inputs.npm-token }}
