export const FETCH_CURRENT_USAGE_ERROR = 'FETCH_CURRENT_USAGE_ERROR'
export const FETCH_CURRENT_USAGE_SUCCESS = 'FETCH_CURRENT_USAGE_SUCCESS'

export const FETCH_INVOICES_ERROR = 'FETCH_INVOICES_ERROR'
export const FETCH_INVOICES_SUCCESS = 'FETCH_INVOICES_SUCCESS'

export const FETCH_CREDIT_CARD_ERROR = 'FETCH_CREDIT_CARD_ERROR'
export const FETCH_CREDIT_CARD_SUCCESS = 'FETCH_CREDIT_CARD_SUCCESS'

export const UPDATE_CREDIT_CARD_ERROR = 'UPDATE_CREDIT_CARD_ERROR'
export const UPDATE_CREDIT_CARD_SUCCESS = 'UPDATE_CREDIT_CARD_SUCCESS'

export const FETCH_PAYMENT_METHOD_ERROR = 'FETCH_PAYMENT_METHOD_ERROR'
export const FETCH_PAYMENT_METHOD_SUCCESS = 'FETCH_PAYMENT_METHOD_SUCCESS'

export const UPDATE_SUBSCRIPTION_ERROR = 'UPDATE_SUBSCRIPTION_ERROR'
export const UPDATE_SUBSCRIPTION_SUCCESS = 'UPDATE_SUBSCRIPTION_SUCCESS'

