export const FETCH_CURRENT_USAGE_START = 'FETCH_CURRENT_USAGE_START'
export const FETCH_CURRENT_USAGE_ERROR = 'FETCH_CURRENT_USAGE_ERROR'
export const FETCH_CURRENT_USAGE_SUCCESS = 'FETCH_CURRENT_USAGE_SUCCESS'

export const FETCH_INVOICES_START = 'FETCH_INVOICES_START'
export const FETCH_INVOICES_ERROR = 'FETCH_INVOICES_ERROR'
export const FETCH_INVOICES_SUCCESS = 'FETCH_INVOICES_SUCCESS'

export const FETCH_CREDIT_CARD_START = 'FETCH_CREDIT_CARD_START'
export const FETCH_CREDIT_CARD_ERROR = 'FETCH_CREDIT_CARD_ERROR'
export const FETCH_CREDIT_CARD_SUCCESS = 'FETCH_CREDIT_CARD_SUCCESS'

export const UPDATE_CREDIT_CARD_START = 'UPDATE_CREDIT_CARD_START'
export const UPDATE_CREDIT_CARD_ERROR = 'UPDATE_CREDIT_CARD_ERROR'
export const UPDATE_CREDIT_CARD_SUCCESS = 'UPDATE_CREDIT_CARD_SUCCESS'

// redux form
export const UPDATE_CREDIT_CARD_FORM = 'UPDATE_CREDIT_CARD_FORM'
