export const OPTIMISTIC_USER_SETTINGS_SET =
    'TICKET_NAVBAR/OPTIMISTIC_USER_SETTINGS_SET'

export const OPTIMISTIC_USER_SETTINGS_RESET =
    'TICKET_NAVBAR/OPTIMISTIC_USER_SETTINGS_RESET'

export const OPTIMISTIC_ACCOUNT_SETTINGS_SET =
    'TICKET_NAVBAR/OPTIMISTIC_ACCOUNT_SETTINGS_SET'

export const OPTIMISTIC_ACCOUNT_SETTINGS_RESET =
    'TICKET_NAVBAR/OPTIMISTIC_ACCOUNT_SETTINGS_RESET'
