import { OrderDirection } from 'models/api/types'
import {
    View,
    ViewCategory,
    ViewField,
    ViewType,
    ViewVisibility,
} from 'models/view/types'

export const newViews: View[] = [
    {
        category: ViewCategory.System,
        created_datetime: '2021-05-14T12:27:39.692574+00:00',
        deactivated_datetime: null,
        decoration: null,
        fields: [],
        filters: 'isNotEmpty(ticket.snooze_datetime)',
        filters_ast: {},
        id: 4000,
        name: 'Snoozed',
        order_by: ViewField.LastMessage,
        order_dir: OrderDirection.Desc,
        search: null,
        section_id: null,
        slug: 'snoozed',
        type: ViewType.TicketList,
        uri: '/api/views/4000/',
        visibility: ViewVisibility.Public,
        with_highlights: false,
    },
    {
        category: ViewCategory.System,
        created_datetime: '2023-07-31T15:30:10.210164+00:00',
        deactivated_datetime: null,
        decoration: null,
        fields: [],
        filters: 'isNotEmpty(ticket.trashed_datetime)',
        filters_ast: {},
        id: 8000,
        name: 'Trash',
        order_by: ViewField.Updated,
        order_dir: OrderDirection.Desc,
        search: null,
        section_id: null,
        slug: 'trash',
        type: ViewType.TicketList,
        uri: '/api/views/8000/',
        visibility: ViewVisibility.Public,
        with_highlights: false,
    },
    {
        category: ViewCategory.System,
        created_datetime: '2023-01-19T08:33:36.597140+00:00',
        deactivated_datetime: null,
        decoration: null,
        fields: [],
        filters: "eq(ticket.assignee_user.id, '{{current_user.id}}')",
        filters_ast: {},
        id: 3000,
        name: 'Inbox',
        order_by: ViewField.LastMessage,
        order_dir: OrderDirection.Desc,
        search: null,
        section_id: null,
        slug: 'inbox',
        uri: '/api/views/3000/',
        type: ViewType.TicketList,
        visibility: ViewVisibility.Public,
        with_highlights: false,
    },
    {
        category: ViewCategory.System,
        created_datetime: '2019-09-20T14:51:40.332147+00:00',
        deactivated_datetime: null,
        decoration: null,
        fields: [],
        filters: 'eq(ticket.spam, true)',
        filters_ast: {},
        id: 7000,
        name: 'Spam',
        order_by: ViewField.Updated,
        order_dir: OrderDirection.Desc,
        search: null,
        section_id: null,
        slug: 'spam',
        type: ViewType.TicketList,
        uri: '/api/views/7000/',
        visibility: ViewVisibility.Public,
        with_highlights: false,
    },
]
