export const FETCH_TEAMS_SUCCESS = 'FETCH_TEAMS_SUCCESS'

export const CREATE_TEAM_SUCCESS = 'CREATE_TEAM_SUCCESS'
export const DELETE_TEAM_SUCCESS = 'DELETE_TEAM_SUCCESS'
export const FETCH_TEAM_SUCCESS = 'FETCH_TEAM_SUCCESS'
export const UPDATE_TEAM_SUCCESS = 'UPDATE_TEAM_SUCCESS'

export const FETCH_TEAM_MEMBERS_SUCCESS = 'FETCH_TEAM_MEMBERS_SUCCESS'
