export const CREATE_TEAM_SUCCESS = 'CREATE_TEAM_SUCCESS'
export const CREATE_TEAM_ERROR = 'CREATE_TEAM_ERROR'

export const UPDATE_TEAM_SUCCESS = 'UPDATE_TEAM_SUCCESS'
export const UPDATE_TEAM_ERROR = 'UPDATE_TEAM_ERROR'

export const DELETE_TEAM_SUCCESS = 'DELETE_TEAM_SUCCESS'
export const DELETE_TEAM_ERROR = 'DELETE_TEAM_ERROR'

export const FETCH_TEAM_SUCCESS = 'FETCH_TEAM_SUCCESS'
export const FETCH_TEAM_ERROR = 'FETCH_TEAM_ERROR'

export const FETCH_TEAMS_PAGINATION_ERROR = 'FETCH_TEAMS_PAGINATION_ERROR'
export const FETCH_TEAM_MEMBERS_PAGINATION_ERROR =
    'FETCH_TEAM_MEMBERS_PAGINATION_ERROR'

export const ADD_TEAM_MEMBER_ERROR = 'ADD_TEAM_MEMBER_ERROR'
export const DELETE_TEAM_MEMBER_ERROR = 'DELETE_TEAM_MEMBER_ERROR'
export const DELETE_TEAM_MEMBER_LIST_ERROR = 'DELETE_TEAM_MEMBER_LIST_ERROR'
