export { ViewCountBadge } from './components/ViewCountBadge'
export { useViews } from './hooks/useViews'
export { useViewCount, setViewsCount } from './hooks/useViewsCount'
export { useSystemViews } from './hooks/useSystemViews'
export type { SystemView } from './hooks/useSystemViews'
