export const SHOPPING_ASSISTANT_TRIAL_DURATION_DAYS = 14
export const SHOPPING_ASSISTANT_TRIAL_GMV_INFLUENCED_THRESHOLD = 0.005
export const AI_AGENT_TRIAL_DURATION_DAYS = 14
export const AI_AGENT_TRIAL_AUTOMATION_RATE_THRESHOLD = 0.005
