import {CampaignTableKeys} from '../../types/enums/CampaignTableKeys.enum'
import {CampaignTableColumn} from '../../types/CampaignTableColumn'
import {CampaignTableValueFormat} from '../../types/enums/CampaignTableValueFormat.enum'

export const CAMPAIGN_TABLE_CELLS: CampaignTableColumn[] = [
    {
        key: CampaignTableKeys.CampaignName,
        title: 'Campaign name',
    },
    {
        key: CampaignTableKeys.TotalRevenue,
        title: 'Total revenue',
        format: CampaignTableValueFormat.Currency,
        tooltip:
            'Sum of revenue from all potential revenue sources for a campaign: tickets converted, products recommended bought, links visited followed by an order, discount codes applied',
    },
    {
        key: CampaignTableKeys.Traffic,
        title: 'Traffic',
        format: CampaignTableValueFormat.Number,
        tooltip:
            'How often the chat was displayed during the time the campaign was live on your shop',
    },
    {
        key: CampaignTableKeys.Impressions,
        title: 'Impressions',
        format: CampaignTableValueFormat.Number,
        tooltip: 'How often the campaign was displayed',
    },
    {
        key: CampaignTableKeys.Engagement,
        title: 'Engagement',
        format: CampaignTableValueFormat.Number,
        tooltip:
            'How often shoppers interacted with the campaign including starting a chat conversation, clicking on a link, clicking on a product recommended, or using a discount code displayed in the campaign. Calculated here as Tickets created + Clicks + Discount codes used',
    },
    {
        key: CampaignTableKeys.ClickThroughRate,
        title: 'Click-through rate',
        format: CampaignTableValueFormat.Percentage,
        tooltip:
            'It measures the attractiveness of the campaign, calculated as engagement divided by impressions',
        className: 'clickThroughRate',
    },
    {
        key: CampaignTableKeys.Conversions,
        title: 'Orders',
        format: CampaignTableValueFormat.Number,
        tooltip: 'Numbers of orders following an engagement with the campaign',
    },
    {
        key: CampaignTableKeys.TotalConversionRate,
        title: 'Total conversion rate',
        format: CampaignTableValueFormat.Percentage,
        tooltip: 'Calculated as orders divided by engagement',
        className: 'totalConversionRate',
    },
    {
        key: CampaignTableKeys.TicketsCreated,
        title: 'Tickets created',
        format: CampaignTableValueFormat.Number,
        className: 'ticketCreated',
    },
    {
        key: CampaignTableKeys.TicketsCreationRate,
        title: 'Tickets creation rate',
        format: CampaignTableValueFormat.Percentage,
        tooltip: 'Tickets created divided by Impressions',
        className: 'ticketCreationRate',
    },
    {
        key: CampaignTableKeys.TicketsConverted,
        title: 'Tickets converted',
        format: CampaignTableValueFormat.Number,
        tooltip:
            'A ticket is converted when an order is placed by the shopper less than 5 days after the last message of the ticket',
        className: 'ticketsConverted',
    },
    {
        key: CampaignTableKeys.TicketConversionRate,
        title: 'Tickets conversion rate',
        format: CampaignTableValueFormat.Percentage,
        className: 'ticketConversionRate',
    },
    {
        key: CampaignTableKeys.RevenueGeneratedTickets,
        title: 'Revenue generated by tickets',
        format: CampaignTableValueFormat.Currency,
        className: 'revenueGeneratedTickets',
    },
    {
        key: CampaignTableKeys.NumberOfClicks,
        title: 'Clicks',
        format: CampaignTableValueFormat.Number,
        tooltip:
            'Clicks on any content of the campaign (links or product cards)',
        className: 'numberOfClicks',
    },
    {
        key: CampaignTableKeys.ClicksRate,
        title: 'Click rate',
        format: CampaignTableValueFormat.Percentage,
        tooltip: 'Campaign clicks divide by impressions',
    },
    {
        key: CampaignTableKeys.ClicksConverted,
        title: 'Clicks converted',
        format: CampaignTableValueFormat.Number,
        tooltip:
            'A click is considered converted when an order is placed by the shopper during the session',
        className: 'clicksConverted',
    },
    {
        key: CampaignTableKeys.ClicksConversionRate,
        title: 'Clicks conversion rate',
        format: CampaignTableValueFormat.Percentage,
        className: 'clicksConversionRate',
    },
    {
        key: CampaignTableKeys.ClicksRevenue,
        title: 'Revenue generated by campaign clicks',
        format: CampaignTableValueFormat.Currency,
        className: 'revenueGeneratedCampaignClicks',
    },
    {
        key: CampaignTableKeys.DiscountCodeUsed,
        title: 'Discount codes used',
        format: CampaignTableValueFormat.Number,
        tooltip:
            'If a discount code is displayed in the campaign message, the number of times the discount code was applied to an order placed during the selected period',
        className: 'discountCodeUsed',
    },
    {
        key: CampaignTableKeys.RevenueGeneratedDiscountCode,
        title: 'Revenue generated by discount codes',
        format: CampaignTableValueFormat.Currency,
        tooltip:
            'Sum of the order amount for all orders using the discount code displayed',
        className: 'revenueDiscountCode',
    },
]
