import {CampaignTableKeys} from '../../types/enums/CampaignTableKeys.enum'
import {CampaignTableColumn} from '../../types/CampaignTableColumn'
import {CampaignTableValueFormat} from '../../types/enums/CampaignTableValueFormat.enum'

export const CAMPAIGN_TABLE_CELLS: CampaignTableColumn[] = [
    {
        key: CampaignTableKeys.CampaignName,
        title: 'Campaign name',
    },
    {
        key: CampaignTableKeys.TotalRevenue,
        title: 'Total revenue',
        format: CampaignTableValueFormat.Currency,
        tooltip:
            'Sum of revenue from all potential revenue sources for a campaign: tickets converted, products recommended bought, links visited followed by an order, discount code applied',
    },
    {
        key: CampaignTableKeys.RevenueUplift,
        title: 'GMV uplift %',
        format: CampaignTableValueFormat.Percentage,
        tooltip:
            'Evolution rate of your total store revenue thanks to this campaign, calculated as: (Total revenue)/(Total store revenue - Total revenue)',
    },
    {
        key: CampaignTableKeys.Traffic,
        title: 'Traffic',
        format: CampaignTableValueFormat.Number,
        tooltip:
            'How often the chat was displayed during the time the campaign was live on your shop',
    },
    {
        key: CampaignTableKeys.Impressions,
        title: 'Impressions',
        format: CampaignTableValueFormat.Number,
        tooltip: 'How often the campaign was displayed',
    },
    {
        key: CampaignTableKeys.UniqueImpressions,
        title: 'Unique impressions',
        format: CampaignTableValueFormat.Number,
        tooltip:
            'How often the campaign was displayed by unique visitors (if the same campaign is shown twice during a shopper’s visit, it will count as only one impression)',
        className: 'uniqueImpressions',
    },
    {
        key: CampaignTableKeys.Engagement,
        title: 'Engagement',
        format: CampaignTableValueFormat.Number,
        tooltip:
            'How often shoppers interacted with the selected campaigns. Campaign interactions include: (1) tickets created after a campaign, (2) clicks on a link displayed in a campaign, (3) clicks on product recommendations displayed in a campaign (clicks on the product link or direct add to cart), (4) discount code displayed in a campaign applied to an order',
    },
    {
        key: CampaignTableKeys.ClickThroughRate,
        title: 'Click-through rate',
        format: CampaignTableValueFormat.Percentage,
        tooltip:
            'It measures the attractiveness of the campaign, calculated as engagement divided by impressions',
        className: 'clickThroughRate',
    },
    {
        key: CampaignTableKeys.Conversions,
        title: 'Orders',
        format: CampaignTableValueFormat.Number,
        tooltip: 'Numbers of orders following an engagement with the campaign',
    },
    {
        key: CampaignTableKeys.TotalConversionRate,
        title: 'Total Conversion rate',
        format: CampaignTableValueFormat.Percentage,
        tooltip: 'Orders divided by Engagement',
        className: 'totalConversionRate',
    },
    {
        key: CampaignTableKeys.TicketsCreated,
        title: 'Ticket created',
        format: CampaignTableValueFormat.Number,
        className: 'ticketCreated',
    },
    {
        key: CampaignTableKeys.TicketsCreationRate,
        title: 'Ticket creation rate',
        format: CampaignTableValueFormat.Percentage,
        tooltip: 'Tickets created divided by Impressions',
        className: 'ticketCreationRate',
    },
    {
        key: CampaignTableKeys.TicketsConverted,
        title: 'Tickets converted',
        format: CampaignTableValueFormat.Number,
        tooltip:
            'A ticket is converted when an order is placed by the shopper less than 5 days after the last message of the ticket',
        className: 'ticketsConverted',
    },
    {
        key: CampaignTableKeys.TicketConversionRate,
        title: 'Ticket conversion rate',
        format: CampaignTableValueFormat.Percentage,
        className: 'ticketConversionRate',
    },
    {
        key: CampaignTableKeys.RevenueGeneratedTickets,
        title: 'Revenue generated by tickets',
        format: CampaignTableValueFormat.Currency,
        className: 'revenueGeneratedTickets',
    },
    {
        key: CampaignTableKeys.NumberOfClicks,
        title: 'Number of clicks',
        format: CampaignTableValueFormat.Number,
        tooltip:
            'Clicks on any content of the campaign (links or product cards)',
        className: 'numberOfClicks',
    },
    {
        key: CampaignTableKeys.ClicksRate,
        title: 'Clicks rate',
        format: CampaignTableValueFormat.Percentage,
        tooltip: 'Campaign clicks divided by Impressions',
    },
    {
        key: CampaignTableKeys.ClicksConverted,
        title: 'Clicks converted',
        format: CampaignTableValueFormat.Number,
        tooltip:
            'A click is considered converted when an order is placed by the shopper during the session',
        className: 'clicksConverted',
    },
    {
        key: CampaignTableKeys.ClicksConversionRate,
        title: 'Clicks conversion rate',
        format: CampaignTableValueFormat.Percentage,
        className: 'clicksConversionRate',
    },
    {
        key: CampaignTableKeys.ClicksRevenue,
        title: 'Revenue generated by campaign clicks',
        format: CampaignTableValueFormat.Currency,
        className: 'revenueGeneratedCampaignClicks',
    },
    {
        key: CampaignTableKeys.DiscountCodeUsed,
        title: 'Discount Code Used',
        format: CampaignTableValueFormat.Number,
        tooltip:
            'If a discount code is displayed in the campaign message, the number of times the discount code was applied to an order placed during the selected period',
        className: 'discountCodeUsed',
    },
    {
        key: CampaignTableKeys.RevenueGeneratedDiscountCode,
        title: 'Revenue generated by discount code',
        format: CampaignTableValueFormat.Currency,
        tooltip:
            'Sum of the order amount for all orders using the discount code displayed',
        className: 'revenueDiscountCode',
    },
]
