import {CampaignTableKeys} from '../../types/enums/CampaignTableKeys.enum'
import {CampaignTableColumn} from '../../types/CampaignTableColumn'
import {CampaignTableValueFormat} from '../../types/enums/CampaignTableValueFormat.enum'

export const CAMPAIGN_TABLE_CELLS: CampaignTableColumn[] = [
    {
        key: CampaignTableKeys.CampaignName,
        title: 'Campaign name',
    },
    {
        key: CampaignTableKeys.Traffic,
        title: 'Traffic',
        tooltip:
            'How often the chat was displayed during the time the campaign was live on your shop',
    },
    {
        key: CampaignTableKeys.Impressions,
        title: 'Impressions',
        tooltip: 'How often the campaign was displayed',
    },
    {
        key: CampaignTableKeys.UniqueImpressions,
        title: 'Unique impressions',
        tooltip:
            'How often the campaign was displayed by unique visitors (if the same campaign is shown twice during a shopper’s visit, it will count as only one impression)',
        className: 'uniqueImpressions',
    },
    {
        key: CampaignTableKeys.NumberOfClicks,
        title: 'Number of clicks',
        tooltip:
            'Clicks on any content of the campaign (links or product cards)',
        className: 'numberOfClicks',
    },
    {
        key: CampaignTableKeys.ClickThroughRate,
        title: 'Click-through rate',
        format: CampaignTableValueFormat.Percentage,
        tooltip:
            'It measures the attractiveness of the campaign, calculated as engagement divided by impressions',
        className: 'clickThroughRate',
    },
    {
        key: CampaignTableKeys.TicketCreated,
        title: 'Ticket created',
        className: 'ticketCreated',
    },
    {
        key: CampaignTableKeys.TicketCreationRate,
        title: 'Ticket creation rate',
        format: CampaignTableValueFormat.Percentage,
        tooltip: 'Tickets created divided by Impressions',
        className: 'ticketCreationRate',
    },
    {
        key: CampaignTableKeys.TicketsConverted,
        title: 'Tickets converted',
        tooltip:
            'A ticket is converted when an order is placed by the shopper less than 5 days after the last message of the ticket',
        className: 'ticketsConverted',
    },
    {
        key: CampaignTableKeys.TicketConversionRate,
        title: 'Ticket conversion rate',
        format: CampaignTableValueFormat.Percentage,
        className: 'ticketConversionRate',
    },
    {
        key: CampaignTableKeys.Conversions,
        title: 'Conversions',
    },
    {
        key: CampaignTableKeys.ConversionRate,
        title: 'Conversion rate',
        format: CampaignTableValueFormat.Percentage,
        tooltip: 'Orders divided by Engagement',
    },
    {
        key: CampaignTableKeys.RevenueGeneratedTickets,
        title: 'Revenue generated by tickets',
        format: CampaignTableValueFormat.Currency,
        className: 'revenueGeneratedTickets',
    },
    {
        key: CampaignTableKeys.RevenueGeneratedCampaignClicks,
        title: 'Revenue generated by campaign clicks',
        format: CampaignTableValueFormat.Currency,
        className: 'revenueGeneratedCampaignClicks',
    },
    {
        key: CampaignTableKeys.TotalRevenue,
        title: 'Total revenue',
        format: CampaignTableValueFormat.Currency,
        tooltip:
            'Sum of revenue from all potential revenue sources for a campaign: tickets converted, products recommended bought, links visited followed by an order, discount code applied',
    },
    {
        key: CampaignTableKeys.GmvUplift,
        title: 'GMV uplift %',
        format: CampaignTableValueFormat.Percentage,
        tooltip:
            'Evolution rate of your total store revenue thanks to this campaign, calculated as: (Total revenue)/(Total store revenue - Total revenue)',
    },
    {
        key: CampaignTableKeys.DiscountCodeUsed,
        title: 'Discount Code Used',
        tooltip:
            'If a discount code is displayed in the campaign message, the number of times the discount code was applied to an order placed during the selected period',
        className: 'discountCodeUsed',
    },
    {
        key: CampaignTableKeys.RevenueGeneratedDiscountCode,
        title: 'Revenue generated by discount code',
        format: CampaignTableValueFormat.Currency,
        tooltip:
            'Sum of the order amount for all orders using the discount code displayed',
        className: 'revenueDiscountCode',
    },
]
