export const FETCH_SELF_SERVICE_CONFIGURATIONS_START =
    'FETCH_SELF_SERVICE_CONFIGURATIONS_START'
export const FETCH_SELF_SERVICE_CONFIGURATIONS_SUCCESS =
    'FETCH_SELF_SERVICE_CONFIGURATIONS_SUCCESS'
export const FETCH_SELF_SERVICE_CONFIGURATIONS_ERROR =
    'FETCH_SELF_SERVICE_CONFIGURATIONS_ERROR'
export const UPDATE_SELF_SERVICE_CONFIGURATION_START =
    'UPDATE_SELF_SERVICE_CONFIGURATION_START'
export const UPDATE_SELF_SERVICE_CONFIGURATION_SUCCESS =
    'UPDATE_SELF_SERVICE_CONFIGURATION_SUCCESS'
export const UPDATE_SELF_SERVICE_CONFIGURATION_ERROR =
    'UPDATE_SELF_SERVICE_CONFIGURATION_ERROR'
