import type { Field } from '../../MetafieldsTable/types'

export const mockImportableFields: Field[] = [
    {
        id: '_1',
        key: 'new_delivery_type',
        name: 'New Delivery type',
        type: 'single_line_text_field',
        category: 'Order',
        isVisible: false,
    },
    {
        id: '_2',
        key: 'new_integer_field',
        name: 'New Integer field',
        type: 'single_line_text_field',
        category: 'Customer',
        isVisible: false,
    },
    {
        id: '_3',
        key: 'new_order_package_size',
        name: 'New Order package size',
        type: 'volume',
        category: 'DraftOrder',
        isVisible: false,
    },
    {
        id: '_4',
        key: 'new_order_package_size_2',
        name: 'New Order package size 2',
        type: 'volume',
        category: 'DraftOrder',
        isVisible: false,
    },
    {
        id: '_5',
        key: 'new_order_package_size_3',
        name: 'New Order package size 3',
        type: 'page_reference',
        category: 'DraftOrder',
        isVisible: false,
    },
    {
        id: '_6',
        key: 'draft_order_weight',
        name: 'Draft Order Weight',
        type: 'number_decimal',
        category: 'DraftOrder',
        isVisible: false,
    },
    {
        id: '_7',
        key: 'draft_order_shipping_method',
        name: 'Draft Order Shipping Method',
        type: 'single_line_text_field',
        category: 'DraftOrder',
        isVisible: false,
    },
    {
        id: '_8',
        key: 'draft_order_estimated_delivery',
        name: 'Draft Order Estimated Delivery',
        type: 'date',
        category: 'DraftOrder',
        isVisible: false,
    },
    {
        id: '_9',
        key: 'draft_order_gift_wrap',
        name: 'Draft Order Gift Wrap',
        type: 'boolean',
        category: 'DraftOrder',
        isVisible: false,
    },
    {
        id: '_10',
        key: 'draft_order_special_instructions',
        name: 'Draft Order Special Instructions',
        type: 'multi_line_text_field',
        category: 'DraftOrder',
        isVisible: false,
    },
    {
        id: '_11',
        key: 'draft_order_coupon_code',
        name: 'Draft Order Coupon Code',
        type: 'single_line_text_field',
        category: 'DraftOrder',
        isVisible: false,
    },
    {
        id: '_12',
        key: 'draft_order_tax_amount',
        name: 'Draft Order Tax Amount',
        type: 'number_decimal',
        category: 'DraftOrder',
        isVisible: false,
    },
    {
        id: '_13',
        key: 'draft_order_item_count',
        name: 'Draft Order Item Count',
        type: 'number_integer',
        category: 'DraftOrder',
        isVisible: false,
    },
    {
        id: '_14',
        key: 'draft_order_packaging_type',
        name: 'Draft Order Packaging Type',
        type: 'single_line_text_field',
        category: 'DraftOrder',
        isVisible: false,
    },
    {
        id: '_15',
        key: 'draft_order_delivery_window',
        name: 'Draft Order Delivery Window',
        type: 'single_line_text_field',
        category: 'DraftOrder',
        isVisible: false,
    },
]
