import type { Field } from '../../MetafieldsTable/types'

export const mockImportableFields: Field[] = [
    {
        id: '_1',
        name: 'New Delivery type',
        type: 'single_line_text',
        category: 'order',
        isVisible: false,
    },
    {
        id: '_2',
        name: 'New Integer field',
        type: 'single_line_text',
        category: 'customer',
        isVisible: false,
    },
    {
        id: '_3',
        name: 'New Order package size',
        type: 'volume',
        category: 'draft_order',
        isVisible: false,
    },
    {
        id: '_4',
        name: 'New Order package size 2',
        type: 'volume',
        category: 'draft_order',
        isVisible: false,
    },
    {
        id: '_5',
        name: 'New Order package size 3',
        type: 'page',
        category: 'draft_order',
        isVisible: false,
    },
    {
        id: '_6',
        name: 'Draft Order Weight',
        type: 'decimal',
        category: 'draft_order',
        isVisible: false,
    },
    {
        id: '_7',
        name: 'Draft Order Shipping Method',
        type: 'single_line_text',
        category: 'draft_order',
        isVisible: false,
    },
    {
        id: '_8',
        name: 'Draft Order Estimated Delivery',
        type: 'date',
        category: 'draft_order',
        isVisible: false,
    },
    {
        id: '_9',
        name: 'Draft Order Gift Wrap',
        type: 'boolean',
        category: 'draft_order',
        isVisible: false,
    },
    {
        id: '_10',
        name: 'Draft Order Special Instructions',
        type: 'multi_line_text',
        category: 'draft_order',
        isVisible: false,
    },
    {
        id: '_11',
        name: 'Draft Order Coupon Code',
        type: 'single_line_text',
        category: 'draft_order',
        isVisible: false,
    },
    {
        id: '_12',
        name: 'Draft Order Tax Amount',
        type: 'decimal',
        category: 'draft_order',
        isVisible: false,
    },
    {
        id: '_13',
        name: 'Draft Order Item Count',
        type: 'integer',
        category: 'draft_order',
        isVisible: false,
    },
    {
        id: '_14',
        name: 'Draft Order Packaging Type',
        type: 'single_line_text',
        category: 'draft_order',
        isVisible: false,
    },
    {
        id: '_15',
        name: 'Draft Order Delivery Window',
        type: 'single_line_text',
        category: 'draft_order',
        isVisible: false,
    },
]
