name: Setup Node.js
description: Sets up Node.js environment with Yarn

inputs:
  node-version:
    description: Version Spec of the version to use
    required: true

runs:
  using: composite
  steps:
    - name: Install node
      uses: actions/setup-node@v4
      with:
        node-version: ${{ inputs.node-version }}

    - name: Install yarn
      shell: bash
      run: npm install -g yarn
