# Configuration for probot-stale - https://github.com/probot/stale
# Limit the number of actions per hour, from 1-30. Default is 30
limitPerRun: 30

# Label to use when marking as stale
staleLabel: stale

# Issues or Pull Requests with these labels will never be considered stale. Set to `[]` to disable
exemptLabels:
  - security

pulls:
  daysUntilStale: 14
  daysUntilClose: 7
  markComment: >
    This pull request has been automatically marked as stale because it has not had
    recent activity. It will be closed if no further activity occurs. Thank you
    for your contributions.
issues:
  daysUntilStale: 180
  daysUntilClose: 14
  markComment: >
    This issue has been automatically marked as stale because it has not had
    recent activity. It will be closed if no further activity occurs. Thank you
   for your contributions.
