codecov:
  require_ci_to_pass: false
  notify:
    after_n_builds: 8
    wait_for_ci: true

ignore:
  - src/pages/automate/workflows/editor/visualBuilder/editors/TestFlowEditor.tsx
  - src/core/layout/panels/helpers/calculateSizes.ts
  - src/pages/aiAgent/Onboarding/components/OnboardingDevPreview/OnboardingDevPreview.tsx

coverage:
  status:
    project:
      default:
        target: auto
        threshold: 0.5%
        if_ci_failed: error
        branches:
          - '!revert*'
          - '!revert-*'

    patch:
      default:
        target: 80%
        threshold: 0.5%
        if_ci_failed: error
        branches:
          - '!revert*'
          - '!revert-*'
