codecov:
  require_ci_to_pass: false
  notify:
    after_n_builds: 10
    wait_for_ci: true

flag_management:
  default_rules:
    carryforward: true

comment:
  layout: 'diff, flags, files'
  require_changes: false
  require_base: no
  require_head: yes
  show_carryforward_flags: true

ignore:
  - src/pages/integrations/integration/components/gorgias_chat/GorgiasChatCreationWizard/**/*
  - apps/helpdesk/src/pages/integrations/integration/components/gorgias_chat/GorgiasChatCreationWizard/revamp/**/*
  - src/core/layout/panels/helpers/calculateSizes.ts
  - src/pages/automate/workflows/editor/visualBuilder/editors/TestFlowEditor.tsx
  - src/pages/aiAgent/Onboarding/components/OnboardingDevPreview/OnboardingDevPreview.tsx
  - src/pages/common/components/infobar/InfobarLayout.tsx
  - src/settings/**/*
  - src/pages/automate/articleRecommendation/ArticleRecommendationView.tsx
  - src/pages/automate/orderManagement/**/*
  - src/pages/settings/common/SettingsNavbar/config.tsx
  - src/routes/settings/Settings.tsx
  - src/main/init/index.tsx
  - src/pages/settings/helpCenter/utils/algolia.ts
  - src/pages/common/hooks/useAutoScrollOnDragging.ts
  - src/routes/Routes.tsx
  - src/pages/automate/workflows/utils/testVisualBuilderScaffolding.tsx
  - src/tests/mockedReactFlow.ts
  - /**/index.ts

coverage:
  status:
    project:
      default:
        target: auto
        threshold: 0.5%
        if_ci_failed: error
        branches:
          - '!revert*'
          - '!revert-*'

    patch:
      default:
        target: 80%
        threshold: 0.5%
        if_ci_failed: error
        branches:
          - '!revert*'
          - '!revert-*'
