overrides:
  '@tanstack/react-query': '4.36.1'
  '@types/escodegen': '^0.0.10'
  '@formatjs/ecma402-abstract': '1.11.4'
  'jquery': '3.5.1'
  'json-schema': '0.4.0'
  '@emotion/styled-base': '10.0.31'
  'isomorphic-fetch': '^3.0.0'

catalogs:
  rest-api-sdk:
    '@gorgias/helpdesk-queries': '0.8.2'
    '@gorgias/helpdesk-validators': '0.7.25'
    '@gorgias/helpdesk-client': '0.8.2'
    '@gorgias/helpdesk-types': '0.7.25'
    '@tanstack/react-query': '4.36.1'
  react:
    react: '17.0.2'
    react-dom: '17.0.2'
    react-test-renderer: '17.0.2'
    '@types/react': '17.0.83'
    '@types/react-dom': '17.0.26'
