packages:
  - 'apps/**'
  - 'core/**'
  - 'configs/**'
  - 'utils/**'

overrides:
  '@tanstack/react-query': '4.36.1'
  '@types/escodegen': '^0.0.10'
  '@formatjs/ecma402-abstract': '1.11.4'
  'jquery': '3.5.1'
  'json-schema': '0.4.0'
  '@emotion/styled-base': '10.0.31'
  'isomorphic-fetch': '^3.0.0'

catalogs:
  rest-api-sdk:
    '@gorgias/helpdesk-client': '^0.10.14'
    '@gorgias/helpdesk-mocks': '^0.7.75'
    '@gorgias/helpdesk-queries': '^0.9.31'
    '@gorgias/helpdesk-spec': '^0.11.29'
    '@gorgias/helpdesk-types': '^0.8.3'
    '@gorgias/helpdesk-validators': '^0.7.74'
    '@gorgias/knowledge-service-client': '^0.3.3'
    '@gorgias/knowledge-service-mocks': '^0.2.22'
    '@gorgias/knowledge-service-queries': '^0.2.22'
    '@gorgias/knowledge-service-types': '^0.2.16'
    '@gorgias/knowledge-service-validators': '^0.2.20'
    '@gorgias/convert-client': '^0.3.1'
    '@gorgias/help-center-client': '^0.3.0'
    '@gorgias/help-center-mocks': '^0.2.14'
    '@gorgias/help-center-queries': '^0.2.14'
    '@gorgias/help-center-types': '^0.2.8'
    '@gorgias/help-center-validators': '^0.2.12'
    '@tanstack/react-query': '4.36.1'
  react:
    react: '18.2.0'
    react-dom: '18.2.0'
    react-test-renderer: '18.2.0'
    '@types/react': '18.2.67'
    '@types/react-dom': '18.2.22'
  jest:
    '@jest/expect': '29.7.0'
    '@swc/core': '^1.10.11'
    '@swc/jest': '^0.2.37'
    '@types/jest': '^29.5.12'
    '@types/jsdom': '16.2.15'
    'jest': '^29.7.0'
    'jest-environment-jsdom': '^29.7.0'
    'jest-fixed-jsdom': '^0.0.9'
    'jest-immutable-matchers': '3.0.0'
    'jest-junit': '^16'
    'jest-launchdarkly-mock': '2.0.3'
    'jest-matcher-utils': '^29.7.0'
    'jest-mock': '^29.7.0'
    'jsdom': '21.0.0'
    'swc_mut_cjs_exports': '^10.7.0'
    '@types/testing-library__jest-dom': '5.14.1'
  testing-library:
    '@testing-library/dom': '^10.4.0'
    '@testing-library/jest-dom': '5.16.5'
    '@testing-library/react': '14.0.0'
    '@testing-library/user-event': '14.5.2'
  typescript:
    'typescript': '5.3.3'
  prettier:
    'prettier': '3.6.2'
    '@trivago/prettier-plugin-sort-imports': '^5.2.2'
  oxlint:
    'oxlint': '^0.16.3'
  lodash:
    'lodash': '4.17.21'
    '@types/lodash': '4.14.158'
