import fs from 'node:fs'
import path from 'node:path'

import { defineConfig, deprecationPlugin } from '@gorgias/static-analysis'

export default defineConfig({
    moduleGraphOptions: {
        rootDir: path.resolve(__dirname, 'apps/helpdesk/src'),
        modules: ['node_modules', 'node_modules/@types'],
        alias: {
            '@knocklabs/types': [
                path.resolve(
                    __dirname,
                    'apps/helpdesk/node_modules/@knocklabs/types/src/index.d.ts',
                ),
            ],
        },
        tsconfig: {
            configFile: path.resolve(__dirname, 'apps/helpdesk/tsconfig.json'),
        },
    },
    plugins: [
        deprecationPlugin({
            report: (results) => {
                fs.writeFileSync(
                    'scripts/deprecated-monitoring/deprecated.snapshot.json',
                    JSON.stringify(results, null, 2),
                )
            },
            deprecatedPackages: [
                {
                    name: 'launchdarkly-react-client-sdk',
                    // Use the useFlag hook (@repo/feature-flags) instead
                    // More context: https://www.notion.so/gorgias/How-to-use-Feature-flags-54fb0f6329b04d21970f42f295d1ef02?pvs=4#1921ae2178f580c99babe154b7116151
                    imports: ['useFlags', 'LD', 'LDProvider'],
                    type: 'feature-flag cleanup initiative',
                    date: '2025-02-10',
                },
                {
                    name: 'reactstrap',
                    imports: [
                        'Alert',
                        'Badge',
                        'Breadcrumb',
                        'BreadcrumbItem',
                        'Button',
                        'Card',
                        'CardBody',
                        'CardHeader',
                        'CardImg',
                        'CardSubtitle',
                        'CardTitle',
                        'Col',
                        'Collapse',
                        'Container',
                        'Dropdown',
                        'DropdownItem',
                        'DropdownMenu',
                        'DropdownToggle',
                        'Form',
                        'FormFeedback',
                        'FormGroup',
                        'FormText',
                        'Input',
                        'InputGroup',
                        'InputGroupAddon',
                        'Label',
                        'ListGroup',
                        'ListGroupItem',
                        'Modal',
                        'ModalBody',
                        'ModalFooter',
                        'ModalHeader',
                        'ModalProps',
                        'Nav',
                        'Navbar',
                        'NavItem',
                        'NavLink',
                        'Popover',
                        'PopoverBody',
                        'PopoverHeader',
                        'PopoverProps',
                        'Progress',
                        'Row',
                        'Table',
                        'Tooltip',
                        'UncontrolledButtonDropdown',
                        'UncontrolledDropdown',
                        'UncontrolledTooltip',
                        'UncontrolledTooltipProps',
                    ],
                    type: 'ui-kit-migration',
                    date: '2025-08-12',
                },
                //
                //  axiom related Legacy component deprecations
                {
                    name: '@gorgias/axiom',
                    imports: [
                        'LegacyButton',
                        'LegacyIconButton',
                        'LegacySelectField',
                        'LegacySelectFieldOption',
                        'LegacySelectFieldProps',
                        'LegacySelectFieldRawOption',
                        'LegacySelectFieldTriggerProps',
                        'LegacyTextField',
                        'LegacyTextFieldProps',
                        'LegacyInput',
                        'LegacyInputProps',
                        'LegacyShortcutKey',
                        'LegacyShortcutKeyProps',
                        'LegacyAvatar',
                        'LegacyAvatarProps',
                        'LegacyTooltip',
                        'LegacyTooltipProps',
                        'LegacyTooltipTrigger',
                        'LegacyTooltipPlacement',
                        'LegacyTag',
                        'LegacyTagProps',
                        'LegacyLabel',
                        'LegacyLabelProps',
                        'LegacyToggleField',
                        'LegacyToggleFieldProps',
                        'LegacyCheckboxField',
                        'LegacyCheckboxFieldProps',
                        'LegacyTabNavigation',
                        'LegacyTabNavigationProps',
                        'LegacyBadge',
                        'LegacyBadgeProps',
                        'LegacyBanner',
                        'LegacyBannerFillStyle',
                        'LegacyBannerType',
                        'LegacyBannerVariant',
                        'LegacyChip',
                        'LegacyChipProps',
                        'LegacyProgressBar',
                        'LegacyProgressBarProps',
                        'LegacyLoadingSpinner',
                        'LegacyLoadingSpinnerProps',
                        'LegacyColorType',
                    ],
                    type: 'ui-kit-migration',
                    date: '2025-10-15',
                },
            ],
        }),
    ],
})
