import type { FlatAlgoliaSearchResults } from '../../providers/SearchContext'

export const searchResultsResponseFixture: FlatAlgoliaSearchResults = [
    {
        gorgias_domain: 'goose.gorgias.docker',
        custom_domain: '',
        title: 'Sub cat 5 mod',
        preview: '',
        slug: 'sub-cat-5-mod',
        title_draft: 'Sub cat 5 mod',
        preview_draft: '',
        slug_draft: 'sub-cat-5-mod',
        parent_category_1: {
            id: 28,
            description: '',
            title: 'Cat 1 mod',
            customer_visibility: 'PUBLIC',
        },
        parent_category_2: null,
        parent_category_3: null,
        customer_visibility: 'PUBLIC',
        id: 39,
        help_center_id: 8,
        locale: 'en-US',
        type: 'category',
        _tags: ['level1', 'latest_draft', 'current'],
        objectID: 'category-39/en-US',
        _highlightResult: {
            title: {
                value: '<span class="search-highlight">Sub</span> cat 5 mod',
                matchLevel: 'full',
                fullyHighlighted: false,
                matchedWords: ['sub'],
            },
            preview: { value: '', matchLevel: 'none', matchedWords: [] },
            title_draft: {
                value: '<span class="search-highlight">Sub</span> cat 5 mod',
                matchLevel: 'full',
                fullyHighlighted: false,
                matchedWords: ['sub'],
            },
            preview_draft: {
                value: '',
                matchLevel: 'none',
                matchedWords: [],
            },
            parent_category_1: {
                description: {
                    value: '',
                    matchLevel: 'none',
                    matchedWords: [],
                },
                title: {
                    value: 'Cat 1 mod',
                    matchLevel: 'none',
                    matchedWords: [],
                },
            },
        },
    },
    {
        gorgias_domain: 'goose.gorgias.docker',
        custom_domain: '',
        title: 'Sub cat 4',
        preview: '',
        slug: 'sub-cat-4',
        title_draft: 'Sub cat 4',
        preview_draft: '',
        slug_draft: 'sub-cat-4',
        parent_category_1: {
            id: 28,
            description: '',
            title: 'Cat 1 mod',
            customer_visibility: 'PUBLIC',
        },
        parent_category_2: null,
        parent_category_3: null,
        customer_visibility: 'PUBLIC',
        id: 38,
        help_center_id: 8,
        locale: 'en-US',
        type: 'category',
        _tags: ['level1', 'latest_draft', 'current'],
        objectID: 'category-38/en-US',
        _highlightResult: {
            title: {
                value: '<span class="search-highlight">Sub</span> cat 4',
                matchLevel: 'full',
                fullyHighlighted: false,
                matchedWords: ['sub'],
            },
            preview: { value: '', matchLevel: 'none', matchedWords: [] },
            title_draft: {
                value: '<span class="search-highlight">Sub</span> cat 4',
                matchLevel: 'full',
                fullyHighlighted: false,
                matchedWords: ['sub'],
            },
            preview_draft: {
                value: '',
                matchLevel: 'none',
                matchedWords: [],
            },
            parent_category_1: {
                description: {
                    value: '',
                    matchLevel: 'none',
                    matchedWords: [],
                },
                title: {
                    value: 'Cat 1 mod',
                    matchLevel: 'none',
                    matchedWords: [],
                },
            },
        },
    },
    {
        gorgias_domain: 'goose.gorgias.docker',
        custom_domain: '',
        title: 'Sub cat 3',
        preview: '',
        slug: 'sub-cat-3',
        title_draft: 'Sub cat 3',
        preview_draft: '',
        slug_draft: 'sub-cat-3',
        parent_category_1: {
            id: 28,
            description: '',
            title: 'Cat 1 mod',
            customer_visibility: 'PUBLIC',
        },
        parent_category_2: null,
        parent_category_3: null,
        customer_visibility: 'PUBLIC',
        id: 37,
        help_center_id: 8,
        locale: 'en-US',
        type: 'category',
        _tags: ['level1', 'latest_draft', 'current'],
        objectID: 'category-37/en-US',
        _highlightResult: {
            title: {
                value: '<span class="search-highlight">Sub</span> cat 3',
                matchLevel: 'full',
                fullyHighlighted: false,
                matchedWords: ['sub'],
            },
            preview: { value: '', matchLevel: 'none', matchedWords: [] },
            title_draft: {
                value: '<span class="search-highlight">Sub</span> cat 3',
                matchLevel: 'full',
                fullyHighlighted: false,
                matchedWords: ['sub'],
            },
            preview_draft: {
                value: '',
                matchLevel: 'none',
                matchedWords: [],
            },
            parent_category_1: {
                description: {
                    value: '',
                    matchLevel: 'none',
                    matchedWords: [],
                },
                title: {
                    value: 'Cat 1 mod',
                    matchLevel: 'none',
                    matchedWords: [],
                },
            },
        },
    },
    {
        gorgias_domain: 'goose.gorgias.docker',
        custom_domain: '',
        title: 'Sub sub cat 2',
        preview: '',
        slug: 'sub-sub-cat-2',
        title_draft: 'Sub sub cat 2',
        preview_draft: '',
        slug_draft: 'sub-sub-cat-2',
        parent_category_1: {
            id: 35,
            description: '',
            title: 'Sub cat 2',
            customer_visibility: 'PUBLIC',
        },
        parent_category_2: {
            id: 28,
            description: '',
            title: 'Cat 1 mod',
            customer_visibility: 'PUBLIC',
        },
        parent_category_3: null,
        customer_visibility: 'PUBLIC',
        id: 36,
        help_center_id: 8,
        locale: 'en-US',
        type: 'category',
        _tags: ['level1', 'level2', 'latest_draft', 'current'],
        objectID: 'category-36/en-US',
        _highlightResult: {
            title: {
                value: '<span class="search-highlight">Sub</span> <span class="search-highlight">sub</span> cat 2',
                matchLevel: 'full',
                fullyHighlighted: false,
                matchedWords: ['sub'],
            },
            preview: { value: '', matchLevel: 'none', matchedWords: [] },
            title_draft: {
                value: '<span class="search-highlight">Sub</span> <span class="search-highlight">sub</span> cat 2',
                matchLevel: 'full',
                fullyHighlighted: false,
                matchedWords: ['sub'],
            },
            preview_draft: {
                value: '',
                matchLevel: 'none',
                matchedWords: [],
            },
            parent_category_1: {
                description: {
                    value: '',
                    matchLevel: 'none',
                    matchedWords: [],
                },
                title: {
                    value: '<span class="search-highlight">Sub</span> cat 2',
                    matchLevel: 'full',
                    fullyHighlighted: false,
                    matchedWords: ['sub'],
                },
            },
            parent_category_2: {
                description: {
                    value: '',
                    matchLevel: 'none',
                    matchedWords: [],
                },
                title: {
                    value: 'Cat 1 mod',
                    matchLevel: 'none',
                    matchedWords: [],
                },
            },
        },
    },
    {
        gorgias_domain: 'goose.gorgias.docker',
        custom_domain: '',
        title: 'Sub cat 2',
        preview: '',
        slug: 'sub-cat-2',
        title_draft: 'Sub cat 2',
        preview_draft: '',
        slug_draft: 'sub-cat-2',
        parent_category_1: {
            id: 28,
            description: '',
            title: 'Cat 1 mod',
            customer_visibility: 'PUBLIC',
        },
        parent_category_2: null,
        parent_category_3: null,
        customer_visibility: 'PUBLIC',
        id: 35,
        help_center_id: 8,
        locale: 'en-US',
        type: 'category',
        _tags: ['level1', 'latest_draft', 'current'],
        objectID: 'category-35/en-US',
        _highlightResult: {
            title: {
                value: '<span class="search-highlight">Sub</span> cat 2',
                matchLevel: 'full',
                fullyHighlighted: false,
                matchedWords: ['sub'],
            },
            preview: { value: '', matchLevel: 'none', matchedWords: [] },
            title_draft: {
                value: '<span class="search-highlight">Sub</span> cat 2',
                matchLevel: 'full',
                fullyHighlighted: false,
                matchedWords: ['sub'],
            },
            preview_draft: {
                value: '',
                matchLevel: 'none',
                matchedWords: [],
            },
            parent_category_1: {
                description: {
                    value: '',
                    matchLevel: 'none',
                    matchedWords: [],
                },
                title: {
                    value: 'Cat 1 mod',
                    matchLevel: 'none',
                    matchedWords: [],
                },
            },
        },
    },
    {
        gorgias_domain: 'goose.gorgias.docker',
        custom_domain: '',
        title: 'Sub sub sub cat 1',
        preview: '',
        slug: 'sub-sub-sub-cat-1',
        title_draft: 'Sub sub sub cat 1',
        preview_draft: '',
        slug_draft: 'sub-sub-sub-cat-1',
        parent_category_1: {
            id: 30,
            description: '',
            title: 'Sub sub cat 1',
            customer_visibility: 'PUBLIC',
        },
        parent_category_2: {
            id: 29,
            description: '',
            title: 'Sub cat 1',
            customer_visibility: 'PUBLIC',
        },
        parent_category_3: {
            id: 28,
            description: '',
            title: 'Cat 1 mod',
            customer_visibility: 'PUBLIC',
        },
        customer_visibility: 'PUBLIC',
        id: 31,
        help_center_id: 8,
        locale: 'en-US',
        type: 'category',
        _tags: ['level1', 'level2', 'level3', 'latest_draft', 'current'],
        objectID: 'category-31/en-US',
        _highlightResult: {
            title: {
                value: '<span class="search-highlight">Sub</span> <span class="search-highlight">sub</span> <span class="search-highlight">sub</span> cat 1',
                matchLevel: 'full',
                fullyHighlighted: false,
                matchedWords: ['sub'],
            },
            preview: { value: '', matchLevel: 'none', matchedWords: [] },
            title_draft: {
                value: '<span class="search-highlight">Sub</span> <span class="search-highlight">sub</span> <span class="search-highlight">sub</span> cat 1',
                matchLevel: 'full',
                fullyHighlighted: false,
                matchedWords: ['sub'],
            },
            preview_draft: {
                value: '',
                matchLevel: 'none',
                matchedWords: [],
            },
            parent_category_1: {
                description: {
                    value: '',
                    matchLevel: 'none',
                    matchedWords: [],
                },
                title: {
                    value: '<span class="search-highlight">Sub</span> <span class="search-highlight">sub</span> cat 1',
                    matchLevel: 'full',
                    fullyHighlighted: false,
                    matchedWords: ['sub'],
                },
            },
            parent_category_2: {
                description: {
                    value: '',
                    matchLevel: 'none',
                    matchedWords: [],
                },
                title: {
                    value: '<span class="search-highlight">Sub</span> cat 1',
                    matchLevel: 'full',
                    fullyHighlighted: false,
                    matchedWords: ['sub'],
                },
            },
            parent_category_3: {
                description: {
                    value: '',
                    matchLevel: 'none',
                    matchedWords: [],
                },
                title: {
                    value: 'Cat 1 mod',
                    matchLevel: 'none',
                    matchedWords: [],
                },
            },
        },
    },
    {
        gorgias_domain: 'goose.gorgias.docker',
        custom_domain: '',
        title: 'Sub sub cat 1',
        preview: '',
        slug: 'sub-sub-cat-1',
        title_draft: 'Sub sub cat 1',
        preview_draft: '',
        slug_draft: 'sub-sub-cat-1',
        parent_category_1: {
            id: 29,
            description: '',
            title: 'Sub cat 1',
            customer_visibility: 'PUBLIC',
        },
        parent_category_2: {
            id: 28,
            description: '',
            title: 'Cat 1 mod',
            customer_visibility: 'PUBLIC',
        },
        parent_category_3: null,
        customer_visibility: 'PUBLIC',
        id: 30,
        help_center_id: 8,
        locale: 'en-US',
        type: 'category',
        _tags: ['level1', 'level2', 'latest_draft', 'current'],
        objectID: 'category-30/en-US',
        _highlightResult: {
            title: {
                value: '<span class="search-highlight">Sub</span> <span class="search-highlight">sub</span> cat 1',
                matchLevel: 'full',
                fullyHighlighted: false,
                matchedWords: ['sub'],
            },
            preview: { value: '', matchLevel: 'none', matchedWords: [] },
            title_draft: {
                value: '<span class="search-highlight">Sub</span> <span class="search-highlight">sub</span> cat 1',
                matchLevel: 'full',
                fullyHighlighted: false,
                matchedWords: ['sub'],
            },
            preview_draft: {
                value: '',
                matchLevel: 'none',
                matchedWords: [],
            },
            parent_category_1: {
                description: {
                    value: '',
                    matchLevel: 'none',
                    matchedWords: [],
                },
                title: {
                    value: '<span class="search-highlight">Sub</span> cat 1',
                    matchLevel: 'full',
                    fullyHighlighted: false,
                    matchedWords: ['sub'],
                },
            },
            parent_category_2: {
                description: {
                    value: '',
                    matchLevel: 'none',
                    matchedWords: [],
                },
                title: {
                    value: 'Cat 1 mod',
                    matchLevel: 'none',
                    matchedWords: [],
                },
            },
        },
    },
    {
        gorgias_domain: 'goose.gorgias.docker',
        custom_domain: '',
        title: 'Sub cat 1',
        preview: '',
        slug: 'sub-cat-1',
        title_draft: 'Sub cat 1',
        preview_draft: '',
        slug_draft: 'sub-cat-1',
        parent_category_1: {
            id: 28,
            description: '',
            title: 'Cat 1 mod',
            customer_visibility: 'PUBLIC',
        },
        parent_category_2: null,
        parent_category_3: null,
        customer_visibility: 'PUBLIC',
        id: 29,
        help_center_id: 8,
        locale: 'en-US',
        type: 'category',
        _tags: ['level1', 'latest_draft', 'current'],
        objectID: 'category-29/en-US',
        _highlightResult: {
            title: {
                value: '<span class="search-highlight">Sub</span> cat 1',
                matchLevel: 'full',
                fullyHighlighted: false,
                matchedWords: ['sub'],
            },
            preview: { value: '', matchLevel: 'none', matchedWords: [] },
            title_draft: {
                value: '<span class="search-highlight">Sub</span> cat 1',
                matchLevel: 'full',
                fullyHighlighted: false,
                matchedWords: ['sub'],
            },
            preview_draft: {
                value: '',
                matchLevel: 'none',
                matchedWords: [],
            },
            parent_category_1: {
                description: {
                    value: '',
                    matchLevel: 'none',
                    matchedWords: [],
                },
                title: {
                    value: 'Cat 1 mod',
                    matchLevel: 'none',
                    matchedWords: [],
                },
            },
        },
    },
    {
        gorgias_domain: 'goose.gorgias.docker',
        custom_domain: '',
        title: 'art in sub cat 5 mod',
        preview: '',
        slug: 'art-in-sub-cat-5-mod',
        title_draft: 'art in sub cat 5 mod',
        preview_draft: '',
        slug_draft: 'art-in-sub-cat-5-mod',
        parent_category_1: {
            id: 39,
            description: '',
            title: 'Sub cat 5 mod',
            customer_visibility: 'PUBLIC',
        },
        parent_category_2: {
            id: 28,
            description: '',
            title: 'Cat 1 mod',
            customer_visibility: 'PUBLIC',
        },
        parent_category_3: null,
        customer_visibility: 'PUBLIC',
        id: 34,
        help_center_id: 8,
        locale: 'en-US',
        article_content: 'content of art in sub cat 5',
        article_content_draft: 'content of art in sub cat 5',
        parent_category_4: null,
        type: 'article',
        _tags: ['level1', 'level2', 'latest_draft', 'current'],
        objectID: 'article-34/en-US',
        _highlightResult: {
            title: {
                value: 'art in <span class="search-highlight">sub</span> cat 5 mod',
                matchLevel: 'full',
                fullyHighlighted: false,
                matchedWords: ['sub'],
            },
            preview: { value: '', matchLevel: 'none', matchedWords: [] },
            title_draft: {
                value: 'art in <span class="search-highlight">sub</span> cat 5 mod',
                matchLevel: 'full',
                fullyHighlighted: false,
                matchedWords: ['sub'],
            },
            preview_draft: {
                value: '',
                matchLevel: 'none',
                matchedWords: [],
            },
            parent_category_1: {
                description: {
                    value: '',
                    matchLevel: 'none',
                    matchedWords: [],
                },
                title: {
                    value: '<span class="search-highlight">Sub</span> cat 5 mod',
                    matchLevel: 'full',
                    fullyHighlighted: false,
                    matchedWords: ['sub'],
                },
            },
            parent_category_2: {
                description: {
                    value: '',
                    matchLevel: 'none',
                    matchedWords: [],
                },
                title: {
                    value: 'Cat 1 mod',
                    matchLevel: 'none',
                    matchedWords: [],
                },
            },
            article_content: {
                value: 'content of art in <span class="search-highlight">sub</span> cat 5',
                matchLevel: 'full',
                fullyHighlighted: false,
                matchedWords: ['sub'],
            },
            article_content_draft: {
                value: 'content of art in <span class="search-highlight">sub</span> cat 5',
                matchLevel: 'full',
                fullyHighlighted: false,
                matchedWords: ['sub'],
            },
        },
    },
    {
        gorgias_domain: 'goose.gorgias.docker',
        custom_domain: '',
        title: 'Article 2 in sub sub sub cat 1 copy new title',
        preview: '',
        slug: 'article-2-in-sub-sub-sub-cat-1-copy-new-title',
        title_draft: 'Article 2 in sub sub sub cat 1 copy new title',
        preview_draft: '',
        slug_draft: 'article-2-in-sub-sub-sub-cat-1-copy-new-title',
        parent_category_1: {
            id: 31,
            description: '',
            title: 'Sub sub sub cat 1',
            customer_visibility: 'PUBLIC',
        },
        parent_category_2: {
            id: 30,
            description: '',
            title: 'Sub sub cat 1',
            customer_visibility: 'PUBLIC',
        },
        parent_category_3: {
            id: 29,
            description: '',
            title: 'Sub cat 1',
            customer_visibility: 'PUBLIC',
        },
        customer_visibility: 'PUBLIC',
        id: 32,
        help_center_id: 8,
        locale: 'en-US',
        article_content: 'Contents of article 2 in sub sub sub cat 1 caaaat',
        article_content_draft:
            'Contents of article 2 in sub sub sub cat 1 caaaat',
        parent_category_4: {
            id: 28,
            description: '',
            title: 'Cat 1 mod',
            customer_visibility: 'PUBLIC',
        },
        type: 'article',
        _tags: [
            'level1',
            'level2',
            'level3',
            'level4',
            'latest_draft',
            'current',
        ],
        objectID: 'article-32/en-US',
        _highlightResult: {
            title: {
                value: 'Article 2 in <span class="search-highlight">sub</span> <span class="search-highlight">sub</span> <span class="search-highlight">sub</span> cat 1 copy new title',
                matchLevel: 'full',
                fullyHighlighted: false,
                matchedWords: ['sub'],
            },
            preview: { value: '', matchLevel: 'none', matchedWords: [] },
            title_draft: {
                value: 'Article 2 in <span class="search-highlight">sub</span> <span class="search-highlight">sub</span> <span class="search-highlight">sub</span> cat 1 copy new title',
                matchLevel: 'full',
                fullyHighlighted: false,
                matchedWords: ['sub'],
            },
            preview_draft: {
                value: '',
                matchLevel: 'none',
                matchedWords: [],
            },
            parent_category_1: {
                description: {
                    value: '',
                    matchLevel: 'none',
                    matchedWords: [],
                },
                title: {
                    value: '<span class="search-highlight">Sub</span> <span class="search-highlight">sub</span> <span class="search-highlight">sub</span> cat 1',
                    matchLevel: 'full',
                    fullyHighlighted: false,
                    matchedWords: ['sub'],
                },
            },
            parent_category_2: {
                description: {
                    value: '',
                    matchLevel: 'none',
                    matchedWords: [],
                },
                title: {
                    value: '<span class="search-highlight">Sub</span> <span class="search-highlight">sub</span> cat 1',
                    matchLevel: 'full',
                    fullyHighlighted: false,
                    matchedWords: ['sub'],
                },
            },
            parent_category_3: {
                description: {
                    value: '',
                    matchLevel: 'none',
                    matchedWords: [],
                },
                title: {
                    value: '<span class="search-highlight">Sub</span> cat 1',
                    matchLevel: 'full',
                    fullyHighlighted: false,
                    matchedWords: ['sub'],
                },
            },
            article_content: {
                value: 'Contents of article 2 in <span class="search-highlight">sub</span> <span class="search-highlight">sub</span> <span class="search-highlight">sub</span> cat 1 caaaat',
                matchLevel: 'full',
                fullyHighlighted: false,
                matchedWords: ['sub'],
            },
            article_content_draft: {
                value: 'Contents of article 2 in <span class="search-highlight">sub</span> <span class="search-highlight">sub</span> <span class="search-highlight">sub</span> cat 1 caaaat',
                matchLevel: 'full',
                fullyHighlighted: false,
                matchedWords: ['sub'],
            },
            parent_category_4: {
                description: {
                    value: '',
                    matchLevel: 'none',
                    matchedWords: [],
                },
                title: {
                    value: 'Cat 1 mod',
                    matchLevel: 'none',
                    matchedWords: [],
                },
            },
        },
    },
    {
        gorgias_domain: 'goose.gorgias.docker',
        custom_domain: '',
        title: 'Article 2 in sub sub sub cat 1 copy new ti',
        preview: 'Contents of article 2 in sub sub sub cat 1 bis',
        slug: 'article-2-in-sub-sub-sub-cat-1-copy-new-ti',
        title_draft: 'Article 2 in sub sub sub cat 1 copy new ti',
        preview_draft: 'Contents of article 2 in sub sub sub cat 1 bis',
        slug_draft: 'article-2-in-sub-sub-sub-cat-1-copy-new-ti',
        parent_category_1: {
            id: 31,
            description: '',
            title: 'Sub sub sub cat 1',
            customer_visibility: 'PUBLIC',
        },
        parent_category_2: {
            id: 30,
            description: '',
            title: 'Sub sub cat 1',
            customer_visibility: 'PUBLIC',
        },
        parent_category_3: {
            id: 29,
            description: '',
            title: 'Sub cat 1',
            customer_visibility: 'PUBLIC',
        },
        customer_visibility: 'PUBLIC',
        id: 31,
        help_center_id: 8,
        locale: 'en-US',
        article_content: 'Contents of article 2 in sub sub sub cat 1 tt',
        article_content_draft: 'Contents of article 2 in sub sub sub cat 1 tt',
        parent_category_4: {
            id: 28,
            description: '',
            title: 'Cat 1 mod',
            customer_visibility: 'PUBLIC',
        },
        type: 'article',
        _tags: [
            'level1',
            'level2',
            'level3',
            'level4',
            'latest_draft',
            'current',
        ],
        objectID: 'article-31/en-US',
        _highlightResult: {
            title: {
                value: 'Article 2 in <span class="search-highlight">sub</span> <span class="search-highlight">sub</span> <span class="search-highlight">sub</span> cat 1 copy new ti',
                matchLevel: 'full',
                fullyHighlighted: false,
                matchedWords: ['sub'],
            },
            preview: {
                value: 'Contents of article 2 in <span class="search-highlight">sub</span> <span class="search-highlight">sub</span> <span class="search-highlight">sub</span> cat 1 bis',
                matchLevel: 'full',
                fullyHighlighted: false,
                matchedWords: ['sub'],
            },
            title_draft: {
                value: 'Article 2 in <span class="search-highlight">sub</span> <span class="search-highlight">sub</span> <span class="search-highlight">sub</span> cat 1 copy new ti',
                matchLevel: 'full',
                fullyHighlighted: false,
                matchedWords: ['sub'],
            },
            preview_draft: {
                value: 'Contents of article 2 in <span class="search-highlight">sub</span> <span class="search-highlight">sub</span> <span class="search-highlight">sub</span> cat 1 bis',
                matchLevel: 'full',
                fullyHighlighted: false,
                matchedWords: ['sub'],
            },
            parent_category_1: {
                description: {
                    value: '',
                    matchLevel: 'none',
                    matchedWords: [],
                },
                title: {
                    value: '<span class="search-highlight">Sub</span> <span class="search-highlight">sub</span> <span class="search-highlight">sub</span> cat 1',
                    matchLevel: 'full',
                    fullyHighlighted: false,
                    matchedWords: ['sub'],
                },
            },
            parent_category_2: {
                description: {
                    value: '',
                    matchLevel: 'none',
                    matchedWords: [],
                },
                title: {
                    value: '<span class="search-highlight">Sub</span> <span class="search-highlight">sub</span> cat 1',
                    matchLevel: 'full',
                    fullyHighlighted: false,
                    matchedWords: ['sub'],
                },
            },
            parent_category_3: {
                description: {
                    value: '',
                    matchLevel: 'none',
                    matchedWords: [],
                },
                title: {
                    value: '<span class="search-highlight">Sub</span> cat 1',
                    matchLevel: 'full',
                    fullyHighlighted: false,
                    matchedWords: ['sub'],
                },
            },
            article_content: {
                value: 'Contents of article 2 in <span class="search-highlight">sub</span> <span class="search-highlight">sub</span> <span class="search-highlight">sub</span> cat 1 tt',
                matchLevel: 'full',
                fullyHighlighted: false,
                matchedWords: ['sub'],
            },
            article_content_draft: {
                value: 'Contents of article 2 in <span class="search-highlight">sub</span> <span class="search-highlight">sub</span> <span class="search-highlight">sub</span> cat 1 tt',
                matchLevel: 'full',
                fullyHighlighted: false,
                matchedWords: ['sub'],
            },
            parent_category_4: {
                description: {
                    value: '',
                    matchLevel: 'none',
                    matchedWords: [],
                },
                title: {
                    value: 'Cat 1 mod',
                    matchLevel: 'none',
                    matchedWords: [],
                },
            },
        },
    },
    {
        gorgias_domain: 'goose.gorgias.docker',
        custom_domain: '',
        title: 'Article 2 in sub sub sub cat 1',
        preview: '',
        slug: 'article-2-in-sub-sub-sub-cat-1',
        title_draft: 'Article 2 in sub sub sub cat 1',
        preview_draft: '',
        slug_draft: 'article-2-in-sub-sub-sub-cat-1',
        parent_category_1: {
            id: 31,
            description: '',
            title: 'Sub sub sub cat 1',
            customer_visibility: 'PUBLIC',
        },
        parent_category_2: {
            id: 30,
            description: '',
            title: 'Sub sub cat 1',
            customer_visibility: 'PUBLIC',
        },
        parent_category_3: {
            id: 29,
            description: '',
            title: 'Sub cat 1',
            customer_visibility: 'PUBLIC',
        },
        customer_visibility: 'PUBLIC',
        id: 29,
        help_center_id: 8,
        locale: 'en-US',
        article_content: 'Contents of article 2 in sub sub sub cat 1',
        article_content_draft: 'Contents of article 2 in sub sub sub cat 1',
        parent_category_4: {
            id: 28,
            description: '',
            title: 'Cat 1 mod',
            customer_visibility: 'PUBLIC',
        },
        type: 'article',
        _tags: [
            'level1',
            'level2',
            'level3',
            'level4',
            'latest_draft',
            'current',
        ],
        objectID: 'article-29/en-US',
        _highlightResult: {
            title: {
                value: 'Article 2 in <span class="search-highlight">sub</span> <span class="search-highlight">sub</span> <span class="search-highlight">sub</span> cat 1',
                matchLevel: 'full',
                fullyHighlighted: false,
                matchedWords: ['sub'],
            },
            preview: { value: '', matchLevel: 'none', matchedWords: [] },
            title_draft: {
                value: 'Article 2 in <span class="search-highlight">sub</span> <span class="search-highlight">sub</span> <span class="search-highlight">sub</span> cat 1',
                matchLevel: 'full',
                fullyHighlighted: false,
                matchedWords: ['sub'],
            },
            preview_draft: {
                value: '',
                matchLevel: 'none',
                matchedWords: [],
            },
            parent_category_1: {
                description: {
                    value: '',
                    matchLevel: 'none',
                    matchedWords: [],
                },
                title: {
                    value: '<span class="search-highlight">Sub</span> <span class="search-highlight">sub</span> <span class="search-highlight">sub</span> cat 1',
                    matchLevel: 'full',
                    fullyHighlighted: false,
                    matchedWords: ['sub'],
                },
            },
            parent_category_2: {
                description: {
                    value: '',
                    matchLevel: 'none',
                    matchedWords: [],
                },
                title: {
                    value: '<span class="search-highlight">Sub</span> <span class="search-highlight">sub</span> cat 1',
                    matchLevel: 'full',
                    fullyHighlighted: false,
                    matchedWords: ['sub'],
                },
            },
            parent_category_3: {
                description: {
                    value: '',
                    matchLevel: 'none',
                    matchedWords: [],
                },
                title: {
                    value: '<span class="search-highlight">Sub</span> cat 1',
                    matchLevel: 'full',
                    fullyHighlighted: false,
                    matchedWords: ['sub'],
                },
            },
            article_content: {
                value: 'Contents of article 2 in <span class="search-highlight">sub</span> <span class="search-highlight">sub</span> <span class="search-highlight">sub</span> cat 1',
                matchLevel: 'full',
                fullyHighlighted: false,
                matchedWords: ['sub'],
            },
            article_content_draft: {
                value: 'Contents of article 2 in <span class="search-highlight">sub</span> <span class="search-highlight">sub</span> <span class="search-highlight">sub</span> cat 1',
                matchLevel: 'full',
                fullyHighlighted: false,
                matchedWords: ['sub'],
            },
            parent_category_4: {
                description: {
                    value: '',
                    matchLevel: 'none',
                    matchedWords: [],
                },
                title: {
                    value: 'Cat 1 mod',
                    matchLevel: 'none',
                    matchedWords: [],
                },
            },
        },
    },
]
