export const CONVERT_ROUTE_PARAM_NAME = 'id'

export const CONVERT_ROUTING_PARAM = `:${CONVERT_ROUTE_PARAM_NAME}`

export const CONVERT_ROUTE_CAMPAIGN_PARAM_NAME = 'campaignId'

export const CONVERT_ROUTING_CAMPAIGN_PARAM = `:${CONVERT_ROUTE_CAMPAIGN_PARAM_NAME}`

export const CONVERT_ROUTE_TEMPLATE_PARAM_NAME = 'templateSlug'

export const CONVERT_ROUTING_TEMPLATE_PARAM = `:${CONVERT_ROUTE_TEMPLATE_PARAM_NAME}`

export const MAX_EXPANDED_SECTIONS_BY_DEFAULT = 3

export const CONVERT_NAVBAR_COLLAPSED_SECTIONS_KEY =
    'convert:navbar:collapsed-cvt-sections'
