export const SUBMIT_ACTIVITY_START = 'SUBMIT_ACTIVITY_START'
export const SUBMIT_ACTIVITY_DISCARD = 'SUBMIT_ACTIVITY_DISCARD'
export const SUBMIT_ACTIVITY_SUCCESS = 'SUBMIT_ACTIVITY_SUCCESS'
export const SUBMIT_ACTIVITY_ERROR = 'SUBMIT_ACTIVITY_ERROR'

export const TICKET_VIEWED = 'TICKET_VIEWED'
