export const SUBMIT_ACTIVITY_START = 'SUBMIT_ACTIVITY_START'
export const SUBMIT_ACTIVITY_SUCCESS = 'SUBMIT_ACTIVITY_SUCCESS'
export const SUBMIT_ACTIVITY_ERROR = 'SUBMIT_ACTIVITY_ERROR'

export const SUBMIT_CHATS_SUCCESS = 'SUBMIT_CHATS_SUCCESS'

export const TICKET_VIEWED = 'TICKET_VIEWED'
