export const KLAVIYO_INITIAL_SYNC_SYNCING = 'syncing'
export const KLAVIYO_INITIAL_SYNC_SYNCED = 'synced'
export const KLAVIYO_INITIAL_SYNC_STATUS = [
    KLAVIYO_INITIAL_SYNC_SYNCING,
    KLAVIYO_INITIAL_SYNC_SYNCED,
]
