export const FETCH_USER_AUTHS_SUCCESS = 'FETCH_USER_AUTHS_SUCCESS'
export const FETCH_USER_AUTHS_ERROR = 'FETCH_USER_AUTHS_ERROR'
export const RESET_API_KEY_SUCCESS = 'RESET_API_KEY_SUCCESS'
export const RESET_API_KEY_ERROR = 'RESET_API_KEY_ERROR'
