export { isViewDeactivated } from './isViewDeactivated'
export { isViewHighPriority } from './isViewHighPriority'
export { isViewLowPriority } from './isViewLowPriority'
export { isViewRealtime } from './isViewRealtime'
export { isViewSystem } from './isViewSystem'
