import 'tickets/notifications/initTicketUpdates'
import 'automate/notifications/init'
import 'tickets/notifications/initNewMessages'
import 'integrations/notifications/init'
import 'pages/settings/historicalImports/notifications/registerNotificationsConfig'
