import {Components} from 'rest_api/help_center_api/client.generated'

// GENERAL

export type Locale = Components.Schemas.LocaleDto
export type LocaleCode = Components.Schemas.LocaleDto['code']

// HELP CENTER

export type CreateHelpCenterDto = Omit<
    Components.Schemas.CreateHelpCenterWithAccountIdDto,
    'account_id'
>
export type UpdateHelpCenterDto = Components.Schemas.UpdateHelpCenterDto
export type CreateHelpCenterTranslationDto =
    Components.Schemas.CreateHelpCenterTranslationDto

export type HelpCentersListPage = Components.Schemas.HelpCentersListPageDto
export type HelpCenterTranslation = Components.Schemas.HelpCenterTranslationDto
export type HelpCenterTranslationSeoMeta =
    Components.Schemas.HelpCenterTranslationSeoMeta

export type HelpCenter = Omit<
    Components.Schemas.HelpCenterDto,
    'contact_form'
> & {
    customDomain?: CustomDomain
    translations?: HelpCenterTranslation[]
}

// CONTACT INFO

export type ContactInfoDto = Components.Schemas.ContactInfoDto
export type ChatContactInfoDto = Components.Schemas.ChatContactInfoDto
export type EmailContactInfoDto = Components.Schemas.EmailContactInfoDto
export type PhoneContactInfoDto = Components.Schemas.PhoneContactInfoDto
export type ContactPhoneNumber = Components.Schemas.ContactPhoneNumber

export type EmailIntegration = {
    email: string | null
    id: number | null
}

// CATEGORIES

export type CreateCategoryDto = Components.Schemas.CreateCategoryDto
export type CreateCategoryTranslationDto =
    Components.Schemas.CreateCategoryTranslationDto
export type UpdateCategoryTranslationDto =
    Components.Schemas.UpdateCategoryTranslationDto

export type CategoriesListPage = Components.Schemas.CategoriesListPageDto
export type CategoryWithLocalTranslation = Components.Schemas.CategoryTreeDto
export type CategoryTranslation = Components.Schemas.CategoryTranslationDto
export type CategoryTranslationSeoMeta =
    Components.Schemas.CategoryTranslationSeoMeta
export type LocalCategoryTranslation =
    Components.Schemas.LocalCategoryTranslation

export type Category = Omit<CategoryWithLocalTranslation, 'children'> & {
    children: number[]
    articleCount: number
}

export type NonRootCategory = Omit<Category, 'translation'> & {
    translation: NonNullable<Category['translation']>
}

// ARTICLES

export type CreateArticleDto = Components.Schemas.CreateArticleDto
export type CreateArticleTranslationDto =
    Components.Schemas.CreateArticleTranslationDto
export type UpdateArticleTranslationDto =
    Components.Schemas.UpdateArticleTranslationDto

export type ArticlesListPage = Components.Schemas.ArticlesListPageDto
export type ArticleWithLocalTranslationAndRating =
    Components.Schemas.ArticleListDataDto
export type ArticleWithLocalTranslation =
    Components.Schemas.ArticleWithLocalTranslation
export type Rating = Components.Schemas.Rating

export type ArticleTranslationWithRating =
    Components.Schemas.ArticleTranslationWithRating
export type ArticleTranslationSeoMeta =
    Components.Schemas.ArticleTranslationSeoMeta
export type LocalArticleTranslation = Components.Schemas.LocalArticleTranslation

export type Article = ArticleWithLocalTranslationAndRating & {
    position: number
}

export type VisibilityStatus =
    Components.Schemas.LocalArticleTranslation['visibility_status']

// NAVIGATION

export type CreateNavigationLinkDto = Components.Schemas.CreateNavigationLinkDto
export type UpdateNavigationLinkDto = Components.Schemas.UpdateNavigationLinkDto

export type NavigationLinksListPage =
    Components.Schemas.NavigationLinksListPageDto
export type NavigationLink = Components.Schemas.NavigationLinkDto
export type NavigationLinkMeta = Components.Schemas.NavigationLinkMeta
export type NavigationLinkGroup = Components.Schemas.NavigationLinkDto['group']

export type LocalNavigationLink = Pick<
    Components.Schemas.NavigationLinkDto,
    | 'id'
    | 'label'
    | 'value'
    | 'locale'
    | 'group'
    | 'created_datetime'
    | 'updated_datetime'
> & {
    key: string
}
export type LocalSocialNavigationLink = Pick<
    Components.Schemas.NavigationLinkDto,
    | 'id'
    | 'label'
    | 'value'
    | 'group'
    | 'meta'
    | 'created_datetime'
    | 'updated_datetime'
>

// CUSTOM DOMAIN

export type CustomDomain = Components.Schemas.CustomDomain
export type CustomDomainsListPage = Components.Schemas.CustomDomainsListPageDto

// IMPORTS

export type CsvColumnPreview = Components.Schemas.AnalyseCsvResponseColumnDto

export type ColumnSourceCsv = Components.Schemas.ColumnSourceCsv
export type ColumnSourceAutoGenerated =
    Components.Schemas.ColumnSourceAutoGenerated
export type ColumnSourceCsvOrAutoGenerated =
    Components.Schemas.ColumnSourceCsvOrAutoGenerated
export type ColumnSourceCsvOnly = Components.Schemas.ColumnSourceCsvOnly

export const isColumnSourceCsv = (
    value: ColumnSourceCsv | ColumnSourceAutoGenerated
): value is ColumnSourceCsv => value.kind === 'CSV_COLUMN'

export const isArticleWithExistingTranslation = (
    value: Article | Components.Schemas.CreateArticleDto
): value is Article =>
    'translation' in value && 'updated_datetime' in value.translation

// EXTRA HTML

export type ExtraHTML = Components.Schemas.ExtraHTML
export type ExtraHTMLDto = Components.Schemas.ExtraHTMLDto
export type UpdateExtraHTMLDto = Components.Schemas.UpdateExtraHTMLDto

// AUTOMATION SETTINGS

export type HelpCenterAutomationSettings =
    Components.Schemas.AutomationSettingsDto

// PAGE EMBEDMENT
export type HelpCenterPageEmbedment = Components.Schemas.PageEmbedmentDto

// ARTICLE TEMPLATE
export type ArticleTemplate = Components.Schemas.ArticleTemplateDto

// HELP CENTER CREATION WIZARD
export enum HelpCenterCreationWizardStep {
    Initialization = 'initialization',
    Basics = 'basics',
    Branding = 'branding',
    Articles = 'articles',
    Automate = 'automate',
}

export enum HelpCenterAutomateType {
    NON_AUTOMATE = 'non-automate',
    AUTOMATE_NO_STORE = 'automate-no-store',
    AUTOMATE = 'automate',
}

export type ArticleTemplateCategory =
    | 'orderManagement'
    | 'returnsAndRefunds'
    | 'shippingAndDelivery'

export type HelpCenterArticleItem = ArticleTemplate & {
    id?: number
    isSelected?: boolean
}
