export const FETCH_STAT_STARTED = 'STAT/FETCH_STAT_STARTED'
export const FETCH_STAT_ENDED = 'STAT/FETCH_STAT_ENDED'
export const STAT_FILTERS_DIRTY = 'STAT/STAT_FILTERS_DIRTY'
export const STAT_FILTERS_CLEAN = 'STAT/STAT_FILTERS_CLEAN'
