export const FETCH_STAT_STARTED = 'STAT/FETCH_STAT_STARTED'
export const FETCH_STAT_ENDED = 'STAT/FETCH_STAT_ENDED'
export const STAT_FILTERS_DIRTY = 'STAT/STAT_FILTERS_DIRTY'
export const STAT_FILTERS_CLEAN = 'STAT/STAT_FILTERS_CLEAN'
export const STAT_FILTERS_CLEAN_W_PAYLOAD = 'STAT/STAT_FILTERS_CLEAN_W_PAYLOAD'
export const STAT_FILTERS_WITH_LOGICAL_OPERATOR_CLEAN_W_PAYLOAD =
    'STAT/STAT_FILTERS_WITH_LOGICAL_OPERATOR_CLEAN_W_PAYLOAD'

export const AGENT_PERFORMANCE_SLICE_NAME = 'agentPerformance'
export const AUTO_QA_AGENT_PERFORMANCE_SLICE_NAME = 'autoQAAgentPerformance'
