export const FETCH_INTEGRATIONS_START = 'FETCH_INTEGRATIONS_START'
export const FETCH_INTEGRATIONS_SUCCESS = 'FETCH_INTEGRATIONS_SUCCESS'
export const FETCH_INTEGRATIONS_ERROR = 'FETCH_INTEGRATIONS_ERROR'

export const TEST_HTTP_INTEGRATION_START = 'TEST_HTTP_INTEGRATION_START'
export const TEST_HTTP_INTEGRATION_SUCCESS = 'TEST_HTTP_INTEGRATION_SUCCESS'

export const EMAIL_INTEGRATION_IMPORT_START = 'EMAIL_INTEGRATION_IMPORT_START'
export const EMAIL_INTEGRATION_IMPORT_ERROR = 'EMAIL_INTEGRATION_IMPORT_ERROR'
export const EMAIL_INTEGRATION_IMPORT_SUCCESS =
    'EMAIL_INTEGRATION_IMPORT_SUCCESS'

export const ACTIVATE_ONBOARDING_INTEGRATIONS_START =
    'ACTIVATE_ONBOARDING_INTEGRATIONS_START'
export const ACTIVATE_ONBOARDING_INTEGRATIONS_SUCCESS =
    'ACTIVATE_ONBOARDING_INTEGRATIONS_SUCCESS'
export const ACTIVATE_ONBOARDING_INTEGRATIONS_ERROR =
    'ACTIVATE_ONBOARDING_INTEGRATIONS_ERROR'

export const EMAIL_INTEGRATION_VERIFIED = 'EMAIL_INTEGRATION_VERIFIED'

export const EMAIL_FORWARDING_ACTIVATED = 'EMAIL_FORWARDING_ACTIVATED'

export const FETCH_ONBOARDING_INTEGRATIONS_START =
    'FETCH_ONBOARDING_INTEGRATIONS_START'
export const FETCH_ONBOARDING_INTEGRATIONS_SUCCESS =
    'FETCH_ONBOARDING_INTEGRATIONS_SUCCESS'
export const FETCH_ONBOARDING_INTEGRATIONS_ERROR =
    'FETCH_ONBOARDING_INTEGRATIONS_ERROR'

// CRUD on detail integration

export const CREATE_INTEGRATION_START = 'CREATE_INTEGRATION_START'
export const CREATE_INTEGRATION_SUCCESS = 'CREATE_INTEGRATION_SUCCESS'
export const CREATE_INTEGRATION_ERROR = 'CREATE_INTEGRATION_ERROR'

export const FETCH_INTEGRATION_START = 'FETCH_INTEGRATION_START'
export const FETCH_INTEGRATION_SUCCESS = 'FETCH_INTEGRATION_SUCCESS'
export const FETCH_INTEGRATION_ERROR = 'FETCH_INTEGRATION_ERROR'

export const UPDATE_INTEGRATION_START = 'UPDATE_INTEGRATION_START'
export const UPDATE_INTEGRATION_SUCCESS = 'UPDATE_INTEGRATION_SUCCESS'
export const UPDATE_INTEGRATION_ERROR = 'UPDATE_INTEGRATION_ERROR'

export const DELETE_INTEGRATION_START = 'DELETE_INTEGRATION_START'
export const DELETE_INTEGRATION_SUCCESS = 'DELETE_INTEGRATION_SUCCESS'
export const DELETE_INTEGRATION_ERROR = 'DELETE_INTEGRATION_ERROR'

export const CREATE_EMAIL_DOMAIN_START = 'CREATE_EMAIL_DOMAIN_START'
export const CREATE_EMAIL_DOMAIN_SUCCESS = 'CREATE_EMAIL_DOMAIN_SUCCESS'
export const CREATE_EMAIL_DOMAIN_ERROR = 'CREATE_EMAIL_DOMAIN_ERROR'

export const FETCH_EMAIL_DOMAIN_START = 'FETCH_EMAIL_DOMAIN_START'
export const FETCH_EMAIL_DOMAIN_SUCCESS = 'FETCH_EMAIL_DOMAIN_SUCCESS'
export const FETCH_EMAIL_DOMAIN_ERROR = 'FETCH_EMAIL_DOMAIN_ERROR'
