export const FETCH_INTEGRATIONS_START = 'FETCH_INTEGRATIONS_START'
export const FETCH_INTEGRATIONS_SUCCESS = 'FETCH_INTEGRATIONS_SUCCESS'
export const FETCH_INTEGRATIONS_ERROR = 'FETCH_INTEGRATIONS_ERROR'

export const TEST_HTTP_INTEGRATION_START = 'TEST_HTTP_INTEGRATION_START'
export const TEST_HTTP_INTEGRATION_SUCCESS = 'TEST_HTTP_INTEGRATION_SUCCESS'

// CRUD on detail integration

export const CREATE_INTEGRATION_START = 'CREATE_INTEGRATION_START'
export const CREATE_INTEGRATION_SUCCESS = 'CREATE_INTEGRATION_SUCCESS'
export const CREATE_INTEGRATION_ERROR = 'CREATE_INTEGRATION_ERROR'

export const FETCH_INTEGRATION_START = 'FETCH_INTEGRATION_START'
export const FETCH_INTEGRATION_SUCCESS = 'FETCH_INTEGRATION_SUCCESS'
export const FETCH_INTEGRATION_ERROR = 'FETCH_INTEGRATION_ERROR'

export const UPDATE_INTEGRATION_START = 'UPDATE_INTEGRATION_START'
export const UPDATE_INTEGRATION_SUCCESS = 'UPDATE_INTEGRATION_SUCCESS'
export const UPDATE_INTEGRATION_ERROR = 'UPDATE_INTEGRATION_ERROR'

export const DELETE_INTEGRATION_START = 'DELETE_INTEGRATION_START'
export const DELETE_INTEGRATION_SUCCESS = 'DELETE_INTEGRATION_SUCCESS'
export const DELETE_INTEGRATION_CANCEL = 'DELETE_INTEGRATION_CANCEL'
export const DELETE_INTEGRATION_ERROR = 'DELETE_INTEGRATION_ERROR'
