export const UNORDERED_LIST_ITEM = 'unordered-list-item'
export const ORDERED_LIST_ITEM = 'ordered-list-item'
export const HEADER_ONE = 'header-one'
export const HEADER_TWO = 'header-two'
export const HEADER_THREE = 'header-three'
