export enum VoiceCallTableColumn {
    Activity = 'Activity',
    TransferActivity = 'TransferActivity',
    Integration = 'Integration',
    Queue = 'Queue',
    Date = 'Date',
    State = 'State',
    Recording = 'Recording',
    Duration = 'Duration',
    WaitTime = 'WaitTime',
    Ticket = 'Ticket',
    TalkTime = 'TalkTime',
    OngoingTime = 'Time',
    LiveStatus = 'Status',
    Monitor = 'Monitor',
}

export const voiceCallTableColumnName: Record<string, string> = {
    [VoiceCallTableColumn.Activity]: 'Activity',
    [VoiceCallTableColumn.TransferActivity]: 'Activity',
    [VoiceCallTableColumn.Integration]: 'Integration',
    [VoiceCallTableColumn.Queue]: 'Queue',
    [VoiceCallTableColumn.Date]: 'Date',
    [VoiceCallTableColumn.State]: 'State',
    [VoiceCallTableColumn.Recording]: 'Recording',
    [VoiceCallTableColumn.Duration]: 'Duration',
    [VoiceCallTableColumn.WaitTime]: 'Wait time',
    [VoiceCallTableColumn.Ticket]: 'Ticket',
    [VoiceCallTableColumn.TalkTime]: 'Talk time',
    [VoiceCallTableColumn.OngoingTime]: 'Time',
    [VoiceCallTableColumn.LiveStatus]: 'Status',
    [VoiceCallTableColumn.Monitor]: 'Monitor',
}

export const skeletonColumnsWidth: Record<string, number> = {
    [VoiceCallTableColumn.Activity]: 364,
    [VoiceCallTableColumn.TransferActivity]: 269,
    [VoiceCallTableColumn.Integration]: 174,
    [VoiceCallTableColumn.Queue]: 174,
    [VoiceCallTableColumn.Date]: 154,
    [VoiceCallTableColumn.OngoingTime]: 120,
    [VoiceCallTableColumn.State]: 74,
    [VoiceCallTableColumn.LiveStatus]: 74,
    [VoiceCallTableColumn.Recording]: 84,
    [VoiceCallTableColumn.Duration]: 74,
    [VoiceCallTableColumn.TalkTime]: 84,
    [VoiceCallTableColumn.WaitTime]: 84,
    [VoiceCallTableColumn.Ticket]: 82,
    [VoiceCallTableColumn.Monitor]: 120,
}
