export const CREATE_AGENT_ERROR = 'CREATE_AGENT_ERROR'
export const CREATE_AGENT_SUCCESS = 'CREATE_AGENT_SUCCESS'

export const UPDATE_AGENT_ERROR = 'UPDATE_AGENT_ERROR'
export const UPDATE_AGENT_SUCCESS = 'UPDATE_AGENT_SUCCESS'

export const DELETE_AGENT_ERROR = 'DELETE_AGENT_ERROR'
export const DELETE_AGENT_SUCCESS = 'DELETE_AGENT_SUCCESS'

export const INVITE_AGENT_ERROR = 'INVITE_AGENT_ERROR'

export const FETCH_AGENT_ERROR = 'FETCH_AGENT_ERROR'

export const FETCH_AGENTS_PAGINATION_ERROR = 'FETCH_AGENTS_PAGINATION_ERROR'
export const FETCH_AGENTS_PAGINATION_SUCCESS = 'FETCH_AGENTS_PAGINATION_SUCCESS'

export const FETCH_USER_LIST_START = 'FETCH_USER_LIST_START'
export const FETCH_USER_LIST_SUCCESS = 'FETCH_USER_LIST_SUCCESS'
export const FETCH_USER_LIST_ERROR = 'FETCH_USER_LIST_ERROR'

export const SET_AGENTS_LOCATIONS = 'SET_AGENTS_LOCATIONS'
export const SET_AGENTS_TYPING_STATUSES = 'SET_AGENTS_TYPING_STATUSES'
