export const SET_FACEBOOK_ADS_LOADING = 'SET_FACEBOOK_ADS_LOADING'
export const SET_FACEBOOK_ADS_INTERNALS = 'SET_FACEBOOK_ADS_INTERNALS'

export const ADD_LOADING_FACEBOOK_AD_ACCOUNT = 'ADD_LOADING_FACEBOOK_AD_ACCOUNT'
export const ADD_LOADING_FACEBOOK_AD = 'ADD_LOADING_FACEBOOK_AD'

export const REMOVE_LOADING_FACEBOOK_AD_ACCOUNT = 'REMOVE_LOADING_FACEBOOK_AD_ACCOUNT'
export const REMOVE_LOADING_FACEBOOK_AD = 'REMOVE_LOADING_FACEBOOK_AD'

export const UPDATE_ACTIVE_FACEBOOK_AD_ACCOUNT = 'UPDATE_ACTIVE_FACEBOOK_AD_ACCOUNT'
export const UPDATE_ACTIVE_FACEBOOK_AD = 'UPDATE_ACTIVE_FACEBOOK_AD'
