export const FETCH_CUSTOMER_START = 'FETCH_CUSTOMER_START'
export const FETCH_CUSTOMER_SUCCESS = 'FETCH_CUSTOMER_SUCCESS'
export const FETCH_CUSTOMER_ERROR = 'FETCH_CUSTOMER_ERROR'

export const SUBMIT_CUSTOMER_START = 'SUBMIT_CUSTOMER_START'
export const SUBMIT_CUSTOMER_SUCCESS = 'SUBMIT_CUSTOMER_SUCCESS'
export const SUBMIT_CUSTOMER_ERROR = ' SUBMIT_CUSTOMER_ERROR'

export const DELETE_CUSTOMER_START = 'DELETE_CUSTOMER_START'
export const DELETE_CUSTOMER_SUCCESS = 'DELETE_CUSTOMER_SUCCESS'
export const DELETE_CUSTOMER_ERROR = 'DELETE_CUSTOMER_ERROR'

// Actions related to customer history (timeline)
export const FETCH_CUSTOMER_HISTORY_START = 'FETCH_CUSTOMER_HISTORY_START'
export const FETCH_CUSTOMER_HISTORY_SUCCESS = 'FETCH_CUSTOMER_HISTORY_SUCCESS'
export const FETCH_CUSTOMER_HISTORY_ERROR = 'FETCH_CUSTOMER_HISTORY_ERROR'

export const MERGE_CUSTOMERS_START = 'MERGE_CUSTOMERS_START'
export const MERGE_CUSTOMERS_SUCCESS = 'MERGE_CUSTOMERS_SUCCESS'
export const MERGE_CUSTOMERS_ERROR = 'MERGE_CUSTOMERS_ERROR'

export const BULK_DELETE_START = 'BULK_DELETE_START'
export const BULK_DELETE_SUCCESS = 'BULK_DELETE_SUCCESS'
export const BULK_DELETE_ERROR = 'BULK_DELETE_ERROR'
