export const CHAT_AUTO_RESPONDER_REPLY_SHORTLY = 'reply-shortly'
export const CHAT_AUTO_RESPONDER_REPLY_DEFAULT = CHAT_AUTO_RESPONDER_REPLY_SHORTLY
export const CHAT_AUTO_RESPONDER_ENABLED_DEFAULT = false
