import {
    EcommerceStore,
    Shopper,
    ShopperAddress,
    ShopperOrder,
} from 'models/customerEcommerceData/types'

export const ecommerceStoreFixture: EcommerceStore = {
    deleted_datetime: null,
    display_name: 'My Store',
    helpdesk_integration_id: 207,
    name: 'my-store',
    default_currency: 'eur',
    currencies: ['eur', 'usd'],
    url: 'https://mystore.com',
    created_datetime: '2023-08-02T14:17:57.549232+00:00',
    type: 'woocommerce',
    id: 2,
    uuid: 'f599447d-2de1-47ea-ab04-7649a421ba7d',
    updated_datetime: null,
}
export const shopperFixture: Shopper = {
    deleted_datetime: null,
    accepts_marketing_sms: false,
    birthdate: null,
    accepts_marketing_email: false,
    external_id: 'c101',
    email_address: 'swim@gorgias.com',
    created_datetime: '2023-08-17T15:11:39+00:00',
    status: null,
    last_name: 'Mer',
    middle_name: null,
    helpdesk_customer_id: 311,
    first_name: 'Swim',
    phone_number: null,
    id: 2,
    updated_datetime: null,
}

export const shopperAddressFixture: ShopperAddress = {
    preferred: false,
    deleted_datetime: null,
    line_1: '123 Avenue',
    line_2: null,
    zip_code: '123456',
    city: 'Bucharest',
    external_id: 'abc',
    state: null,
    created_datetime: '2023-08-17T15:12:33+00:00',
    last_name: 'Mer',
    country: 'Romania',
    first_name: 'Swim',
    phone_number: null,
    id: 6,
    updated_datetime: null,
}

export const shopperOrderFixture: ShopperOrder = {
    canceled_datetime: null,
    external_fulfillment_status: null,
    external_payment_status: null,
    external_status: null,
    payment_status: null,
    processed_datetime: null,
    shopper_external_id: shopperFixture.external_id,
    status: null,
    deleted_datetime: null,
    shipping_address: {
        preferred: false,
        deleted_datetime: null,
        line_1: '123 Avenue',
        line_2: null,
        zip_code: '123456',
        city: 'Bucharest',
        external_id: 'abc',
        state: null,
        created_datetime: '2023-08-17T15:12:33+00:00',
        last_name: 'Mer',
        country: 'Romania',
        first_name: 'Swim',
        phone_number: null,
        id: 6,
        updated_datetime: null,
    },
    discount_codes: null,
    shipping_amount: 0,
    number: 878,
    name: 'Order #878',
    tax_amount: 0,
    external_id: 's101',
    billing_address: {
        preferred: false,
        deleted_datetime: null,
        line_1: '123 Avenue',
        line_2: null,
        zip_code: '123456',
        city: 'Bucharest',
        external_id: 'abc',
        state: null,
        created_datetime: '2023-08-17T15:12:33+00:00',
        last_name: 'Mer',
        country: 'Romania',
        first_name: 'Swim',
        phone_number: null,
        id: 6,
        updated_datetime: null,
    },
    currency: 'usd',
    created_datetime: '2023-08-17T15:16:48+00:00',
    total_amount: 900,
    subtotal_amount: 900,
    line_items: [
        {
            deleted_datetime: null,
            discount_reason: null,
            taxable: null,
            quantity: 1,
            fulfilled_quantity: null,
            unit_price: 900,
            product_options: null,
            product: {
                barcode: null,
                deleted_datetime: null,
                taxable: false,
                price: 86,
                name: 'Awesome product',
                external_id: '101',
                currency: 'usd',
                created_datetime: '2021-01-07T13:00:00+00:00',
                stock: 900,
                images: [],
                tags: [],
                id: 3,
                description: 'Foo bar',
                sku: 'SKU-101',
                updated_datetime: '2023-08-17T10:45:08+00:00',
                requires_shipping: true,
            },
            created_datetime: '2023-08-17T15:18:58+00:00',
            total_amount: 900,
            discount_amount: null,
            title: 'my awesome item',
            discount_type: null,
            id: 4,
            updated_datetime: null,
            requires_shipping: null,
        },
        {
            deleted_datetime: null,
            discount_reason: null,
            taxable: null,
            quantity: 1,
            fulfilled_quantity: null,
            unit_price: 901,
            product_options: null,
            product: {
                barcode: null,
                deleted_datetime: null,
                taxable: false,
                price: 86,
                name: 'Awesome product',
                external_id: '101',
                currency: 'usd',
                created_datetime: '2021-01-07T13:00:00+00:00',
                stock: 900,
                images: [],
                tags: [],
                id: 3,
                description: 'Foo bar',
                sku: 'SKU-101',
                updated_datetime: '2023-08-17T10:45:08+00:00',
                requires_shipping: true,
            },
            created_datetime: '2023-08-17T15:18:58+00:00',
            total_amount: 901,
            discount_amount: null,
            title: 'my awesome item 2',
            discount_type: null,
            id: 5,
            updated_datetime: null,
            requires_shipping: null,
        },
    ],
    discount_amount: null,
    id: 5,
    updated_datetime: null,
}
