export const AIRCALL_INTEGRATION_TYPE = 'aircall'
export const SMOOCH_INTEGRATION_TYPE = 'smooch'
export const SMOOCH_INSIDE_INTEGRATION_TYPE = 'smooch_inside'
export const FACEBOOK_INTEGRATION_TYPE = 'facebook'
export const EMAIL_INTEGRATION_TYPE = 'email'
export const GMAIL_INTEGRATION_TYPE = 'gmail'
export const OUTLOOK_INTEGRATION_TYPE = 'outlook'

export const HTTP_INTEGRATION_TYPE = 'http'
export const SHOPIFY_INTEGRATION_TYPE = 'shopify'
export const RECHARGE_INTEGRATION_TYPE = 'recharge'
export const SMILE_INTEGRATION_TYPE = 'smile'

export const ZENDESK_INTEGRATION_TYPE = 'zendesk'

export const EMAIL_INTEGRATION_TYPES = Object.freeze([
    EMAIL_INTEGRATION_TYPE, GMAIL_INTEGRATION_TYPE, OUTLOOK_INTEGRATION_TYPE
])

export const MESSAGING_INTEGRATION_TYPES = Object.freeze([
    ...EMAIL_INTEGRATION_TYPES,
    AIRCALL_INTEGRATION_TYPE, SMOOCH_INSIDE_INTEGRATION_TYPE, SMOOCH_INTEGRATION_TYPE, FACEBOOK_INTEGRATION_TYPE
])

export const INTEGRATION_TYPES = Object.freeze([
    ...MESSAGING_INTEGRATION_TYPES,

    HTTP_INTEGRATION_TYPE, SHOPIFY_INTEGRATION_TYPE,
    RECHARGE_INTEGRATION_TYPE, SMILE_INTEGRATION_TYPE,

    ZENDESK_INTEGRATION_TYPE
])

export const EMAIL_INTEGRATION_NAME_FORBIDDEN_CHARS = Object.freeze(['@', ',', ';', '<', '>'])


export const PENDING_AUTHENTICATION_STATUS = 'pending'
export const SUCCESS_AUTHENTICATION_STATUS = 'success'
export const ERROR_AUTHENTICATION_STATUS = 'error'
export const AUTHENTICATION_STATUS = [
    PENDING_AUTHENTICATION_STATUS,
    SUCCESS_AUTHENTICATION_STATUS,
    ERROR_AUTHENTICATION_STATUS
]

