export const FETCH_INTEGRATION_START = 'FETCH_INTEGRATION_START'
export const FETCH_INTEGRATION_SUCCESS = 'FETCH_INTEGRATION_SUCCESS'
export const FETCH_INTEGRATION_ERROR = 'FETCH_INTEGRATION_ERROR'

export const DELETE_INTEGRATION_SUCCESS = 'DELETE_INTEGRATION_SUCCESS'
export const DELETE_INTEGRATION_ERROR = 'DELETE_INTEGRATION_ERROR'

export const FETCH_INTEGRATIONS_START = 'FETCH_INTEGRATIONS_START'
export const FETCH_INTEGRATIONS_SUCCESS = 'FETCH_INTEGRATIONS_SUCCESS'
export const FETCH_INTEGRATIONS_ERROR = 'FETCH_INTEGRATIONS_ERROR'

export const FACEBOOK_LOGIN = 'FACEBOOK_LOGIN'
export const FACEBOOK_LOGIN_SUCCESS = 'FACEBOOK_LOGIN_SUCCESS'
export const FACEBOOK_LOGIN_ERROR = 'FACEBOOK_LOGIN_ERROR'

export const TOGGLE_PRIVATE_MESSAGES_ENABLED = 'TOGGLE_PRIVATE_MESSAGES_ENABLED'
export const TOGGLE_POSTS_ENABLED = 'TOGGLE_POSTS_ENABLED'
export const TOGGLE_IMPORT_HISTORY_ENABLED = 'TOGGLE_IMPORT_HISTORY_ENABLED'

export const UPDATE_INTEGRATION_START = 'UPDATE_INTEGRATION_START'
export const UPDATE_INTEGRATION_SUCCESS = 'UPDATE_INTEGRATION_SUCCESS'
export const UPDATE_INTEGRATION_ERROR = 'UPDATE_INTEGRATION_ERROR'

export const SELECT_FACEBOOK_PAGE = 'SELECT_FACEBOOK_PAGE'
