export const ENGLISH_US_LANGUAGE = 'en-US'
export const FRENCH_LANGUAGE = 'fr'
export const SPANISH_LANGUAGE = 'es'
export const DANISH_LANGUAGE = 'da'
export const SWEDISH_LANGUAGE = 'sv'
export const DUTCH_LANGUAGE = 'nl'
export const ITALIAN_LANGUAGE = 'it'
export const GERMAN_LANGUAGE = 'de'
