// Fetching a list of tickets life-cycle
export const FETCH_TICKET_LIST_VIEW_START = 'FETCH_TICKET_LIST_VIEW_START'
export const FETCH_TICKET_LIST_VIEW_SUCCESS = 'FETCH_TICKET_LIST_VIEW_SUCCESS'
export const FETCH_TICKET_LIST_VIEW_ERROR = 'FETCH_TICKET_LIST_VIEW_ERROR'

export const TOGGLE_TICKET_SELECTION = 'TOGGLE_TICKET_SELECTION'

export const BULK_UPDATE_START = 'BULK_UPDATE_START'
export const BULK_UPDATE_SUCCESS = 'BULK_UPDATE_SUCCESS'
export const BULK_UPDATE_ERROR = 'BULK_UPDATE_ERROR'

export const BULK_DELETE_START = 'BULK_DELETE_START'
export const BULK_DELETE_SUCCESS = 'BULK_DELETE_SUCCESS'
export const BULK_DELETE_ERROR = 'BULK_DELETE_ERROR'

export const BULK_APPLY_MACRO = 'BULK_APPLY_MACRO'

export const SAVE_INDEX = 'SAVE_INDEX'
