export const EMAIL_CUSTOMER_CHANNEL_TYPE = 'email'
export const TWITTER_CUSTOMER_CHANNEL_TYPE = 'twitter'
export const PHONE_CUSTOMER_CHANNEL_TYPE = 'phone'
export const CHAT_CUSTOMER_CHANNEL_TYPE = 'chat'
export const FACEBOOK_CUSTOMER_CHANNEL_TYPE = 'facebook'
export const INSTAGRAM_CUSTOMER_CHANNEL_TYPE = 'instagram'
