export const HELPCENTER_ARTICLE_CREATED = 'HELPCENTER/ARTICLE_CREATED'
export const HELPCENTER_ARTICLE_DELETED = 'HELPCENTER/ARTICLE_DELETED'
export const HELPCENTER_ARTICLE_UPDATED = 'HELPCENTER/ARTICLE_UPDATED'
export const HELPCENTER_ARTICLE_FETCHED = 'HELPCENTER/ARTICLE_FETCHED'

export const HELPCENTER_ARTICLES_FETCHED = 'HELPCENTER/ARTICLES_FETCHED'
