// Basic operations on the views
export const UPDATE_VIEW = 'UPDATE_VIEW'
export const RESET_VIEW = 'RESET_VIEW'
export const ADD_VIEW_FIELD_FILTER = 'ADD_VIEW_FIELD_FILTER'
export const UPDATE_VIEW_FIELD_FILTER = 'UPDATE_VIEW_FIELD_FILTER'
export const REMOVE_VIEW_FIELD_FILTER = 'REMOVE_VIEW_FIELD_FILTER'
export const UPDATE_VIEW_FIELD_FILTER_OPERATOR = 'UPDATE_VIEW_FIELD_FILTER_OPERATOR'

export const SET_FIELD_VISIBILITY = 'SET_FIELD_VISIBILITY'
export const SET_ORDER_DIRECTION = 'SET_ORDER_DIRECTION'

export const UPDATE_VIEW_FIELD_ENUM_START = 'UPDATE_VIEW_FIELD_ENUM_START'
export const UPDATE_VIEW_FIELD_ENUM_SUCCESS = 'UPDATE_VIEW_FIELD_ENUM_SUCCESS'
export const UPDATE_VIEW_FIELD_ENUM_ERROR = 'UPDATE_VIEW_FIELD_ENUM_ERROR'

// Update individual view definitions
export const SUBMIT_VIEW_START = 'SUBMIT_VIEW_START'
export const SUBMIT_NEW_VIEW_SUCCESS = 'SUBMIT_NEW_VIEW_SUCCESS'
export const SUBMIT_NEW_VIEW_ERROR = 'SUBMIT_NEW_VIEW_ERROR'

export const SUBMIT_UPDATE_VIEW_SUCCESS = 'SUBMIT_UPDATE_VIEW_SUCCESS'
export const SUBMIT_UPDATE_VIEW_ERROR = 'SUBMIT_UPDATE_VIEW_ERROR'

// Fetch list views
export const FETCH_VIEW_LIST_START = 'FETCH_VIEW_LIST_START'
export const FETCH_VIEW_LIST_SUCCESS = 'FETCH_VIEW_LIST_SUCCESS'
export const FETCH_VIEW_LIST_ERROR = 'FETCH_VIEW_LIST_ERROR'

export const UPDATE_VIEW_LIST = 'UPDATE_VIEW_LIST'

// Read views
export const SET_VIEW_ACTIVE = 'SET_VIEW_ACTIVE'

export const DELETE_VIEW_SUCCESS = 'DELETE_VIEW_SUCCESS'


export const FETCH_LIST_VIEW_START = 'FETCH_LIST_VIEW_START'
export const FETCH_LIST_VIEW_SUCCESS = 'FETCH_LIST_VIEW_SUCCESS'
export const FETCH_LIST_VIEW_ERROR = 'FETCH_LIST_VIEW_ERROR'

export const SET_PAGE = 'SET_PAGE'


export const TOGGLE_SELECTION = 'TOGGLE_TICKET_SELECTION'

export const BULK_UPDATE_START = 'BULK_UPDATE_START'
export const BULK_UPDATE_SUCCESS = 'BULK_UPDATE_SUCCESS'
export const BULK_UPDATE_ERROR = 'BULK_UPDATE_ERROR'

export const BULK_DELETE_START = 'BULK_DELETE_START'
export const BULK_DELETE_SUCCESS = 'BULK_DELETE_SUCCESS'
export const BULK_DELETE_ERROR = 'BULK_DELETE_ERROR'

export const BULK_APPLY_MACRO = 'BULK_APPLY_MACRO'
