import React, { Fragment, ReactNode, useState } from 'react'

import classNames from 'classnames'
import { FormGroup, UncontrolledTooltip } from 'reactstrap'

import { LegacyButton as Button } from '@gorgias/axiom'

import {
    ColumnSourceCsvOrAutoGenerated,
    CsvColumnPreview,
    HelpCenter,
    Locale,
    LocaleCode,
} from 'models/helpCenter/types'
import { ConfirmModalAction } from 'pages/common/components/ConfirmModalAction'
import { FlagLanguageItem } from 'pages/common/components/LanguageBulletList'
import HeaderCellProperty from 'pages/common/components/table/cells/HeaderCellProperty'
import TableBody from 'pages/common/components/table/TableBody'
import TableBodyRow from 'pages/common/components/table/TableBodyRow'
import TableHead from 'pages/common/components/table/TableHead'
import TableWrapper from 'pages/common/components/table/TableWrapper'
import settingsCss from 'pages/settings/settings.less'

import { ImportedLanguagesTags } from '../ImportedLanguagesTags'
import { FieldRow } from './components/FieldRow'
import {
    CsvColumnsByName,
    GorgiasFields,
    GorgiasFieldsMappingsLocalized,
} from './types'
import {
    initialMappings,
    mappingsComplete,
    previewField,
    updateGorgiasFieldsMappingsLocalized,
} from './utils'

import css from './CsvColumnMatching.less'

const localeFieldRows: {
    field: GorgiasFields
    isAutoGeneratable: boolean
    isRequired: boolean
    fieldName: string | ReactNode
}[] = [
    {
        field: 'ArticleTitle',
        isRequired: true,
        isAutoGeneratable: false,
        fieldName: 'Article Title',
    },
    {
        field: 'ArticleContent',
        isRequired: true,
        isAutoGeneratable: false,
        fieldName: 'Article Content',
    },
    {
        field: 'ArticleSlug',
        isRequired: true,
        isAutoGeneratable: true,
        fieldName: (
            <span>
                <span className={css['tooltip-target']} id="articleSlugTooltip">
                    Article Slug
                </span>
                <UncontrolledTooltip
                    target="articleSlugTooltip"
                    fade={false}
                    innerClassName={css['csv-tooltip-inner']}
                >
                    <div>
                        <p>
                            This is a text part of the URL of your article that
                            will be visible in the address bar.
                        </p>

                        <p>
                            We can autogenarate it for you based on the article
                            title or you can select the right column in your CSV
                            file if you already have it.
                        </p>
                    </div>
                </UncontrolledTooltip>
            </span>
        ),
    },
    {
        field: 'ArticleExcerpt',
        isRequired: false,
        isAutoGeneratable: true,
        fieldName: (
            <span>
                <span
                    className={css['tooltip-target']}
                    id="articleExcerptTooltip"
                >
                    Article Excerpt
                </span>
                <UncontrolledTooltip
                    innerClassName={css['csv-tooltip-inner']}
                    fade={false}
                    target="articleExcerptTooltip"
                >
                    <p>
                        This is a short version of your article to help people
                        find it more easily when searching.
                    </p>
                </UncontrolledTooltip>
            </span>
        ),
    },
    {
        field: 'ArticleID',
        isRequired: false,
        isAutoGeneratable: false,
        fieldName: (
            <span>
                <span className={css['tooltip-target']} id="articleIDTooltip">
                    Article ID
                </span>
                <UncontrolledTooltip
                    innerClassName={css['csv-tooltip-inner']}
                    fade={false}
                    target="articleIDTooltip"
                >
                    <p>
                        You can easily update existing articles by importing a
                        new article with the same Article ID. If you don’t want
                        to replace any existing articles, leave the Article ID
                        empty.
                    </p>
                </UncontrolledTooltip>
            </span>
        ),
    },
    {
        field: 'CategoryName',
        isRequired: false,
        isAutoGeneratable: false,
        fieldName: 'Category Name',
    },
    {
        field: 'CategoryDescription',
        isRequired: false,
        isAutoGeneratable: false,
        fieldName: 'Category Description',
    },
    {
        field: 'CategorySlug',
        isRequired: false,
        isAutoGeneratable: true,
        fieldName: 'Category Slug',
    },
    {
        field: 'CategoryID',
        isRequired: false,
        isAutoGeneratable: false,
        fieldName: (
            <span>
                <span className={css['tooltip-target']} id="categoryIDTooltip">
                    Category ID
                </span>
                <UncontrolledTooltip
                    innerClassName={css['csv-tooltip-inner']}
                    fade={false}
                    target="categoryIDTooltip"
                >
                    <p>
                        You can easily update existing categories by importing a
                        new category with the same Category ID. If you don’t
                        want to replace any existing categories, leave the
                        Category ID empty.
                    </p>
                </UncontrolledTooltip>
            </span>
        ),
    },
]

export interface Props {
    csvColumns: CsvColumnPreview[]
    helpCenter: HelpCenter
    locales: Locale[]
    onImport: (mappings: GorgiasFieldsMappingsLocalized) => void
    onCancel: () => void
}

export const CsvColumnMatching = ({
    csvColumns,
    helpCenter,
    locales,
    onImport,
    onCancel,
}: Props): JSX.Element | null => {
    const csvColumnsByName: CsvColumnsByName = React.useMemo(() => {
        const columnsByName: CsvColumnsByName = new Map()
        csvColumns.forEach((column) => {
            columnsByName.set(column.name, column)
        })

        return columnsByName
    }, [csvColumns])

    const [fieldsMappings, setFieldsMappings] =
        useState<GorgiasFieldsMappingsLocalized>(
            initialMappings(
                helpCenter.default_locale,
                Array.from(csvColumnsByName.keys()),
            ),
        )

    const selectedLocalesToImport: LocaleCode[] = React.useMemo(
        () => fieldsMappings.map(({ localeCode }) => localeCode),
        [fieldsMappings],
    )

    const handleSelectedLocalesChange = (newSelectedLocales: LocaleCode[]) => {
        setFieldsMappings(
            newSelectedLocales.sort().map((newSelectedLocale) => {
                const existingMapping = fieldsMappings.find(
                    ({ localeCode }) => localeCode === newSelectedLocale,
                )

                return (
                    existingMapping || {
                        localeCode: newSelectedLocale,
                        mappings: {},
                    }
                )
            }),
        )
    }

    const makeOnChangeMapping =
        (field: GorgiasFields, localeCode: LocaleCode) =>
        (mapping?: ColumnSourceCsvOrAutoGenerated) => {
            if (mapping === undefined) {
                return setFieldsMappings(
                    updateGorgiasFieldsMappingsLocalized(
                        fieldsMappings,
                        localeCode,
                        {
                            [field]: undefined,
                        },
                    ),
                )
            }

            setFieldsMappings(
                updateGorgiasFieldsMappingsLocalized(
                    fieldsMappings,
                    localeCode,
                    {
                        [field]: {
                            source: mapping.source,
                        },
                    },
                ),
            )
        }

    return (
        <div className={settingsCss.pageContainer}>
            <h3>Column matching</h3>

            <p>Match the fields below with the ones in your CSV</p>

            <h4>Language import</h4>

            <p>
                Choose the languages you want to import. If you don’t see all
                languages you wish to import from here, you might need to add
                them in preferences before and re-upload the file.
            </p>

            <ImportedLanguagesTags
                availableLocales={locales}
                selectedLocales={selectedLocalesToImport}
                onSelectedLocalesChange={handleSelectedLocalesChange}
            />

            <TableWrapper className={css['table']}>
                <TableHead>
                    <HeaderCellProperty
                        className={classNames(css['th-auto'])}
                        title="Matched"
                    />
                    <HeaderCellProperty
                        className={css['th-max-20']}
                        title="Gorgias field name"
                    />
                    <HeaderCellProperty
                        className={css['th-max-20']}
                        title="Column header from file"
                    />
                    <HeaderCellProperty title="Preview information" />
                </TableHead>
                <TableBody>
                    {fieldsMappings.map(({ localeCode, mappings }) => (
                        <Fragment key={localeCode}>
                            <TableBodyRow>
                                <th
                                    className={
                                        css['table-language-header-cell']
                                    }
                                    colSpan={4}
                                >
                                    <FlagLanguageItem
                                        code={localeCode}
                                        name={
                                            locales.find(
                                                ({ code }) =>
                                                    code === localeCode,
                                            )?.name || ''
                                        }
                                    />
                                </th>
                            </TableBodyRow>

                            {localeFieldRows.map(
                                ({
                                    field,
                                    fieldName,
                                    isAutoGeneratable,
                                    isRequired,
                                }) => (
                                    <FieldRow
                                        key={field}
                                        fieldName={fieldName}
                                        currentMapping={mappings[field]}
                                        csvColumnsByName={csvColumnsByName}
                                        onChangeMapping={makeOnChangeMapping(
                                            field,
                                            localeCode,
                                        )}
                                        isRequired={isRequired}
                                        isAutoGeneratable={isAutoGeneratable}
                                        preview={previewField(
                                            field,
                                            csvColumnsByName,
                                            mappings,
                                        )}
                                    />
                                ),
                            )}
                        </Fragment>
                    ))}
                </TableBody>
            </TableWrapper>

            <FormGroup className="mt-5">
                <Button
                    className="mr-2"
                    isDisabled={!mappingsComplete(fieldsMappings)}
                    onClick={() => onImport(fieldsMappings)}
                >
                    Confirm Import
                </Button>
                <ConfirmModalAction
                    actions={(onClose) => (
                        <>
                            <Button
                                className={css['cancel-button']}
                                intent="secondary"
                                onClick={() => onClose()}
                            >
                                Cancel
                            </Button>
                            <Button intent="destructive" onClick={onCancel}>
                                Stop Import
                            </Button>
                        </>
                    )}
                    content={
                        <p>
                            You will need to re-upload the file if you decide to
                            import again.
                        </p>
                    }
                    title="Are you sure you want to stop importing?"
                >
                    {(onClick) => (
                        <Button intent="secondary" onClick={onClick}>
                            Cancel
                        </Button>
                    )}
                </ConfirmModalAction>
            </FormGroup>
        </div>
    )
}

export default CsvColumnMatching
