//@flow
export const MACRO_CREATED: 'MACROS/MACRO_CREATED' = 'MACROS/MACRO_CREATED'
export const MACRO_DELETED: 'MACROS/MACRO_DELETED' = 'MACROS/MACRO_DELETED'
export const MACRO_FETCHED: 'MACROS/MACRO_FETCHED' = 'MACROS/MACRO_FETCHED'
export const MACRO_UPDATED: 'MACROS/MACRO_UPDATED' = 'MACROS/MACRO_UPDATED'
export const MACROS_FETCHED: 'MACROS/MACROS_FETCHED' = 'MACROS/MACROS_FETCHED'
