import React, {ReactNode} from 'react'
import classNames from 'classnames'

import TableBodyRow from '../../../../../../../../common/components/table/TableBodyRow'

import BodyCell from '../../../../../../../../common/components/table/cells/BodyCell'

import {ColumnSourceCsvOrAutoGenerated} from '../../../../../../../../../models/helpCenter/types'

import {CsvColumnsByName} from '../../types'

import FieldMappingSelectorDropdown from '../FieldMappingSelectorDropdown'
import {Option} from '../FieldMappingSelectorDropdown/types'

import {
    optionForAutoGenerated,
    optionForCsvColumn,
    optionForSource,
    sourceFromOptionKey,
    truncatePreview,
} from './utils'

import css from './FieldRow.less'

const OPTION_NO_SELECTION: Option = {
    key: 'NO_SELECTION',
    label: '- No selection -',
}

export interface Props {
    currentMapping?: ColumnSourceCsvOrAutoGenerated
    csvColumnsByName: CsvColumnsByName
    isAutoGeneratable?: boolean
    isRequired?: boolean
    fieldName: string | ReactNode
    preview: string[]
    onChangeMapping: (newMapping?: ColumnSourceCsvOrAutoGenerated) => void
}

export const FieldRow = ({
    isAutoGeneratable,
    fieldName,
    csvColumnsByName,
    currentMapping,
    onChangeMapping,
    preview,
    isRequired,
}: Props): JSX.Element | null => {
    const csvColumnsNames: string[] = React.useMemo(
        () => Array.from(csvColumnsByName.keys()),
        [csvColumnsByName]
    )

    const options = React.useMemo(() => {
        let csvOptions = csvColumnsNames.map(optionForCsvColumn)

        if (isRequired !== true && currentMapping !== undefined) {
            csvOptions = [OPTION_NO_SELECTION, ...csvOptions]
        }

        if (isAutoGeneratable === true) {
            csvOptions = [optionForAutoGenerated(), ...csvOptions]
        }

        return csvOptions
    }, [csvColumnsNames, currentMapping, isAutoGeneratable, isRequired])

    const selectedOption: Option | undefined = React.useMemo(() => {
        if (currentMapping === undefined) {
            return undefined
        }

        return optionForSource(currentMapping)
    }, [currentMapping])

    if (options.length === 0) {
        return null
    }

    return (
        <TableBodyRow>
            <BodyCell innerClassName={css['cell']}>
                <i
                    className={classNames(
                        'material-icons',
                        currentMapping === undefined
                            ? css['not-matched-mark']
                            : css['matched-mark']
                    )}
                >
                    check_circle
                </i>
            </BodyCell>
            <BodyCell innerClassName={css['cell']}>
                <div className={isRequired ? css['is-required'] : undefined}>
                    {fieldName}
                </div>
            </BodyCell>
            <BodyCell innerClassName={css['cell']}>
                <FieldMappingSelectorDropdown
                    className={css['selector']}
                    options={options}
                    onClick={(key) => {
                        if (key === OPTION_NO_SELECTION.key) {
                            onChangeMapping(undefined)
                        } else {
                            const changedMapping = sourceFromOptionKey(key)

                            onChangeMapping(changedMapping)
                        }
                    }}
                    selectedOption={selectedOption}
                />
            </BodyCell>
            <BodyCell innerClassName={css['cell']}>
                <ul>
                    {preview.map((preview, index) => (
                        <li key={index}>{truncatePreview(preview)}</li>
                    ))}
                </ul>
            </BodyCell>
        </TableBodyRow>
    )
}

export default FieldRow
