import React from 'react'

import {
    ColumnSourceAutoGenerated,
    ColumnSourceCsv,
    ColumnSourceCsvOrAutoGenerated,
    isColumnSourceCsv,
} from '../../../../../../../../../models/helpCenter/types'

import {Option} from '../FieldMappingSelectorDropdown/types'

export const optionForSource = ({
    source,
}: ColumnSourceCsvOrAutoGenerated): Option => ({
    key: JSON.stringify(source),
    label: isColumnSourceCsv(source) ? (
        source.csv_column
    ) : (
        <span>
            <i className="material-icons mr-2">auto_awesome</i> Auto generate
        </span>
    ),
})

export const optionForCsvColumn = (csvColumn: string): Option =>
    optionForSource({
        source: {
            kind: 'CSV_COLUMN',
            csv_column: csvColumn,
        },
    })

export const optionForAutoGenerated = (): Option =>
    optionForSource({
        source: {
            kind: 'AUTO_GENERATED',
        },
    })

export const sourceFromOptionKey = (
    key: string
): ColumnSourceCsvOrAutoGenerated => ({
    // the type assertion, though ugly, is safe as long as optionFor* functions were used to generate the options
    source: JSON.parse(key) as ColumnSourceAutoGenerated | ColumnSourceCsv,
})

const FIELD_PREVIEW_MAX_LENGTH = 50

export const truncatePreview = (preview: string): string =>
    preview.length < FIELD_PREVIEW_MAX_LENGTH
        ? preview
        : `${preview.slice(0, FIELD_PREVIEW_MAX_LENGTH)}...`
