import { TrialType } from 'pages/aiAgent/components/ShoppingAssistant/types/ShoppingAssistant'

export const createMockTrialAccess = (overrides = {}) => ({
    canNotifyAdmin: false,
    canBookDemo: false,
    canSeeSystemBanner: false,
    canSeeTrialCTA: false,
    canSeeSubscribeNowCTA: false,
    hasCurrentStoreTrialStarted: false,
    hasAnyTrialStarted: false,
    hasCurrentStoreTrialOptedOut: false,
    hasAnyTrialOptedOut: false,
    hasCurrentStoreTrialExpired: false,
    hasAnyTrialExpired: false,
    hasAnyTrialOptedIn: false,
    hasCurrentStoreTrialActive: false,
    hasAnyTrialActive: false,
    isAdminUser: false,
    isLoading: false,
    trialType: TrialType.ShoppingAssistant,
    currentAutomatePlan: undefined,
    isError: false,
    isInAiAgentTrial: false,
    isOnboarded: false,
    isTrialingSubscription: false,
    trials: undefined,
    ...overrides,
})
