export const CHANGE_PASSWORD_START = 'CHANGE_PASSWORD_START'
export const CHANGE_PASSWORD_SUCCESS = 'CHANGE_PASSWORD_SUCCESS'
export const CHANGE_PASSWORD_ERROR = 'CHANGE_PASSWORD_ERROR'

export const SUBMIT_CURRENT_USER_START = 'SUBMIT_CURRENT_USER_START'
export const SUBMIT_CURRENT_USER_SUCCESS = 'SUBMIT_CURRENT_USER_SUCCESS'
export const SUBMIT_CURRENT_USER_ERROR = 'SUBMIT_CURRENT_USER_ERROR'

export const SUBMIT_SETTING_START = 'SUBMIT_SETTING_START'
export const SUBMIT_SETTING_SUCCESS = 'SUBMIT_SETTING_SUCCESS'
export const SUBMIT_SETTING_ERROR = 'SUBMIT_SETTING_ERROR'

export const TOGGLE_ACTIVE_STATUS = 'TOGGLE_ACTIVE_STATUS'

export const UPDATE_2FA_STATUS = 'UPDATE_2FA_STATUS'

export const TWO_FA_REQUIRED_NOTIFICATION_ID = 'two-fa-setup-required-banner'
export const OPEN_TWO_FA_MODAL_URL =
    '/app/settings/password-2fa?enforce_2fa_setup_modal=true'
export const TWO_FA_REQUIRED_AFTER_DAYS = 14
