export const CHANGE_PASSWORD_START = 'CHANGE_PASSWORD_START'
export const CHANGE_PASSWORD_SUCCESS = 'CHANGE_PASSWORD_SUCCESS'
export const CHANGE_PASSWORD_ERROR = 'CHANGE_PASSWORD_ERROR'

export const SUBMIT_CURRENT_USER_START = 'SUBMIT_CURRENT_USER_START'
export const SUBMIT_CURRENT_USER_SUCCESS = 'SUBMIT_CURRENT_USER_SUCCESS'
export const SUBMIT_CURRENT_USER_ERROR = 'SUBMIT_CURRENT_USER_ERROR'

export const SUBMIT_SETTING_START = 'SUBMIT_SETTING_START'
export const SUBMIT_SETTING_SUCCESS = 'SUBMIT_SETTING_SUCCESS'
export const SUBMIT_SETTING_ERROR = 'SUBMIT_SETTING_ERROR'

export const TOGGLE_ACTIVE_STATUS = 'TOGGLE_ACTIVE_STATUS'

