export const AGENT_PERFORMANCE_SLICE_NAME = 'agentPerformance'
export const AGENT_AVAILABILITY_SLICE_NAME = 'agentAvailability'
export const AUTO_QA_AGENT_PERFORMANCE_SLICE_NAME = 'autoQAAgentPerformance'
export const INTENT_SLICE_NAME = 'intent'
export const QUALITY_MANAGEMENT_SLICE_NAME = 'qualityManagements'
export const PRODUCTS_PER_TICKET_SLICE_NAME = 'productsPerTicket'
export const PRODUCT_INSIGHTS_SLICE_NAME = 'productInsights'
export const VOICE_AGENTS_PERFORMANCE_SLICE_NAME = 'voiceAgentsPerformance'
