export const BROADCAST_CHANNEL_NAME = 'WebsocketBroadcastChannel'

export const MAX_INCREMENTAL_RECONNECT_BACKOFF = 30
export const DISCONNECTED_NOTIFICATION_DELAY = 10
export const HEALTH_CHECK_INTERVAL = 10
export const HEALTH_CHECK_RECEIVE_TIMEOUT = 5
export const HEALTH_CHECK_SEND_INTERVAL = 1
export const OUTDATED_NOTIFICATION_DELAY = 30
export const SHARED_WORKER_LEGACY_VERSION = 1
export const SHARED_WORKER_VERSION = 6
export const SCOPED_BROADCAST_CHANNEL_NAME = `${BROADCAST_CHANNEL_NAME}-${SHARED_WORKER_VERSION}`
