export const SELF_SERVICE_CONFIGURATIONS_FETCHED =
    'SELF_SERVICE_CONFIGURATIONS/SELF_SERVICE_CONFIGURATIONS_FETCHED'
export const SELF_SERVICE_CONFIGURATION_FETCHED =
    'SELF_SERVICE_CONFIGURATIONS/SELF_SERVICE_CONFIGURATION_FETCHED'
export const SELF_SERVICE_CONFIGURATION_UPDATED =
    'SELF_SERVICE_CONFIGURATIONS/SELF_SERVICE_CONFIGURATION_UPDATED'
