//@flow
export type TicketAuditLogEvent =
    | 'rule-executed'
    | 'ticket-assigned'
    | 'ticket-closed'
    | 'ticket-created'
    | 'ticket-customer-updated'
    | 'ticket-marked-spam'
    | 'ticket-merged'
    | 'ticket-message-created'
    | 'ticket-reopened'
    | 'ticket-snoozed'
    | 'ticket-tags-added'
    | 'ticket-tags-removed'
    | 'ticket-team-assigned'
    | 'ticket-team-unassigned'
    | 'ticket-trashed'
    | 'ticket-unassigned'
    | 'ticket-unmarked-spam'
    | 'ticket-untrashed'
    | 'ticket-updated'
