export const jsonToCovertToWidgets = {
    customer: {
        id: 311,
        name: 'Swim Mer',
        ecommerce_data: {
            'f599447d-2de1-47ea-ab04-7649a421ba7d': {
                store: {
                    deleted_datetime: null,
                    display_name: 'My Store',
                    helpdesk_integration_id: 207,
                    name: 'my-store',
                    default_currency: 'eur',
                    currencies: ['eur', 'usd'],
                    url: 'https://mystore.myshopify.com',
                    created_datetime: '2023-08-02T14:17:57.549232+00:00',
                    type: 'woocommerce',
                    id: 2,
                    uuid: 'f599447d-2de1-47ea-ab04-7649a421ba7d',
                    updated_datetime: null,
                },
                shopper: {
                    deleted_datetime: null,
                    accepts_marketing_sms: false,
                    birthdate: null,
                    accepts_marketing_email: false,
                    external_id: 'c101',
                    email_address: 'swim@gorgias.com',
                    created_datetime: '2023-08-17T15:11:39+00:00',
                    status: null,
                    last_name: 'Mer',
                    middle_name: null,
                    helpdesk_customer_id: 311,
                    first_name: 'Swim',
                    phone_number: null,
                    id: 2,
                    updated_datetime: null,
                },
                orders: [
                    {
                        deleted_datetime: null,
                        shipping_address: {
                            preferred: false,
                            deleted_datetime: null,
                            line_1: '123 Avenue',
                            line_2: null,
                            zip_code: '123456',
                            city: 'Bucharest',
                            external_id: 'abc',
                            state: null,
                            created_datetime: '2023-08-17T15:12:33+00:00',
                            last_name: 'Mer',
                            country: 'Romania',
                            first_name: 'Swim',
                            phone_number: null,
                            id: 6,
                            updated_datetime: null,
                        },
                        financial_status: null,
                        discount_codes: null,
                        shipping_amount: 0,
                        number: 878,
                        name: 'Order #878',
                        tax_amount: 0,
                        external_id: 's101',
                        billing_address: {
                            preferred: false,
                            deleted_datetime: null,
                            line_1: '123 Avenue',
                            line_2: null,
                            zip_code: '123456',
                            city: 'Bucharest',
                            external_id: 'abc',
                            state: null,
                            created_datetime: '2023-08-17T15:12:33+00:00',
                            last_name: 'Mer',
                            country: 'Romania',
                            first_name: 'Swim',
                            phone_number: null,
                            id: 6,
                            updated_datetime: null,
                        },
                        currency: 'usd',
                        created_datetime: '2023-08-17T15:16:48+00:00',
                        fulfillment_status: null,
                        total_amount: 900,
                        subtotal_amount: 900,
                        line_items: [
                            {
                                deleted_datetime: null,
                                discount_reason: null,
                                taxable: null,
                                quantity: 1,
                                fulfilled_quantity: null,
                                unit_price: 900,
                                product_options: null,
                                product: {
                                    barcode: null,
                                    deleted_datetime: null,
                                    taxable: false,
                                    price: 86,
                                    name: 'Awesome product',
                                    external_id: '101',
                                    currency: 'usd',
                                    created_datetime:
                                        '2021-01-07T13:00:00+00:00',
                                    stock: 900,
                                    images: [],
                                    tags: [],
                                    id: 3,
                                    description: 'Foo bar',
                                    sku: 'SKU-101',
                                    updated_datetime:
                                        '2023-08-17T10:45:08+00:00',
                                    requires_shipping: true,
                                },
                                created_datetime: '2023-08-17T15:18:58+00:00',
                                total_amount: 900,
                                discount_amount: null,
                                title: 'my awesome item',
                                discount_type: null,
                                id: 4,
                                updated_datetime: null,
                                requires_shipping: null,
                            },
                            {
                                deleted_datetime: null,
                                discount_reason: null,
                                taxable: null,
                                quantity: 1,
                                fulfilled_quantity: null,
                                unit_price: 901,
                                product_options: null,
                                product: {
                                    barcode: null,
                                    deleted_datetime: null,
                                    taxable: false,
                                    price: 86,
                                    name: 'Awesome product',
                                    external_id: '101',
                                    currency: 'usd',
                                    created_datetime:
                                        '2021-01-07T13:00:00+00:00',
                                    stock: 900,
                                    images: [],
                                    tags: [],
                                    id: 3,
                                    description: 'Foo bar',
                                    sku: 'SKU-101',
                                    updated_datetime:
                                        '2023-08-17T10:45:08+00:00',
                                    requires_shipping: true,
                                },
                                created_datetime: '2023-08-17T15:18:58+00:00',
                                total_amount: 901,
                                discount_amount: null,
                                title: 'my awesome item 2',
                                discount_type: null,
                                id: 5,
                                updated_datetime: null,
                                requires_shipping: null,
                            },
                        ],
                        discount_amount: null,
                        id: 5,
                        updated_datetime: null,
                    },
                ],
                addresses: [
                    {
                        preferred: false,
                        deleted_datetime: null,
                        line_1: '123 Avenue',
                        line_2: null,
                        zip_code: '123456',
                        city: 'Bucharest',
                        external_id: 'abc',
                        state: null,
                        created_datetime: '2023-08-17T15:12:33+00:00',
                        last_name: 'Mer',
                        country: 'Romania',
                        first_name: 'Swim',
                        phone_number: null,
                        id: 6,
                        updated_datetime: null,
                    },
                ],
            },
        },
        external_data: {
            '6318a932ee4d6a5078cde639': {
                foo: 'bar',
                best: 1,
                __app_name__: 'DevRel test app - Ionut',
            },
        },
        integrations: {
            '1': {
                url: 'https://httpbin.org/get?name=Swim Mer',
                args: {
                    name: 'Swim Mer',
                },
                origin: '94.53.66.51',
                headers: {
                    Host: 'httpbin.org',
                    Accept: '*/*',
                    'User-Agent': 'python-requests/2.25.1',
                    'Content-Type': 'application/json',
                    'Accept-Encoding': 'gzip, deflate',
                    'X-Amzn-Trace-Id':
                        'Root=1-6492b4cb-25776e231b1ecdd4193e11cd',
                },
                __integration_type__: 'http',
            },
            '9': {
                orders: [],
                customer: {
                    addresses: [
                        {
                            default: true,
                            zip: '34000',
                            city: 'Montpellier',
                            name: 'Swim Mer',
                            phone: null,
                            province: null,
                            country_name: 'France',
                            last_name: 'Mer',
                            country_code: 'FR',
                            country: 'France',
                            first_name: 'Swim',
                            id: 7311436480711,
                            customer_id: 5854703780039,
                            province_code: null,
                            company: null,
                            address1: '123 Avenue',
                            address2: '',
                        },
                    ],
                    accepts_marketing_updated_at: '2022-03-08T12:25:39+01:00',
                    last_order_name: '#1009',
                    verified_email: true,
                    admin_graphql_api_id:
                        'gid://shopify/Customer/5854703780039',
                    created_at: '2022-03-08T12:25:39+01:00',
                    phone: null,
                    marketing_opt_in_level: null,
                    currency: 'EUR',
                    state: 'disabled',
                    accepts_marketing: false,
                    note: 'This is the best swimmer ever',
                    total_spent: '141.40',
                    tax_exempt: false,
                    last_name: 'Mer',
                    orders_count: 5,
                    last_order_id: 4795495416007,
                    default_address: {
                        default: true,
                        zip: '34000',
                        city: 'Montpellier',
                        name: 'Swim Mer',
                        phone: null,
                        province: null,
                        country_name: 'France',
                        last_name: 'Mer',
                        country_code: 'FR',
                        country: 'France',
                        first_name: 'Swim',
                        id: 7311436480711,
                        customer_id: 5854703780039,
                        province_code: null,
                        company: null,
                        address1: '123 Avenue',
                        address2: '',
                    },
                    updated_at: '2023-04-28T17:47:21+02:00',
                    tags: 'Active Subscriber, test',
                    first_name: 'Swim',
                    id: 5854703780039,
                    sms_marketing_consent: null,
                    email: 'swim@gorgias.com',
                    email_marketing_consent: {
                        state: 'not_subscribed',
                        opt_in_level: 'single_opt_in',
                        consent_updated_at: null,
                    },
                    tax_exemptions: [],
                    multipass_identifier: null,
                },
                __integration_type__: 'shopify',
            },
        },
    },
}
