export enum FeatureFlagKey {
    SelfServiceArticleRecommendation = 'self-service-article-recommendation',
    SelfServiceAutomatedResponseOrderManagement = 'self-service-automated-response-order-management',
    EarlyAdopter = 'early-adopter',
    DefaultMacroToSearch = 'default-macro-to-search',
    MacroForwardByEmail = 'macro-forward-by-email',
    MacroResponseTextCcBcc = 'macro-response-text-cc-bcc',
    PrefillBestMacro = 'pre-fill-best-macro',
    NewPhoneErrorHandling = 'new-phone-error-handling',
    HelpCenterEmbeddedContactForm = 'help-center-embedded-contact-form',
    ElasticsearchSearchLoadTest = 'elasticsearch-search-load-test',
    ElasticsearchTicketSearch = 'elasticsearch-ticket-search',
    SelfServiceLoopReturnsFlow = 'self-service-loop-returns-flow',
    RuleSuggestion = 'rule-suggestion',
    BigCommerceCreateOrder = 'bigcommerce-create-order',
    AppStore = 'app-store',
    EnableWhatsApp = 'enable-whatsapp',
    TicketFields = 'ticket-fields',
    TicketMessagesVirtualization = 'ticket-messages-virtualization',
    EnableSendgrid = 'use-sendgrid',
    RevenueAlphaTesters = 'revenue-alpha-testers',
    RevenueBetaTesters = 'revenue-beta-testers',
    RevenueHideDiscountCodeButton = 'revenue-hide-discount-code-button',
    ChatMergedOrderManagementButton = 'chat-merged-order-management-button',
    AgentsAvailabilityStatus = 'agents-availability-status',
    ChatVideoSharingConversations = 'chat-video-sharing-conversations',
    ChatVideoSharingCampaigns = 'chat-video-sharing-campaigns',
}
