export enum FeatureFlagKey {
    SelfServiceArticleRecommendation = 'self-service-article-recommendation',
    SelfServiceAutomatedResponseOrderManagement = 'self-service-automated-response-order-management',
    EarlyAdopter = 'early-adopter',
    DefaultMacroToSearch = 'default-macro-to-search',
    MacroForwardByEmail = 'macro-forward-by-email',
    MacroResponseTextCcBcc = 'macro-response-text-cc-bcc',
    PrefillBestMacro = 'pre-fill-best-macro',
    NewPhoneErrorHandling = 'new-phone-error-handling',
    HelpCenterEmbeddedContactForm = 'help-center-embedded-contact-form',
    RevenueAlphaTesters = 'revenue-alpha-testers',
    NewVoiceSmsLayout = 'new-voice-sms-layout',
    RevenueDiscountCodesV0 = 'revenue-discount-codes-v0',
    ElasticsearchSearchLoadTest = 'elasticsearch-search-load-test',
    SelfServiceLoopReturnsFlow = 'self-service-loop-returns-flow',
    RuleSuggestion = 'rule-suggestion',
    BigCommerceCreateOrder = 'bigcommerce-create-order',
}
