export enum PageSection {
    Billing = 'billing',
    Integrations = 'integrations',
    Channels = 'channels',
    Macros = 'macros',
    Rules = 'rules',
    ManageTags = 'manage-tags',
    Users = 'users',
    Api = 'api',
    Audit = 'audit',
    Access = 'access',
    SatisfactionSurveys = 'satisfaction-surveys',
    BusinessHours = 'business-hours',
    TicketAssignment = 'ticket-assignment',
    PhoneNumbers = 'phone-numbers',
    HelpCenter = 'help-center',
    SelfService = 'self-service',
    Teams = 'teams',
    ImportData = 'import-data',
    ImportPhoneNumber = 'import-phone-number',
    TwilioSubaccountStatus = 'twilio-subaccount-status',
}

export enum SectionPageHeader {
    Billing = 'Billing & usage',
    Integrations = 'Integrations',
    Channels = 'Channels',
    Macros = 'Macros',
    Rules = 'Rules',
    ManageTags = 'Manage tags',
    Users = 'Users',
    Api = 'REST API',
    Audit = 'Audit logs',
    Access = 'Access management',
    SatisfactionSurveys = 'Satisfaction',
    BusinessHours = 'Business hours',
    TicketAssignment = 'Ticket assignment',
    PhoneNumbers = 'Phone numbers',
    HelpCenter = 'Help Center',
    SelfService = 'Self-service',
    Teams = 'Teams',
    ImportData = 'Import data',
    ImportPhoneNumber = 'Import phone number',
    TwilioSubaccountStatus = 'Twilio Subaccount Status',
}
