//@flow
export const AGENT_ACTIVE = 'agent-active'
export const AGENT_INACTIVE = 'agent-inactive'
export const ACCOUNT_UPDATED = 'account-updated'
export const TICKET_VIEWED = 'ticket-viewed'
export const ROOM_JOINED = 'room-joined'
export const ROOM_LEFT = 'room-left'
export const AGENT_TYPING_STARTED = 'agent-typing-started'
export const AGENT_TYPING_STOPPED = 'agent-typing-stopped'
export const VIEWS_COUNTS_EXPIRED = 'views-counts-expired'
export const SID_UPDATED = 'sid-updated'
export const TICKET_MESSAGE_CHAT_CREATED = 'ticket-message-chat-created'
export const TICKET_CHAT_UPDATED = 'ticket-chat-updated'
export const EMAIL_INTEGRATION_VERIFIED = 'email.integration-verified'
export const FACEBOOK_INTEGRATIONS_RECONNECTED = 'facebook-integrations-reconnected'
export const VIEWS_DEACTIVATED = 'views-deactivated'
