export enum IntentName {
    DiscountRequest = 'discount/request',
    ExchangeRequest = 'exchange/request',
    ExchangeStatus = 'exchange/status',
    FeedbackPositive = 'feedback/positive',
    FeedbackNegative = 'feedback/negative',
    OrderCancel = 'order/cancel',
    OrderChange = 'order/change',
    OrderDamaged = 'order/damaged',
    OrderWrong = 'order/wrong',
    OtherNoReply = 'other/no_reply',
    OtherQuestion = 'other/question',
    OtherThanks = 'other/thanks',
    ProductRecommendation = 'product/recommendation',
    ProductQuestion = 'product/question',
    RefundRequest = 'refund/request',
    RefundStatus = 'refund/status',
    ReturnRequest = 'return/request',
    ReturnStatus = 'return/status',
    ShippingChange = 'shipping/change',
    ShippingDeliveryIssue = 'shipping/delivery-issue',
    ShippingPolicy = 'shipping/policy',
    ShippingStatus = 'shipping/status',
    StockRequest = 'stock/request',
    SubscriptionCancel = 'subscription/cancel',
    SubscriptionChange = 'subscription/change',
}
