export const FETCH_REQUEST_LIST_START = 'FETCH_REQUEST_LIST_START'
export const FETCH_REQUEST_LIST_SUCCESS = 'FETCH_REQUEST_LIST_SUCCESS'
export const FETCH_REQUEST_LIST_ERROR = 'FETCH_REQUEST_LIST_ERROR'

export const CREATE_REQUEST_SUCCESS = 'CREATE_REQUEST_SUCCESS'
export const CREATE_REQUEST_ERROR = 'CREATE_REQUEST_ERROR'

export const UPDATE_REQUEST_SUCCESS = 'UPDATE_REQUEST_SUCCESS'
export const UPDATE_REQUEST_ERROR = 'UPDATE_REQUEST_ERROR'

export const DELETE_REQUEST_SUCCESS = 'DELETE_REQUEST_SUCCESS'
export const DELETE_REQUEST_ERROR = 'DELETE_REQUEST_ERROR'

export const DELETE_BULK_REQUEST_SUCCESS = 'DELETE_BULK_REQUEST_SUCCESS'
