export enum CampaignTriggerKey {
    TimeSpentOnPage = 'time_spent_on_page',
    CurrentUrl = 'current_url',
    BusinessHours = 'business_hours',
    CartValue = 'cart_value',
    ProductTags = 'product_tags',
    CurrentProductTags = 'current_product_tags',
    VisitCount = 'visit_count',
    SessionTime = 'session_time',
    ExitIntent = 'exit_intent',
    SingleInView = 'single_in_view',
    DeviceType = 'device_type',
    OrdersCount = 'orders_count',
    AmountSpent = 'amount_spent',
    OrderedProducts = 'ordered_products',
    CustomerTags = 'customer_tags',
    CountryCode = 'country_code',
}
