import {
    DateFormatType,
    TimeFormatType,
    DateAndTimeFormatting,
    DateTimeFormatMapper,
    DateTimeFormatType,
} from 'constants/datetime'
import {getDateAndTimeFormat} from 'utils/datetime'

describe('getDateAndTimeFormat', () => {
    const timeSetting24hour = TimeFormatType.TwentyFourHour
    const timeSettingAMPM = TimeFormatType.AmPm
    const dateSettingEnGB = DateFormatType.en_GB
    const dateSettingEnUS = DateFormatType.en_US

    it.each([
        [
            timeSetting24hour,
            dateSettingEnGB,
            DateTimeFormatMapper[DateTimeFormatType.TIME_24HOUR],
        ],
        [
            timeSettingAMPM,
            dateSettingEnUS,
            DateTimeFormatMapper[DateTimeFormatType.TIME_AM_PM],
        ],
        [
            timeSetting24hour,
            dateSettingEnUS,
            DateTimeFormatMapper[DateTimeFormatType.TIME_24HOUR],
        ],
        [
            timeSettingAMPM,
            dateSettingEnGB,
            DateTimeFormatMapper[DateTimeFormatType.TIME_AM_PM],
        ],
    ])(
        'should test DateAndTimeFormattingSettingType.Time',
        (timeSetting, dateSetting, expectedFormat) => {
            expect(
                getDateAndTimeFormat(
                    dateSetting,
                    timeSetting,
                    DateAndTimeFormatting.Time
                )
            ).toEqual(expectedFormat)
        }
    )

    it.each([
        [
            timeSetting24hour,
            dateSettingEnGB,
            DateTimeFormatMapper[
                DateTimeFormatType.TIME_DOUBLE_DIGIT_HOUR_24HOUR
            ],
        ],
        [
            timeSettingAMPM,
            dateSettingEnUS,
            DateTimeFormatMapper[
                DateTimeFormatType.TIME_DOUBLE_DIGIT_HOUR_AM_PM
            ],
        ],
        [
            timeSetting24hour,
            dateSettingEnUS,
            DateTimeFormatMapper[
                DateTimeFormatType.TIME_DOUBLE_DIGIT_HOUR_24HOUR
            ],
        ],
        [
            timeSettingAMPM,
            dateSettingEnGB,
            DateTimeFormatMapper[
                DateTimeFormatType.TIME_DOUBLE_DIGIT_HOUR_AM_PM
            ],
        ],
    ])(
        'should test DateAndTimeFormattingSettingType.TimeDoubleDigitHour',
        (timeSetting, dateSetting, expectedFormat) => {
            expect(
                getDateAndTimeFormat(
                    dateSetting,
                    timeSetting,
                    DateAndTimeFormatting.TimeDoubleDigitHour
                )
            ).toEqual(expectedFormat)
        }
    )

    it.each([
        [
            timeSetting24hour,
            dateSettingEnGB,
            DateTimeFormatMapper[DateTimeFormatType.TIME_HOUR_TWENTY_FOUR_HOUR],
        ],
        [
            timeSettingAMPM,
            dateSettingEnUS,
            DateTimeFormatMapper[DateTimeFormatType.TIME_HOUR_AM_PM],
        ],
        [
            timeSetting24hour,
            dateSettingEnUS,
            DateTimeFormatMapper[DateTimeFormatType.TIME_HOUR_TWENTY_FOUR_HOUR],
        ],
        [
            timeSettingAMPM,
            dateSettingEnGB,
            DateTimeFormatMapper[DateTimeFormatType.TIME_HOUR_AM_PM],
        ],
    ])(
        'should test DateAndTimeFormattingSettingType.TimeHour',
        (timeSetting, dateSetting, expectedFormat) => {
            expect(
                getDateAndTimeFormat(
                    dateSetting,
                    timeSetting,
                    DateAndTimeFormatting.TimeHour
                )
            ).toEqual(expectedFormat)
        }
    )

    it.each([
        [
            timeSetting24hour,
            dateSettingEnGB,
            DateTimeFormatMapper[DateTimeFormatType.COMPACT_DATE_EN_GB],
        ],
        [
            timeSettingAMPM,
            dateSettingEnUS,
            DateTimeFormatMapper[DateTimeFormatType.COMPACT_DATE_EN_US],
        ],
        [
            timeSetting24hour,
            dateSettingEnUS,
            DateTimeFormatMapper[DateTimeFormatType.COMPACT_DATE_EN_US],
        ],
        [
            timeSettingAMPM,
            dateSettingEnGB,
            DateTimeFormatMapper[DateTimeFormatType.COMPACT_DATE_EN_GB],
        ],
    ])(
        'should test DateAndTimeFormattingSettingType.CompactDate',
        (timeSetting, dateSetting, expectedFormat) => {
            expect(
                getDateAndTimeFormat(
                    dateSetting,
                    timeSetting,
                    DateAndTimeFormatting.CompactDate
                )
            ).toEqual(expectedFormat)
        }
    )

    it.each([
        [
            timeSetting24hour,
            dateSettingEnGB,
            DateTimeFormatMapper[
                DateTimeFormatType.COMPACT_DATE_WITH_TIME_EN_GB_24_HOUR
            ],
        ],
        [
            timeSettingAMPM,
            dateSettingEnUS,
            DateTimeFormatMapper[
                DateTimeFormatType.COMPACT_DATE_WITH_TIME_EN_US_AM_PM
            ],
        ],
        [
            timeSetting24hour,
            dateSettingEnUS,
            DateTimeFormatMapper[
                DateTimeFormatType.COMPACT_DATE_WITH_TIME_EN_US_24_HOUR
            ],
        ],
        [
            timeSettingAMPM,
            dateSettingEnGB,
            DateTimeFormatMapper[
                DateTimeFormatType.COMPACT_DATE_WITH_TIME_EN_GB_AM_PM
            ],
        ],
    ])(
        'should test DateAndTimeFormattingSettingType.CompactDateWithTime',
        (timeSetting, dateSetting, expectedFormat) => {
            expect(
                getDateAndTimeFormat(
                    dateSetting,
                    timeSetting,
                    DateAndTimeFormatting.CompactDateWithTime
                )
            ).toEqual(expectedFormat)
        }
    )

    it.each([
        [
            timeSetting24hour,
            dateSettingEnGB,
            DateTimeFormatMapper[DateTimeFormatType.SHORT_DATE_EN_GB],
        ],
        [
            timeSettingAMPM,
            dateSettingEnUS,
            DateTimeFormatMapper[DateTimeFormatType.SHORT_DATE_EN_US],
        ],
        [
            timeSetting24hour,
            dateSettingEnUS,
            DateTimeFormatMapper[DateTimeFormatType.SHORT_DATE_EN_US],
        ],
        [
            timeSettingAMPM,
            dateSettingEnGB,
            DateTimeFormatMapper[DateTimeFormatType.SHORT_DATE_EN_GB],
        ],
    ])(
        'should test DateAndTimeFormattingSettingType.ShortDate',
        (timeSetting, dateSetting, expectedFormat) => {
            expect(
                getDateAndTimeFormat(
                    dateSetting,
                    timeSetting,
                    DateAndTimeFormatting.ShortDate
                )
            ).toEqual(expectedFormat)
        }
    )

    it.each([
        [
            timeSetting24hour,
            dateSettingEnGB,
            DateTimeFormatMapper[
                DateTimeFormatType.SHORT_DATE_WITH_ORDINAL_SUFFIX_DAY_EN_GB
            ],
        ],
        [
            timeSettingAMPM,
            dateSettingEnUS,
            DateTimeFormatMapper[
                DateTimeFormatType.SHORT_DATE_WITH_ORDINAL_SUFFIX_DAY_EN_US
            ],
        ],
        [
            timeSetting24hour,
            dateSettingEnUS,
            DateTimeFormatMapper[
                DateTimeFormatType.SHORT_DATE_WITH_ORDINAL_SUFFIX_DAY_EN_US
            ],
        ],
        [
            timeSettingAMPM,
            dateSettingEnGB,
            DateTimeFormatMapper[
                DateTimeFormatType.SHORT_DATE_WITH_ORDINAL_SUFFIX_DAY_EN_GB
            ],
        ],
    ])(
        'should test DateAndTimeFormattingSettingType.ShortDateWithOrdinalSuffixDay',
        (timeSetting, dateSetting, expectedFormat) => {
            expect(
                getDateAndTimeFormat(
                    dateSetting,
                    timeSetting,
                    DateAndTimeFormatting.ShortDateWithOrdinalSuffixDay
                )
            ).toEqual(expectedFormat)
        }
    )

    it.each([
        [
            timeSetting24hour,
            dateSettingEnGB,
            DateTimeFormatMapper[
                DateTimeFormatType.SHORT_DATE_WITH_DAY_OF_WEEK_EN_GB
            ],
        ],
        [
            timeSettingAMPM,
            dateSettingEnUS,
            DateTimeFormatMapper[
                DateTimeFormatType.SHORT_DATE_WITH_DAY_OF_WEEK_EN_US
            ],
        ],
        [
            timeSetting24hour,
            dateSettingEnUS,
            DateTimeFormatMapper[
                DateTimeFormatType.SHORT_DATE_WITH_DAY_OF_WEEK_EN_US
            ],
        ],
        [
            timeSettingAMPM,
            dateSettingEnGB,
            DateTimeFormatMapper[
                DateTimeFormatType.SHORT_DATE_WITH_DAY_OF_WEEK_EN_GB
            ],
        ],
    ])(
        'should test DateAndTimeFormattingSettingType.ShortDateWithDayOfWeek',
        (timeSetting, dateSetting, expectedFormat) => {
            expect(
                getDateAndTimeFormat(
                    dateSetting,
                    timeSetting,
                    DateAndTimeFormatting.ShortDateWithDayOfWeek
                )
            ).toEqual(expectedFormat)
        }
    )

    it.each([
        [
            timeSetting24hour,
            dateSettingEnGB,
            DateTimeFormatMapper[DateTimeFormatType.SHORT_DATE_WITH_YEAR_EN_GB],
        ],
        [
            timeSettingAMPM,
            dateSettingEnUS,
            DateTimeFormatMapper[DateTimeFormatType.SHORT_DATE_WITH_YEAR_EN_US],
        ],
        [
            timeSetting24hour,
            dateSettingEnUS,
            DateTimeFormatMapper[DateTimeFormatType.SHORT_DATE_WITH_YEAR_EN_US],
        ],
        [
            timeSettingAMPM,
            dateSettingEnGB,
            DateTimeFormatMapper[DateTimeFormatType.SHORT_DATE_WITH_YEAR_EN_GB],
        ],
    ])(
        'should test DateAndTimeFormattingSettingType.ShortDateWithYear',
        (timeSetting, dateSetting, expectedFormat) => {
            expect(
                getDateAndTimeFormat(
                    dateSetting,
                    timeSetting,
                    DateAndTimeFormatting.ShortDateWithYear
                )
            ).toEqual(expectedFormat)
        }
    )

    it.each([
        [
            timeSetting24hour,
            dateSettingEnGB,
            DateTimeFormatMapper[
                DateTimeFormatType
                    .SHORT_DATE_WITH_YEAR_AND_ORDINAL_SUFFIX_DAY_EN_GB
            ],
        ],
        [
            timeSettingAMPM,
            dateSettingEnUS,
            DateTimeFormatMapper[
                DateTimeFormatType
                    .SHORT_DATE_WITH_YEAR_AND_ORDINAL_SUFFIX_DAY_EN_US
            ],
        ],
        [
            timeSetting24hour,
            dateSettingEnUS,
            DateTimeFormatMapper[
                DateTimeFormatType
                    .SHORT_DATE_WITH_YEAR_AND_ORDINAL_SUFFIX_DAY_EN_US
            ],
        ],
        [
            timeSettingAMPM,
            dateSettingEnGB,
            DateTimeFormatMapper[
                DateTimeFormatType
                    .SHORT_DATE_WITH_YEAR_AND_ORDINAL_SUFFIX_DAY_EN_GB
            ],
        ],
    ])(
        'should test DateAndTimeFormattingSettingType.ShortDateWithYearAndOrdinalSuffixDay',
        (timeSetting, dateSetting, expectedFormat) => {
            expect(
                getDateAndTimeFormat(
                    dateSetting,
                    timeSetting,
                    DateAndTimeFormatting.ShortDateWithYearAndOrdinalSuffixDay
                )
            ).toEqual(expectedFormat)
        }
    )

    it.each([
        [
            timeSetting24hour,
            dateSettingEnGB,
            DateTimeFormatMapper[
                DateTimeFormatType.SHORT_DATE_WITH_DAY_OF_WEEK_AND_YEAR_EN_GB
            ],
        ],
        [
            timeSettingAMPM,
            dateSettingEnUS,
            DateTimeFormatMapper[
                DateTimeFormatType.SHORT_DATE_WITH_DAY_OF_WEEK_AND_YEAR_EN_US
            ],
        ],
        [
            timeSetting24hour,
            dateSettingEnUS,
            DateTimeFormatMapper[
                DateTimeFormatType.SHORT_DATE_WITH_DAY_OF_WEEK_AND_YEAR_EN_US
            ],
        ],
        [
            timeSettingAMPM,
            dateSettingEnGB,
            DateTimeFormatMapper[
                DateTimeFormatType.SHORT_DATE_WITH_DAY_OF_WEEK_AND_YEAR_EN_GB
            ],
        ],
    ])(
        'should test DateAndTimeFormattingSettingType.ShortDateWithDayOfWeekAndYear',
        (timeSetting, dateSetting, expectedFormat) => {
            expect(
                getDateAndTimeFormat(
                    dateSetting,
                    timeSetting,
                    DateAndTimeFormatting.ShortDateWithDayOfWeekAndYear
                )
            ).toEqual(expectedFormat)
        }
    )

    it.each([
        [
            timeSetting24hour,
            dateSettingEnGB,
            DateTimeFormatMapper[DateTimeFormatType.LONG_DATE_EN_GB],
        ],
        [
            timeSettingAMPM,
            dateSettingEnUS,
            DateTimeFormatMapper[DateTimeFormatType.LONG_DATE_EN_US],
        ],
        [
            timeSetting24hour,
            dateSettingEnUS,
            DateTimeFormatMapper[DateTimeFormatType.LONG_DATE_EN_US],
        ],
        [
            timeSettingAMPM,
            dateSettingEnGB,
            DateTimeFormatMapper[DateTimeFormatType.LONG_DATE_EN_GB],
        ],
    ])(
        'should test DateAndTimeFormattingSettingType.LongDate',
        (timeSetting, dateSetting, expectedFormat) => {
            expect(
                getDateAndTimeFormat(
                    dateSetting,
                    timeSetting,
                    DateAndTimeFormatting.LongDate
                )
            ).toEqual(expectedFormat)
        }
    )

    it.each([
        [
            timeSetting24hour,
            dateSettingEnGB,
            DateTimeFormatMapper[
                DateTimeFormatType.LONG_DATE_WITH_DAY_OF_WEEK_EN_GB
            ],
        ],
        [
            timeSettingAMPM,
            dateSettingEnUS,
            DateTimeFormatMapper[
                DateTimeFormatType.LONG_DATE_WITH_DAY_OF_WEEK_EN_US
            ],
        ],
        [
            timeSetting24hour,
            dateSettingEnUS,
            DateTimeFormatMapper[
                DateTimeFormatType.LONG_DATE_WITH_DAY_OF_WEEK_EN_US
            ],
        ],
        [
            timeSettingAMPM,
            dateSettingEnGB,
            DateTimeFormatMapper[
                DateTimeFormatType.LONG_DATE_WITH_DAY_OF_WEEK_EN_GB
            ],
        ],
    ])(
        'should test DateAndTimeFormattingSettingType.LongDateWithDayOfWeek',
        (timeSetting, dateSetting, expectedFormat) => {
            expect(
                getDateAndTimeFormat(
                    dateSetting,
                    timeSetting,
                    DateAndTimeFormatting.LongDateWithDayOfWeek
                )
            ).toEqual(expectedFormat)
        }
    )

    it.each([
        [
            timeSetting24hour,
            dateSettingEnGB,
            DateTimeFormatMapper[DateTimeFormatType.LONG_DATE_WITH_YEAR_EN_GB],
        ],
        [
            timeSettingAMPM,
            dateSettingEnUS,
            DateTimeFormatMapper[DateTimeFormatType.LONG_DATE_WITH_YEAR_EN_US],
        ],
        [
            timeSetting24hour,
            dateSettingEnUS,
            DateTimeFormatMapper[DateTimeFormatType.LONG_DATE_WITH_YEAR_EN_US],
        ],
        [
            timeSettingAMPM,
            dateSettingEnGB,
            DateTimeFormatMapper[DateTimeFormatType.LONG_DATE_WITH_YEAR_EN_GB],
        ],
    ])(
        'should test DateAndTimeFormattingSettingType.LongDateWithYear',
        (timeSetting, dateSetting, expectedFormat) => {
            expect(
                getDateAndTimeFormat(
                    dateSetting,
                    timeSetting,
                    DateAndTimeFormatting.LongDateWithYear
                )
            ).toEqual(expectedFormat)
        }
    )

    it.each([
        [
            timeSetting24hour,
            dateSettingEnGB,
            DateTimeFormatMapper[
                DateTimeFormatType.LONG_DATE_WITH_YEAR_AND_TIME_EN_GB_24_HOUR
            ],
        ],
        [
            timeSettingAMPM,
            dateSettingEnUS,
            DateTimeFormatMapper[
                DateTimeFormatType.LONG_DATE_WITH_YEAR_AND_TIME_EN_US_AM_PM
            ],
        ],
        [
            timeSetting24hour,
            dateSettingEnUS,
            DateTimeFormatMapper[
                DateTimeFormatType.LONG_DATE_WITH_YEAR_AND_TIME_EN_US_24_HOUR
            ],
        ],
        [
            timeSettingAMPM,
            dateSettingEnGB,
            DateTimeFormatMapper[
                DateTimeFormatType.LONG_DATE_WITH_YEAR_AND_TIME_EN_GB_AM_PM
            ],
        ],
    ])(
        'should test DateAndTimeFormattingSettingType.LongDateWithYearAndTime',
        (timeSetting, dateSetting, expectedFormat) => {
            expect(
                getDateAndTimeFormat(
                    dateSetting,
                    timeSetting,
                    DateAndTimeFormatting.LongDateWithYearAndTime
                )
            ).toEqual(expectedFormat)
        }
    )

    it.each([
        [
            timeSetting24hour,
            dateSettingEnGB,
            DateTimeFormatMapper[DateTimeFormatType.MONTH_AND_YEAR_SHORT],
        ],
        [
            timeSettingAMPM,
            dateSettingEnUS,
            DateTimeFormatMapper[DateTimeFormatType.MONTH_AND_YEAR_SHORT],
        ],
        [
            timeSetting24hour,
            dateSettingEnUS,
            DateTimeFormatMapper[DateTimeFormatType.MONTH_AND_YEAR_SHORT],
        ],
        [
            timeSettingAMPM,
            dateSettingEnGB,
            DateTimeFormatMapper[DateTimeFormatType.MONTH_AND_YEAR_SHORT],
        ],
    ])(
        'should test DateAndTimeFormattingSettingType.MonthAndYearShort',
        (timeSetting, dateSetting, expectedFormat) => {
            expect(
                getDateAndTimeFormat(
                    dateSetting,
                    timeSetting,
                    DateAndTimeFormatting.MonthAndYearShort
                )
            ).toEqual(expectedFormat)
        }
    )

    it.each([
        [
            timeSetting24hour,
            dateSettingEnGB,
            DateTimeFormatMapper[DateTimeFormatType.MONTH_AND_YEAR_LONG],
        ],
        [
            timeSettingAMPM,
            dateSettingEnUS,
            DateTimeFormatMapper[DateTimeFormatType.MONTH_AND_YEAR_LONG],
        ],
        [
            timeSetting24hour,
            dateSettingEnUS,
            DateTimeFormatMapper[DateTimeFormatType.MONTH_AND_YEAR_LONG],
        ],
        [
            timeSettingAMPM,
            dateSettingEnGB,
            DateTimeFormatMapper[DateTimeFormatType.MONTH_AND_YEAR_LONG],
        ],
    ])(
        'should test DateAndTimeFormattingSettingType.MonthAndYearLong',
        (timeSetting, dateSetting, expectedFormat) => {
            expect(
                getDateAndTimeFormat(
                    dateSetting,
                    timeSetting,
                    DateAndTimeFormatting.MonthAndYearLong
                )
            ).toEqual(expectedFormat)
        }
    )

    it.each([
        [
            timeSetting24hour,
            dateSettingEnGB,
            DateTimeFormatMapper[
                DateTimeFormatType.RELATIVE_DATE_AND_TIME_EN_GB_24_HOUR
            ],
        ],
        [
            timeSettingAMPM,
            dateSettingEnUS,
            DateTimeFormatMapper[
                DateTimeFormatType.RELATIVE_DATE_AND_TIME_EN_US_AM_PM
            ],
        ],
        [
            timeSetting24hour,
            dateSettingEnUS,
            DateTimeFormatMapper[
                DateTimeFormatType.RELATIVE_DATE_AND_TIME_EN_US_24_HOUR
            ],
        ],
        [
            timeSettingAMPM,
            dateSettingEnGB,
            DateTimeFormatMapper[
                DateTimeFormatType.RELATIVE_DATE_AND_TIME_EN_GB_AM_PM
            ],
        ],
    ])(
        'should test DateAndTimeFormattingSettingType.RelativeDateAndTime',
        (timeSetting, dateSetting, expectedFormat) => {
            expect(
                getDateAndTimeFormat(
                    dateSetting,
                    timeSetting,
                    DateAndTimeFormatting.RelativeDateAndTime
                )
            ).toEqual(expectedFormat)
        }
    )
})
