export enum IntegrationType {
    Email = 'email',
    Gmail = 'gmail',
    Outlook = 'outlook',
    Aircall = 'aircall',
    GorgiasChat = 'gorgias_chat',
    Smooch = 'smooch',
    SmoochInside = 'smooch_inside',
    Facebook = 'facebook',
    Http = 'http',
    Shopify = 'shopify',
    Recharge = 'recharge',
    Smile = 'smile',
    Magento2 = 'magento2',
    Zendesk = 'zendesk',
    Yotpo = 'yotpo',
    Klaviyo = 'klaviyo',
    Phone = 'phone',
    Twitter = 'twitter',
}

export const MESSAGING_INTEGRATION_TYPES = Object.freeze([
    IntegrationType.Email,
    IntegrationType.Outlook,
    IntegrationType.Gmail,
    IntegrationType.Aircall,
    IntegrationType.SmoochInside,
    IntegrationType.Smooch,
    IntegrationType.Facebook,
    IntegrationType.GorgiasChat,
    IntegrationType.Phone,
    IntegrationType.Twitter,
])
