import { execSync } from 'node:child_process'
import { createHash } from 'node:crypto'
import { readFileSync, writeFileSync } from 'node:fs'
import path from 'node:path'

const outFile = path.resolve(__dirname, '../src/sdkVersionHash.ts')

const output = execSync('pnpm list --recursive --json --depth=0', {
    cwd: path.resolve(__dirname, '../../..'),
    encoding: 'utf-8',
})

type PnpmListEntry = {
    dependencies?: Record<string, { version: string }>
    devDependencies?: Record<string, { version: string }>
}

const packages: PnpmListEntry[] = JSON.parse(output)
const queriesVersions: string[] = []

for (const pkg of packages) {
    const deps = { ...pkg.dependencies, ...pkg.devDependencies }
    for (const [name, info] of Object.entries(deps)) {
        if (
            name.startsWith('@gorgias/') &&
            (name.endsWith('-queries') || name.endsWith('-types'))
        ) {
            queriesVersions.push(`${name}@${info.version}`)
        }
    }
}

const sorted = [...new Set(queriesVersions)].sort()
const hash = createHash('sha256')
    .update(sorted.join(','))
    .digest('hex')
    .slice(0, 8)

const content = `// Auto-generated by scripts/generate-sdk-version-hash.ts — do not edit
export const SDK_VERSION_HASH = '${hash}'
`

try {
    const existing = readFileSync(outFile, 'utf-8')
    if (existing === content) {
        process.exit(0)
    }
} catch {
    // File doesn't exist yet
}

writeFileSync(outFile, content)
