import { createHash } from 'node:crypto'
import { readFileSync, writeFileSync } from 'node:fs'
import path from 'node:path'

const outFile = path.resolve(__dirname, '../src/sdkVersionHash.ts')
const lockfilePath = path.resolve(__dirname, '../../../pnpm-lock.yaml')
const lockfile = readFileSync(lockfilePath, 'utf-8')

const sdkVersions = [
    ...lockfile.matchAll(
        /@gorgias\/[a-z-]+(?:-queries|-types)@(\d+\.\d+\.\d+)/g,
    ),
]
const sorted = [...new Set(sdkVersions.map((m) => m[0]))].sort()
console.log('SDK versions used for hash:', sorted)
const hash = createHash('sha256')
    .update(sorted.join(','))
    .digest('hex')
    .slice(0, 8)

const content = `// Auto-generated by scripts/generate-sdk-version-hash.ts — do not edit
export const SDK_VERSION_HASH = '${hash}'
`

try {
    const existing = readFileSync(outFile, 'utf-8')
    if (existing === content) {
        process.exit(0)
    }
} catch {
    // File doesn't exist yet
}

writeFileSync(outFile, content)
