export const FETCH_WIDGETS_START = 'FETCH_WIDGETS_START'
export const FETCH_WIDGETS_SUCCESS = 'FETCH_WIDGETS_SUCCESS'
export const FETCH_WIDGETS_ERROR = 'FETCH_WIDGETS_ERROR'

export const RESET_WIDGETS = 'RESET_WIDGETS'

export const GENERATE_AND_SET_WIDGETS = 'GENERATE_AND_SET_WIDGETS'

export const START_EDITION = 'START_EDITION'
export const STOP_EDITION = 'STOP_EDITION'

export const START_WIDGET_EDITION = 'START_WIDGET_EDITION'
export const STOP_WIDGET_EDITION = 'STOP_WIDGET_EDITION'

export const ADD_EDITED_WIDGET = 'ADD_EDITED_WIDGET'
export const UPDATE_EDITED_WIDGET = 'UPDATE_EDITED_WIDGET'
export const REMOVE_EDITED_WIDGET = 'REMOVE_EDITED_WIDGET'

export const ADD_FIELD_EDITED_WIDGET = 'ADD_FIELD_EDITED_WIDGET'
export const UPDATE_FIELD_EDITED_WIDGET = 'UPDATE_FIELD_EDITED_WIDGET'

export const DRAG = 'DRAG'
export const CANCEL_DRAG = 'CANCEL_DRAG'
export const DROP = 'DROP'
