export const FETCH_WIDGETS_START = 'FETCH_WIDGETS_START'
export const FETCH_WIDGETS_SUCCESS = 'FETCH_WIDGETS_SUCCESS'
export const FETCH_WIDGETS_ERROR = 'FETCH_WIDGETS_ERROR'

export const RESET_WIDGETS = 'RESET_WIDGETS'
export const SELECT_CONTEXT = 'SELECT_CONTEXT'

export const GENERATE_AND_SET_WIDGETS = 'GENERATE_AND_SET_WIDGETS'
export const SET_EDITED_WIDGETS = 'SET_EDITED_WIDGETS'
export const SET_EDITION_AS_DIRTY = 'SET_EDITION_AS_DIRTY'

export const START_EDITION_MODE = 'START_EDITION_MODE'
export const STOP_EDITION_MODE = 'STOP_EDITION_MODE'

export const START_WIDGET_EDITION = 'START_WIDGET_EDITION'
export const STOP_WIDGET_EDITION = 'STOP_WIDGET_EDITION'

export const UPDATE_EDITED_WIDGET = 'UPDATE_EDITED_WIDGET'
export const REMOVE_EDITED_WIDGET = 'REMOVE_EDITED_WIDGET'

export const DRAG = 'DRAG'
export const CANCEL_DRAG = 'CANCEL_DRAG'
export const DROP = 'DROP'

export const SUBMIT_WIDGET_START = 'SUBMIT_WIDGET_START'
export const SUBMIT_WIDGET_SUCCESS = 'SUBMIT_WIDGET_SUCCESS'
export const SUBMIT_WIDGET_ERROR = 'SUBMIT_WIDGET_ERROR'

export const CUSTOM_WIDGET_TYPE = 'custom'
export const HTTP_WIDGET_TYPE = 'http'
export const MAGENTO2_WIDGET_TYPE = 'magento2'
export const RECHARGE_WIDGET_TYPE = 'recharge'
export const SHOPIFY_WIDGET_TYPE = 'shopify'
export const SMILE_WIDGET_TYPE = 'smile'
export const SMOOCH_INSIDE_WIDGET_TYPE = 'smooch_inside'
export const YOTPO_WIDGET_TYPE = 'yotpo'
export const KLAVIYO_WIDGET_TYPE = 'klaviyo'
