export const allProducts = [
    {
        id: 1,
        title: 'Performance Running Shorts',
        image: { src: 'running-shorts.jpg' },
    },
    { id: 2, title: 'Men’s Compression Top' },
    {
        id: 3,
        title: 'Seamless Yoga Leggings',
        image: { src: 'yoga-leggings.jpg' },
    },
    { id: 4, title: 'Lightweight Training Hoodie' },
    { id: 5, title: 'Women’s Sports Bra', image: { src: 'sports-bra.jpg' } },
    { id: 6, title: 'High-Waisted Gym Leggings' },
    {
        id: 7,
        title: 'Moisture-Wicking T-Shirt',
        image: { src: 'moisture-tee.jpg' },
    },
    { id: 8, title: 'Resistance Band Set' },
    {
        id: 9,
        title: 'Breathable Mesh Tank Top',
        image: { src: 'mesh-tank.jpg' },
    },
    { id: 10, title: 'Youth Track Pants' },
    {
        id: 11,
        title: 'Athletic Water Bottle',
        image: { src: 'water-bottle.jpg' },
    },
    { id: 12, title: 'CrossFit Shorts' },
    {
        id: 13,
        title: 'Outdoor Running Jacket',
        image: { src: 'running-jacket.jpg' },
    },
    { id: 14, title: 'Sweat-Wicking Socks' },
    { id: 15, title: 'Unisex Workout Cap', image: { src: 'workout-cap.jpg' } },
    { id: 16, title: 'Kids Active Tee' },
    {
        id: 17,
        title: 'Men’s Training Joggers',
        image: { src: 'training-joggers.jpg' },
    },
    { id: 18, title: '4-Way Stretch Shorts' },
    { id: 19, title: 'Fitness Gloves', image: { src: 'fitness-gloves.jpg' } },
    { id: 20, title: 'Slim Fit Gym Tee' },
]

export const allTags = [
    'Running Gear',
    'Training Essentials',
    'CrossFit Apparel',
    'HIIT Wear',
    'Yoga Clothing',
    'Gym Gear',
    'Outdoor Fitness',
    'Track & Field',
    'Endurance Equipment',
    'Speed Training',
    'Compression Wear',
    'Relaxed Fit',
    'Slim Fit',
    'High-Waisted',
    'Moisture-Wicking',
    'Seamless Design',
    'Breathable Fabric',
    'Lightweight Material',
    'Four-Way Stretch',
    'Performance Mesh',
].map((tag) => ({
    id: '019838e2-e878-752a-8202-eb2f0c88c48c',
    account_id: 456,
    integration_id: 123,
    source_type: 'shopify',
    lookup_type: 'product_tag',
    created_datetime: '2025-07-23T20:04:11.512000+00:00',
    value: tag,
}))

export const allVendors = [
    'Nike',
    'Adidas',
    'Under Armour',
    'Puma',
    'New Balance',
    'ASICS',
    'Reebok',
    'Columbia Sportswear',
    'Wilson Sporting Goods',
    'Spalding',
    'Rawlings',
    'Easton',
    'Mizuno',
    'Franklin Sports',
    'TRX Training',
    'Rogue Fitness',
    'ProForm',
    'Bowflex (Nautilus Inc.)',
    'The North Face',
    'Salomon',
].map((vendor) => ({
    id: '019838e2-e878-752a-8202-eb2f0c88c48c',
    account_id: 456,
    integration_id: 123,
    source_type: 'shopify',
    lookup_type: 'vendor',
    created_datetime: '2025-07-23T20:04:11.512000+00:00',
    value: vendor,
}))
