export const allProducts = [
    {
        id: 1,
        title: 'Performance Running Shorts',
        image: { src: 'running-shorts.jpg' },
        vendor: 'Nike',
        tags: 'Running, Training',
    },
    {
        id: 2,
        title: 'Men’s Compression Top',
        vendor: 'Adidas',
        tags: 'Training, Compression',
    },
    {
        id: 3,
        title: 'Seamless Yoga Leggings',
        image: { src: 'yoga-leggings.jpg' },
        vendor: 'Under Armour',
        tags: 'Yoga, Leggings',
    },
    {
        id: 4,
        title: 'Lightweight Training Hoodie',
        vendor: 'Puma',
        tags: 'Training, Hoodie',
    },
    {
        id: 5,
        title: 'Women’s Sports Bra',
        image: { src: 'sports-bra.jpg' },
        vendor: 'New Balance',
        tags: 'Sports, Bra',
    },
    {
        id: 6,
        title: 'High-Waisted Gym Leggings',
        vendor: 'Reebok',
        tags: 'Gym, Leggings',
    },
    {
        id: 7,
        title: 'Moisture-Wicking T-Shirt',
        image: { src: 'moisture-tee.jpg' },
        vendor: 'Columbia Sportswear',
        tags: 'Moisture-Wicking, T-Shirt',
    },
    {
        id: 8,
        title: 'Resistance Band Set',
        vendor: 'Wilson Sporting Goods',
        tags: 'Resistance, Band',
    },
    {
        id: 9,
        title: 'Breathable Mesh Tank Top',
        image: { src: 'mesh-tank.jpg' },
        vendor: 'Easton',
        tags: 'Breathable, Mesh Tank Top',
    },
    {
        id: 10,
        title: 'Youth Track Pants',
        vendor: 'Nike',
        tags: 'Youth, Track Pants',
    },
    {
        id: 11,
        title: 'Athletic Water Bottle',
        image: { src: 'water-bottle.jpg' },
        vendor: 'Adidas',
        tags: 'Water Bottle, Athletic',
    },
    {
        id: 12,
        title: 'CrossFit Shorts',
        vendor: 'Under Armour',
        tags: 'CrossFit, Shorts',
    },
    {
        id: 13,
        title: 'Outdoor Running Jacket',
        image: { src: 'running-jacket.jpg' },
        vendor: 'Columbia Sportswear',
        tags: 'Running, Jacket',
    },
    {
        id: 14,
        title: 'Sweat-Wicking Socks',
        vendor: 'Under Armour',
        tags: 'Sweat-Wicking, Socks',
    },
    {
        id: 15,
        title: 'Unisex Workout Cap',
        image: { src: 'workout-cap.jpg' },
        vendor: 'Puma',
        tags: 'Workout, Cap',
    },
    {
        id: 16,
        title: 'Kids Active Tee',
        vendor: 'Nike',
        tags: 'Kids, Active Tee',
    },
    {
        id: 17,
        title: 'Men’s Training Joggers',
        image: { src: 'training-joggers.jpg' },
        vendor: 'Adidas',
        tags: 'Training, Joggers',
    },
    {
        id: 18,
        title: '4-Way Stretch Shorts',
        vendor: 'Under Armour',
        tags: '4-Way Stretch, Shorts',
    },
    {
        id: 19,
        title: 'Fitness Gloves',
        image: { src: 'fitness-gloves.jpg' },
        vendor: 'Under Armour',
        tags: 'Fitness, Gloves',
    },
    {
        id: 20,
        title: 'Slim Fit Gym Tee',
        vendor: 'Puma',
        tags: 'Slim Fit, Gym Tee',
    },
    {
        id: 21,
        title: 'Adjustable Jump Rope',
        image: { src: 'jump-rope.jpg' },
        vendor: 'Nike',
        tags: 'Adjustable, Jump Rope',
    },
    {
        id: 22,
        title: 'Foam Roller',
        image: { src: 'foam-roller.jpg' },
        vendor: 'Under Armour',
        tags: 'Foam Roller',
    },
    {
        id: 23,
        title: 'Hydration Backpack',
        vendor: 'Puma',
        tags: 'Hydration, Backpack',
    },
    {
        id: 24,
        title: 'Men’s Sleeveless Hoodie',
        image: { src: 'sleeveless-hoodie.jpg' },
        vendor: 'Reebok',
        tags: 'Sleeveless, Hoodie',
    },
    {
        id: 25,
        title: 'Women’s Zip-Up Jacket',
        vendor: 'Adidas',
        tags: 'Women’s, Zip-Up Jacket',
    },
    {
        id: 26,
        title: 'Ankle Support Brace',
        image: { src: 'ankle-brace.jpg' },
        vendor: 'Under Armour',
        tags: 'Ankle Support, Brace',
    },
    {
        id: 27,
        title: 'Gym Duffel Bag',
        vendor: 'Puma',
        tags: 'Gym, Duffel Bag',
    },
    {
        id: 28,
        title: 'Grip Strength Trainer',
        image: { src: 'grip-trainer.jpg' },
        vendor: 'Under Armour',
        tags: 'Grip Strength, Trainer',
    },
    {
        id: 29,
        title: 'Longline Sports Tee',
        vendor: 'Nike',
        tags: 'Longline, Sports Tee',
    },
    {
        id: 30,
        title: 'Reflective Running Vest',
        image: { src: 'reflective-vest.jpg' },
        vendor: 'Castore',
        tags: 'Reflective, Running Vest',
    },
]

export const allTags = [
    'Running Gear',
    'Training Essentials',
    'CrossFit Apparel',
    'HIIT Wear',
    'Yoga Clothing',
    'Gym Gear',
    'Outdoor Fitness',
    'Track & Field',
    'Endurance Equipment',
    'Speed Training',
    'Compression Wear',
    'Relaxed Fit',
    'Slim Fit',
    'High-Waisted',
    'Moisture-Wicking',
    'Seamless Design',
    'Breathable Fabric',
    'Lightweight Material',
    'Four-Way Stretch',
    'Performance Mesh',
].map((tag) => ({
    id: '019838e2-e878-752a-8202-eb2f0c88c48c',
    account_id: 456,
    integration_id: 123,
    source_type: 'shopify',
    lookup_type: 'product_tag',
    created_datetime: '2025-07-23T20:04:11.512000+00:00',
    value: tag,
}))

export const allVendors = [
    'Nike',
    'Adidas',
    'Under Armour',
    'Puma',
    'New Balance',
    'ASICS',
    'Reebok',
    'Columbia Sportswear',
    'Wilson Sporting Goods',
    'Spalding',
    'Rawlings',
    'Easton',
    'Mizuno',
    'Franklin Sports',
    'TRX Training',
    'Rogue Fitness',
    'ProForm',
    'Bowflex (Nautilus Inc.)',
    'The North Face',
    'Salomon',
].map((vendor) => ({
    id: '019838e2-e878-752a-8202-eb2f0c88c48c',
    account_id: 456,
    integration_id: 123,
    source_type: 'shopify',
    lookup_type: 'vendor',
    created_datetime: '2025-07-23T20:04:11.512000+00:00',
    value: vendor,
}))

export const allCollections = [
    {
        id: 1,
        title: 'Tennis',
    },
    { id: 2, title: 'Running' },
    {
        id: 3,
        title: 'Football',
    },
    { id: 4, title: 'Golf' },
    { id: 5, title: 'Basketball' },
    { id: 6, title: 'Soccer' },
    {
        id: 7,
        title: 'Hockey',
    },
    { id: 8, title: 'Baseball' },
    {
        id: 9,
        title: 'Volleyball',
    },
    { id: 10, title: 'Softball' },
    {
        id: 11,
        title: 'Summer Sale',
    },
    { id: 12, title: 'CrossFit' },
    {
        id: 13,
        title: 'Winter Sale',
    },
    { id: 14, title: 'Swimwear' },
    { id: 15, title: 'Big discount' },
    { id: 16, title: 'New arrivals' },
    {
        id: 17,
        title: 'Best sellers',
    },
    { id: 18, title: 'Sale' },
    { id: 19, title: 'Clearance' },
    { id: 20, title: 'Free shipping' },
    { id: 21, title: 'New season' },
    { id: 22, title: 'Back to school' },
    { id: 23, title: 'Big sizes' },
    {
        id: 24,
        title: 'Men’s clothing',
    },
    { id: 25, title: 'Women’s clothing' },
    { id: 26, title: 'Kids clothing' },
    { id: 27, title: 'Running shoes' },
    {
        id: 28,
        title: 'Walking shoes',
    },
    { id: 29, title: 'Sandals' },
    {
        id: 30,
        title: 'Boots',
    },
]
