export const FETCH_STATS_SUCCESS = 'FETCH_STATS_SUCCESS'
export const FETCH_STATS_ERROR = 'FETCH_STATS_ERROR'

export const SET_STATS_META = 'SET_STATS_META'
export const SET_STATS_FILTERS = 'SET_STATS_FILTERS'
