export const SET_STAT = 'SET_STAT'
export const SET_STATS_FILTERS = 'SET_STATS_FILTERS'
export const MERGE_STATS_FILTERS = 'MERGE_STATS_FILTERS'
export const RESET_STATS_FILTERS = 'RESET_STATS_FILTERS'
