import React, {ComponentProps} from 'react'
import {Meta, Story} from '@storybook/react'
import _noop from 'lodash/noop'

import refreshIcon from '../../../../../img/icons/refresh.svg'
import {NotificationStatus} from '../../../../state/notifications/types'

import BannerNotification from './BannerNotification'

const storyConfig: Meta = {
    title: 'Feedback/BannerNotification',
    component: BannerNotification,
    parameters: {
        docs: {
            description: {
                component:
                    'Banner component for displaying contextual notifications.',
            },
        },
        backgrounds: {default: 'grey'},
    },
    argTypes: {
        status: {
            control: {
                type: 'select',
            },
        },
        allowHTML: {
            description:
                'Allow custom HTML to be embedded inside the notification container.',
        },
        actionHTML: {
            description:
                'Custom HTML to be embedded inside the notification container as an action.',
        },
        id: {
            description:
                'This prop is either explicitly passed or automatically generated by the notification store.',
            control: {
                type: null,
            },
        },
        hide: {
            description:
                'Prop that handles hiding notifications after interaction with them.',
        },
        dismissible: {
            description:
                'Call the hide() prop after onClick() handler has been called.',
        },
    },
}

const Template: Story<ComponentProps<typeof BannerNotification>> = (props) => (
    <BannerNotification {...props} />
)

const defaultProps = {
    hide: _noop,
    status: NotificationStatus.Info as const,
    message: 'Storybook notification',
}

export const Primary = Template.bind({})
Primary.args = {
    ...defaultProps,
}

export const WithIcon = Template.bind({})
WithIcon.args = {
    ...defaultProps,
    showIcon: true,
}

export const Clickable = Template.bind({})
Clickable.args = {
    ...defaultProps,
}
Clickable.argTypes = {
    onClick: {
        action: 'Clicked !',
    },
}

export const Closable = Template.bind({})
Closable.args = {
    ...defaultProps,
    closable: true,
}
Closable.argTypes = {
    onClose: {
        action: 'Closed !',
    },
}

export const HTMLContent = Template.bind({})
HTMLContent.args = {
    ...defaultProps,
    allowHTML: true,
    message: '<i>This is HTML!</i>',
}

export const HTMLAction = Template.bind({})
HTMLAction.args = {
    ...defaultProps,
    allowHTML: true,
    actionHTML: `<span class="d-inline-flex align-items-baseline">
                  <img src=${refreshIcon} class="mr-2 align-self-center"/><span class="text-primary">Reload page</span>
                 </span>`,
}

export default storyConfig
