import type { CampaignTemplate } from '../types'
import { CSM_CROSS_SELL_COMPLIMENTARY_ITEM } from './csmCrossSellComplimentaryItem'
import { CSM_DRIVE_LOYALTY_PROGRAM_SIGNUPS } from './csmDriveLoyaltyProgramSignups'
import { CSM_HIGHLIGHT_PRODUCTS_FEATURED_IN_BLOG } from './csmHighlightProductsFeaturedInBlog'
import { CSM_PERSONALIZED_EXPERIENCE_BY_TRIGGERING_WITH_UTMS } from './csmPersonalizedExperienceByTriggeringWithUtms'
import { CSM_PRESALE_LANDING_PAGE } from './csmPresaleLandingPage'
import { CSM_SUGGEST_COMPLIMENTARY_PRODUCT_TO_PREVIOUS_PURCHASE } from './csmSuggestComplimentaryProductToPreviousPurchase'
import { CSM_TARGET_KNOWN_RETURN_REASONS_ON_PRODUCT_CART_TRIGGERED_DURING_BUSINESS_HOURS } from './csmTargetKnownReturnReasonsOnProductCartTriggeredDuringBusinessHours'
import { CSM_TARGET_KNOWN_RETURN_REASONS_ON_PRODUCT_CART_TRIGGERED_OUTSIDE_BUSINESS_HOURS } from './csmTargetKnownReturnReasonsOnProductCartTriggeredOutsideBusinessHours'
import { CSM_TARGET_KNOWN_RETURN_REASONS_ON_PRODUCT_DURING_BUSINESS_HOURS } from './csmTargetKnownReturnReasonsOnProductDuringBusinessHours'
import { CSM_TARGET_KNOWN_RETURN_REASONS_ON_PRODUCT_OUTSIDE_BUSINESS_HOURS } from './csmTargetKnownReturnReasonsOnProductOutsideBusinessHours'

export const CSM_CAMPAIGN_TEMPLATES: Record<
    CampaignTemplate['slug'],
    CampaignTemplate
> = {
    [CSM_CROSS_SELL_COMPLIMENTARY_ITEM.slug]: CSM_CROSS_SELL_COMPLIMENTARY_ITEM,
    [CSM_DRIVE_LOYALTY_PROGRAM_SIGNUPS.slug]: CSM_DRIVE_LOYALTY_PROGRAM_SIGNUPS,
    [CSM_HIGHLIGHT_PRODUCTS_FEATURED_IN_BLOG.slug]:
        CSM_HIGHLIGHT_PRODUCTS_FEATURED_IN_BLOG,
    [CSM_PERSONALIZED_EXPERIENCE_BY_TRIGGERING_WITH_UTMS.slug]:
        CSM_PERSONALIZED_EXPERIENCE_BY_TRIGGERING_WITH_UTMS,
    [CSM_PRESALE_LANDING_PAGE.slug]: CSM_PRESALE_LANDING_PAGE,
    [CSM_PRESALE_LANDING_PAGE.slug]: CSM_PRESALE_LANDING_PAGE,
    [CSM_SUGGEST_COMPLIMENTARY_PRODUCT_TO_PREVIOUS_PURCHASE.slug]:
        CSM_SUGGEST_COMPLIMENTARY_PRODUCT_TO_PREVIOUS_PURCHASE,
    [CSM_TARGET_KNOWN_RETURN_REASONS_ON_PRODUCT_CART_TRIGGERED_DURING_BUSINESS_HOURS.slug]:
        CSM_TARGET_KNOWN_RETURN_REASONS_ON_PRODUCT_CART_TRIGGERED_DURING_BUSINESS_HOURS,
    [CSM_TARGET_KNOWN_RETURN_REASONS_ON_PRODUCT_CART_TRIGGERED_OUTSIDE_BUSINESS_HOURS.slug]:
        CSM_TARGET_KNOWN_RETURN_REASONS_ON_PRODUCT_CART_TRIGGERED_OUTSIDE_BUSINESS_HOURS,
    [CSM_TARGET_KNOWN_RETURN_REASONS_ON_PRODUCT_DURING_BUSINESS_HOURS.slug]:
        CSM_TARGET_KNOWN_RETURN_REASONS_ON_PRODUCT_DURING_BUSINESS_HOURS,
    [CSM_TARGET_KNOWN_RETURN_REASONS_ON_PRODUCT_OUTSIDE_BUSINESS_HOURS.slug]:
        CSM_TARGET_KNOWN_RETURN_REASONS_ON_PRODUCT_OUTSIDE_BUSINESS_HOURS,
}
