import {
    ecommerceStoreFixture,
    shopperAddressFixture,
    shopperFixture,
    shopperOrderFixture,
} from 'models/customerEcommerceData/fixtures'

export const jsonToCovertToWidgets = {
    customer: {
        id: 311,
        name: 'Swim Mer',
        ecommerce_data: {
            [ecommerceStoreFixture.uuid]: {
                store: ecommerceStoreFixture,
                shopper: shopperFixture,
                orders: [shopperOrderFixture],
                addresses: [shopperAddressFixture],
            },
        },
        external_data: {
            '6318a932ee4d6a5078cde639': {
                foo: 'bar',
                best: 1,
                __app_name__: 'DevRel test app - Ionut',
            },
        },
        integrations: {
            '1': {
                url: 'https://httpbin.org/get?name=Swim Mer',
                args: {
                    name: 'Swim Mer',
                },
                origin: '94.53.66.51',
                headers: {
                    Host: 'httpbin.org',
                    Accept: '*/*',
                    'User-Agent': 'python-requests/2.25.1',
                    'Content-Type': 'application/json',
                    'Accept-Encoding': 'gzip, deflate',
                    'X-Amzn-Trace-Id':
                        'Root=1-6492b4cb-25776e231b1ecdd4193e11cd',
                },
                __integration_type__: 'http',
            },
            '9': {
                orders: [],
                customer: {
                    addresses: [
                        {
                            default: true,
                            zip: '34000',
                            city: 'Montpellier',
                            name: 'Swim Mer',
                            phone: null,
                            province: null,
                            country_name: 'France',
                            last_name: 'Mer',
                            country_code: 'FR',
                            country: 'France',
                            first_name: 'Swim',
                            id: 7311436480711,
                            customer_id: 5854703780039,
                            province_code: null,
                            company: null,
                            address1: '123 Avenue',
                            address2: '',
                        },
                    ],
                    last_order_name: '#1009',
                    verified_email: true,
                    admin_graphql_api_id:
                        'gid://shopify/Customer/5854703780039',
                    created_at: '2022-03-08T12:25:39+01:00',
                    phone: null,
                    currency: 'EUR',
                    state: 'disabled',
                    note: 'This is the best swimmer ever',
                    total_spent: '141.40',
                    tax_exempt: false,
                    last_name: 'Mer',
                    orders_count: 5,
                    last_order_id: 4795495416007,
                    default_address: {
                        default: true,
                        zip: '34000',
                        city: 'Montpellier',
                        name: 'Swim Mer',
                        phone: null,
                        province: null,
                        country_name: 'France',
                        last_name: 'Mer',
                        country_code: 'FR',
                        country: 'France',
                        first_name: 'Swim',
                        id: 7311436480711,
                        customer_id: 5854703780039,
                        province_code: null,
                        company: null,
                        address1: '123 Avenue',
                        address2: '',
                    },
                    updated_at: '2023-04-28T17:47:21+02:00',
                    tags: 'Active Subscriber, test',
                    first_name: 'Swim',
                    id: 5854703780039,
                    sms_marketing_consent: null,
                    email: 'swim@gorgias.com',
                    email_marketing_consent: {
                        state: 'not_subscribed',
                        opt_in_level: 'single_opt_in',
                        consent_updated_at: null,
                    },
                    tax_exemptions: [],
                    multipass_identifier: null,
                },
                __integration_type__: 'shopify',
            },
        },
    },
}
