export const FETCH_MACRO_LIST_START = 'FETCH_MACRO_LIST_START'
export const FETCH_MACRO_LIST_SUCCESS = 'FETCH_MACRO_LIST_SUCCESS'
export const FETCH_MACRO_LIST_ERROR = 'FETCH_MACRO_LIST_ERROR'

// TicketReplyMacros
export const PREVIEW_MACRO = 'PREVIEW_MACRO'
export const SET_MACROS_VISIBILITY = 'SET_MACROS_VISIBILITY'
export const PREVIEW_ADJACENT_MACRO = 'PREVIEW_ADJACENT_MACRO'

export const PREVIEW_MACRO_IN_MODAL = 'PREVIEW_MACRO_IN_MODAL'
export const PREVIEW_ADJACENT_MACRO_IN_MODAL = 'PREVIEW_ADJACENT_MACRO_IN_MODAL'

// Macro Management Modal
export const ADD_NEW_MACRO = 'ADD_NEW_MACRO'

export const CREATE_MACRO_START = 'CREATE_MACRO_START'
export const CREATE_MACRO_SUCCESS = 'CREATE_MACRO_SUCCESS'
export const CREATE_MACRO_ERROR = 'CREATE_MACRO_ERROR'

export const DELETE_MACRO_START = 'DELETE_MACRO_START'
export const DELETE_MACRO_SUCCESS = 'DELETE_MACRO_SUCCESS'
export const DELETE_MACRO_ERROR = 'DELETE_MACRO_ERROR'

export const ADD_ACTION = 'ADD_ACTION'
export const DELETE_ACTION = 'DELETE_ACTION'

export const UPDATE_MACRO_START = 'UPDATE_MACRO_START'
export const UPDATE_MACRO_SUCCESS = 'UPDATE_MACRO_SUCCESS'
export const UPDATE_MACRO_ERROR = 'UPDATE_MACRO_ERROR'

export const OPEN_MODAL = 'OPEN_MODAL'
export const CLOSE_MODAL = 'CLOSE_MODAL'

export const UPDATE_ACTION_ARGS = 'UPDATE_ACTION_ARGS'

export const UPDATE_ACTION_TITLE = 'UPDATE_ACTION_TITLE'
export const SET_NAME = 'SET_NAME_ON_MACRO'

export const SAVE_SEARCH = 'SAVE_SEARCH'
