export const FETCH_MACRO_LIST_START = 'FETCH_MACRO_LIST_START'
export const FETCH_MACRO_LIST_SUCCESS = 'FETCH_MACRO_LIST_SUCCESS'
export const FETCH_MACRO_LIST_ERROR = 'FETCH_MACRO_LIST_ERROR'

// TicketReplyMacros
export const SET_MACROS_VISIBILITY = 'SET_MACROS_VISIBILITY'

export const CREATE_MACRO_SUCCESS = 'CREATE_MACRO_SUCCESS'
export const CREATE_MACRO_ERROR = 'CREATE_MACRO_ERROR'

export const UPDATE_MACRO_SUCCESS = 'UPDATE_MACRO_SUCCESS'
export const UPDATE_MACRO_ERROR = 'UPDATE_MACRO_ERROR'

export const DELETE_MACRO_SUCCESS = 'DELETE_MACRO_SUCCESS'
export const DELETE_MACRO_ERROR = 'DELETE_MACRO_ERROR'

export const OPEN_MODAL = 'OPEN_MODAL'
export const CLOSE_MODAL = 'CLOSE_MODAL'
