import {
    HTTP_WIDGET_TYPE,
    MAGENTO2_WIDGET_TYPE,
    RECHARGE_WIDGET_TYPE,
    SHOPIFY_WIDGET_TYPE,
    SMILE_WIDGET_TYPE,
    SMOOCH_INSIDE_WIDGET_TYPE,
} from '../../../../../../../state/widgets/constants'

export const WIDGET_COLOR_SUPPORTED_TYPES = [
    HTTP_WIDGET_TYPE,
    MAGENTO2_WIDGET_TYPE,
    RECHARGE_WIDGET_TYPE,
    SHOPIFY_WIDGET_TYPE,
    SMILE_WIDGET_TYPE,
    SMOOCH_INSIDE_WIDGET_TYPE,
]
