import React from 'react'

import { fireEvent, render } from '@testing-library/react'

import FieldMappingSelectorDropdown from '..'
import {
    optionForAutoGenerated,
    optionForCsvColumn,
} from '../../FieldRow/utils'
import type { Props as FieldMappingSelectorDropdownProps } from '../FieldMappingSelectorDropdown'

const props: FieldMappingSelectorDropdownProps = {
    options: [
        optionForAutoGenerated(),
        optionForCsvColumn('article_id'),
        optionForCsvColumn('article_title'),
        optionForCsvColumn('article_body'),
    ],
    selectedOption: undefined,
    onClick: jest.fn(),
}

describe('<FieldMappingSelectorDropdown />', () => {
    it('renders options', () => {
        const { container } = render(
            <FieldMappingSelectorDropdown {...props} />,
        )
        expect(container.firstChild).toMatchSnapshot()
    })

    it('returns the selected option on click', () => {
        const { getByText } = render(
            <FieldMappingSelectorDropdown {...props} />,
        )

        fireEvent.click(getByText('Auto generate'))

        expect(props.onClick).toHaveBeenLastCalledWith(
            '{"kind":"AUTO_GENERATED"}',
        )

        fireEvent.click(getByText('article_id'))

        expect(props.onClick).toHaveBeenLastCalledWith(
            '{"kind":"CSV_COLUMN","csv_column":"article_id"}',
        )
    })
})
