export const FETCH_TAG_LIST_START = 'FETCH_TAG_LIST_START'
export const FETCH_TAG_LIST_SUCCESS = 'FETCH_TAG_LIST_SUCCESS'
export const FETCH_TAG_LIST_ERROR = 'FETCH_TAG_LIST_ERROR'

export const ADD_TAGS = 'ADD_TAGS'
