import { useState } from 'react'

import {
    LegacyCheckBoxField as CheckBoxField,
    LegacyLabel as Label,
} from '@gorgias/axiom'

import {
    INITIAL_FORM_VALUES,
    SMS_DISCLAIMER_MAX_LENGTH,
} from 'pages/aiAgent/constants'
import type { FormValues, UpdateValue } from 'pages/aiAgent/types'
import {
    SettingsCard,
    SettingsCardContent,
    SettingsCardHeader,
    SettingsCardTitle,
} from 'pages/common/components/SettingsCard'
import TextArea from 'pages/common/forms/TextArea'

import css from './SmsFooterFormComponent.less'

type SmsFooterFormComponentProps = {
    smsDisclaimer: string | null
    updateValue: UpdateValue<FormValues>
    isRequired: boolean
    setIsPristine?: (isPristine: boolean) => void
}

export const SmsFooterFormComponent = ({
    smsDisclaimer,
    updateValue,
    setIsPristine,
    isRequired,
}: SmsFooterFormComponentProps) => {
    const initialValue = smsDisclaimer ?? INITIAL_FORM_VALUES.smsDisclaimer
    const [isFooterEnabled, setIsFooterEnabled] = useState<boolean>(() => {
        // Initialize checkbox state based on whether there's a value
        return (
            smsDisclaimer !== null &&
            smsDisclaimer !== '' &&
            smsDisclaimer.trim().length > 0
        )
    })

    const [isBlurred, setIsBlurred] = useState<boolean | null>(null)
    const isSmsDisclaimerValid =
        !isRequired ||
        !isFooterEnabled ||
        isBlurred === false ||
        (smsDisclaimer && smsDisclaimer.trim() && smsDisclaimer.length > 0)

    const handleChange = <K extends keyof FormValues>(
        property: K,
        newValue: FormValues[K],
    ) => {
        if (setIsPristine) setIsPristine(false)
        updateValue(property, newValue)
        setIsBlurred(false)
    }

    const handleBlur = () => {
        setIsBlurred(true)
        // Disable checkbox only when leaving the text area with empty content
        if (!smsDisclaimer || smsDisclaimer.trim().length === 0) {
            setIsFooterEnabled(false)
        }
    }

    const handleCheckboxChange = (value: boolean) => {
        if (setIsPristine) setIsPristine(false)
        setIsFooterEnabled(value)

        if (value) {
            // Set the initial value when enabling the checkbox if smsDisclaimer is null
            if (!smsDisclaimer) {
                updateValue('smsDisclaimer', INITIAL_FORM_VALUES.smsDisclaimer)
            }
        } else {
            // Clear the disclaimer when unchecking
            updateValue('smsDisclaimer', null)
        }
    }

    return (
        <div className={css.formGroup}>
            <SettingsCard>
                <SettingsCardHeader>
                    <SettingsCardTitle
                        id="sms-disclaimer-text-area"
                        isRequired={false}
                    >
                        <Label className={css.label}>
                            Initial message footer
                        </Label>
                    </SettingsCardTitle>
                    <div className={css.formGroupDescription}>
                        At the end of the first SMS sent by AI Agent, you can
                        include a footer to disclose that the message was
                        generated by AI, along with other necessary disclaimers
                        (e.g. &quot;Msg &amp; data rates may apply&quot;;
                        &quot;Reply STOP to unsubscribe&quot;).
                    </div>
                </SettingsCardHeader>
                <SettingsCardContent>
                    <CheckBoxField
                        id="sms-footer-checkbox"
                        className={css.checkbox}
                        value={isFooterEnabled}
                        label="Use initial message footer"
                        onChange={handleCheckboxChange}
                        caption="When enabled, the text below will appear at the end of the first SMS sent to customers by AI Agent."
                    />
                    <TextArea
                        aria-labelledby="sms-disclaimer-text-area"
                        innerClassName={css.formInputEditor}
                        placeholder="Powered by AI"
                        value={initialValue}
                        isDisabled={!isFooterEnabled}
                        onChange={(value) =>
                            handleChange('smsDisclaimer', value)
                        }
                        onBlur={handleBlur}
                        maxLength={SMS_DISCLAIMER_MAX_LENGTH}
                        error={
                            !isSmsDisclaimerValid
                                ? 'SMS footer is required.'
                                : undefined
                        }
                    />
                </SettingsCardContent>
            </SettingsCard>
        </div>
    )
}
