import { useState } from 'react'

import {
    LegacyCheckBoxField as CheckBoxField,
    LegacyLabel as Label,
} from '@gorgias/axiom'

import {
    INITIAL_FORM_VALUES,
    SOCIALS_DISCLAIMER_MAX_LENGTH,
} from 'pages/aiAgent/constants'
import type { FormValues, UpdateValue } from 'pages/aiAgent/types'
import {
    SettingsCard,
    SettingsCardContent,
    SettingsCardHeader,
    SettingsCardTitle,
} from 'pages/common/components/SettingsCard'
import { DefaultExportTextArea as TextArea } from 'pages/common/forms/TextArea'

import css from './SocialsFooterFormComponent.less'

type SocialsFooterFormComponentProps = {
    socialsDisclaimer: string | null
    updateValue: UpdateValue<FormValues>
    isRequired: boolean
    isDisabled?: boolean
    setIsPristine?: (isPristine: boolean) => void
}

export const SocialsFooterFormComponent = ({
    socialsDisclaimer,
    updateValue,
    setIsPristine,
    isRequired,
    isDisabled,
}: SocialsFooterFormComponentProps) => {
    const initialValue =
        socialsDisclaimer ?? INITIAL_FORM_VALUES.socialsDisclaimer
    const [isFooterEnabled, setIsFooterEnabled] = useState<boolean>(() => {
        return (
            socialsDisclaimer !== null &&
            socialsDisclaimer !== '' &&
            socialsDisclaimer.trim().length > 0
        )
    })

    const [isBlurred, setIsBlurred] = useState<boolean | null>(null)
    const isSocialsDisclaimerValid =
        !isRequired ||
        !isFooterEnabled ||
        isBlurred === false ||
        (socialsDisclaimer &&
            socialsDisclaimer.trim() &&
            socialsDisclaimer.length > 0)

    const handleChange = <K extends keyof FormValues>(
        property: K,
        newValue: FormValues[K],
    ) => {
        if (setIsPristine) setIsPristine(false)
        updateValue(property, newValue)
        setIsBlurred(false)
    }

    const handleBlur = () => {
        setIsBlurred(true)
        if (!socialsDisclaimer || socialsDisclaimer.trim().length === 0) {
            setIsFooterEnabled(false)
        }
    }

    const handleCheckboxChange = (value: boolean) => {
        if (setIsPristine) setIsPristine(false)
        setIsFooterEnabled(value)

        if (value) {
            if (!socialsDisclaimer) {
                updateValue(
                    'socialsDisclaimer',
                    INITIAL_FORM_VALUES.socialsDisclaimer,
                )
            }
        } else {
            updateValue('socialsDisclaimer', null)
        }
    }

    return (
        <div className={css.formGroup}>
            <SettingsCard>
                <SettingsCardHeader>
                    <SettingsCardTitle
                        id="socials-disclaimer-text-area"
                        isRequired={false}
                    >
                        <Label className={css.label}>
                            Initial message footer
                        </Label>
                    </SettingsCardTitle>
                    <div className={css.formGroupDescription}>
                        At the end of the first message sent by AI Agent, you
                        can include a footer to disclose that the message was
                        generated by AI, along with other necessary disclaimers.
                    </div>
                </SettingsCardHeader>
                <SettingsCardContent>
                    <CheckBoxField
                        id="socials-footer-checkbox"
                        className={css.checkbox}
                        value={isFooterEnabled}
                        label="Use initial message footer"
                        onChange={handleCheckboxChange}
                        isDisabled={isDisabled}
                        caption="When enabled, the text below will appear at the end of the first message sent to customers by AI Agent."
                    />
                    <TextArea
                        aria-labelledby="socials-disclaimer-text-area"
                        innerClassName={css.formInputEditor}
                        placeholder="Powered by AI"
                        value={initialValue}
                        isDisabled={isDisabled || !isFooterEnabled}
                        onChange={(value) =>
                            handleChange('socialsDisclaimer', value)
                        }
                        onBlur={handleBlur}
                        maxLength={SOCIALS_DISCLAIMER_MAX_LENGTH}
                        error={
                            !isSocialsDisclaimerValid
                                ? 'Socials footer is required.'
                                : undefined
                        }
                    />
                </SettingsCardContent>
            </SettingsCard>
        </div>
    )
}
