// Update a message (retry failed actions or sending, or force sending)
export const UPDATE_TICKET_MESSAGE_START = 'UPDATE_TICKET_MESSAGE_START'
export const UPDATE_TICKET_MESSAGE_SUCCESS = 'UPDATE_TICKET_MESSAGE_SUCCESS'
export const UPDATE_TICKET_MESSAGE_ERROR = 'UPDATE_TICKET_MESSAGE_ERROR'

export const DELETE_TICKET_ERROR = 'DELETE_TICKET_ERROR'

// Reply to a ticket
export const SUBMIT_TICKET_SUCCESS = 'SUBMIT_TICKET_SUCCESS'

// Fetching a single ticket life-cycle
export const FETCH_TICKET_START = 'FETCH_TICKET_START'
export const FETCH_TICKET_SUCCESS = 'FETCH_TICKET_SUCCESS'
export const FETCH_TICKET_ERROR = 'FETCH_TICKET_ERROR'

export const CLEAR_TICKET = 'CLEAR_TICKET'

export const FETCH_TICKET_REPLY_MACRO = 'FETCH_TICKET_REPLY_MACRO'

// Fetching a single ticketMessage to get action results
export const FETCH_MESSAGE_SUCCESS = 'FETCH_MESSAGE_SUCCESS'

export const TICKET_PARTIAL_UPDATE_START = 'TICKET_PARTIAL_UPDATE_START'
export const TICKET_PARTIAL_UPDATE_SUCCESS = 'TICKET_PARTIAL_UPDATE_SUCCESS'
export const TICKET_PARTIAL_UPDATE_ERROR = 'TICKET_PARTIAL_UPDATE_ERROR'

// Macro actions
export const ADD_TICKET_TAGS = 'addTags'
export const TOGGLE_PRIORITY = 'setPriority'
export const SET_STATUS = 'setStatus'
export const SET_AGENT = 'setAssignee'
export const SET_SUBJECT = 'setSubject'

export const REMOVE_TICKET_TAG = 'REMOVE_TICKET_TAG'

export const UPDATE_ACTION_ARGS_ON_APPLIED = 'UPDATE_ACTION_ARGS_ON_APPLIED'
export const DELETE_ACTION_ON_APPLIED = 'DELETE_ACTION_ON_APPLIED'
export const APPLY_MACRO = 'APPLY_MACRO'
export const CLEAR_APPLIED_MACRO = 'CLEAR_APPLIED_MACRO'

export const MARK_TICKET_DIRTY = 'MARK_TICKET_DIRTY'

export const DELETE_TICKET_MESSAGE_START = 'DELETE_TICKET_MESSAGE_START'
export const DELETE_TICKET_MESSAGE_SUCCESS = 'DELETE_TICKET_MESSAGE_SUCCESS'
export const DELETE_TICKET_MESSAGE_ERROR = 'DELETE_TICKET_MESSAGE_ERROR'

export const TOGGLE_HISTORY = 'TOGGLE_HISTORY'

// State-related
export const DISPLAY_HISTORY_ON_NEXT_PAGE = 'DISPLAY_HISTORY_ON_NEXT_PAGE'

// Merge events from sockets updates coming from server
export const MERGE_TICKET = 'MERGE_TICKET'
export const MERGE_REQUESTER = 'MERGE_REQUESTER'
