// Reply to a ticket
export const SUBMIT_TICKET_START = 'SUBMIT_TICKET_START'
export const SUBMIT_TICKET_SUCCESS = 'SUBMIT_TICKET_SUCCESS'
export const SUBMIT_TICKET_ERROR = 'SUBMIT_TICKET_ERROR'

export const SUBMIT_TICKET_MESSAGE_SUCCESS = 'SUBMIT_TICKET_MESSAGE_SUCCESS'
export const SUBMIT_TICKET_MESSAGE_START = 'SUBMIT_TICKET_MESSAGE_START'
export const SUBMIT_TICKET_MESSAGE_ERROR = 'SUBMIT_TICKET_MESSAGE_ERROR'

// Fetching a single ticket life-cycle
export const FETCH_TICKET_START = 'FETCH_TICKET_START'
export const FETCH_TICKET_SUCCESS = 'FETCH_TICKET_SUCCESS'
export const FETCH_TICKET_ERROR = 'FETCH_TICKET_ERROR'

export const CLEAR_TICKET = 'CLEAR_TICKET'

export const FETCH_TICKET_REPLY = 'FETCH_TICKET_REPLY'

// Fetching a single ticketMessage to get action results
export const FETCH_MESSAGE_START = 'FETCH_MESSAGE_START'
export const FETCH_MESSAGE_SUCCESS = 'FETCH_MESSAGE_SUCCESS'
export const FETCH_MESSAGE_ERROR = 'FETCH_MESSAGE_ERROR'

export const TICKET_PARTIAL_UPDATE_START = 'TICKET_PARTIAL_UPDATE_START'
export const TICKET_PARTIAL_UPDATE_SUCCESS = 'TICKET_PARTIAL_UPDATE_SUCCESS'
export const TICKET_PARTIAL_UPDATE_ERROR = 'TICKET_PARTIAL_UPDATE_ERROR'

// Macro actions
export const ADD_TICKET_TAGS = 'addTags'
export const TOGGLE_PRIORITY = 'setPriority'
export const SET_RESPONSE_TEXT = 'setResponseText'
export const SET_STATUS = 'setStatus'
export const SET_AGENT = 'assignUser'
export const ADD_ATTACHMENTS = 'addAttachments'
export const SET_TAGS = 'SET_TAGS'

export const REMOVE_TICKET_TAG = 'REMOVE_TAG'

export const RECORD_MACRO = 'RECORD_MACRO'
export const RECEIVED_MACRO = 'RECEIVED_MACRO'

export const SET_PUBLIC = 'SET_PUBLIC'
export const SET_SUBJECT = 'SET_SUBJECT'
export const SET_SOURCE_TYPE = 'SET_SOURCE_TYPE'
export const SET_RECEIVERS = 'SET_RECEIVERS'

export const MARK_TICKET_DIRTY = 'MARK_TICKET_DIRTY'

export const DELETE_TICKET_MESSAGE_START = 'DELETE_TICKET_MESSAGE_START'
export const DELETE_TICKET_MESSAGE_SUCCESS = 'DELETE_TICKET_MESSAGE_SUCCESS'
export const DELETE_TICKET_MESSAGE_ERROR = 'DELETE_TICKET_MESSAGE_ERROR'

// Action related to attachments
export const ADD_ATTACHMENT_START = 'ADD_ATTACHMENT_START'
export const ADD_ATTACHMENT_SUCCESS = 'ADD_ATTACHMENT_SUCCESS'
export const ADD_ATTACHMENT_ERROR = 'ADD_ATTACHMENT_ERROR'

export const DELETE_ATTACHMENT = 'DELETE_ATTACHMENT'

export const TOGGLE_HISTORY = 'TOGGLE_HISTORY'

// State-related
export const DISPLAY_HISTORY_ON_NEXT_PAGE = 'DISPLAY_HISTORY_ON_NEXT_PAGE'
