export const SEARCH_CUSTOMERS_START = 'SEARCH_CUSTOMERS_START'
export const SEARCH_CUSTOMERS_SUCCESS = 'SEARCH_CUSTOMERS_SUCCESS'
export const SEARCH_CUSTOMERS_ERROR = 'SEARCH_CUSTOMERS_ERROR'

export const SEARCH_SIMILAR_CUSTOMER_START = 'SEARCH_SIMILAR_CUSTOMER_START'
export const SEARCH_SIMILAR_CUSTOMER_SUCCESS = 'SEARCH_SIMILAR_CUSTOMER_SUCCESS'
export const SEARCH_SIMILAR_CUSTOMER_ERROR = 'SEARCH_SIMILAR_CUSTOMER_ERROR'

export const EXECUTE_ACTION_START = 'EXECUTE_ACTION_START'
export const EXECUTE_ACTION_SUCCESS = 'EXECUTE_ACTION_SUCCESS'
export const EXECUTE_ACTION_ERROR = 'EXECUTE_ACTION_ERROR'

export const FETCH_PREVIEW_CUSTOMER_START = 'FETCH_PREVIEW_CUSTOMER_START'
export const FETCH_PREVIEW_CUSTOMER_SUCCESS = 'FETCH_PREVIEW_CUSTOMER_SUCCESS'
export const FETCH_PREVIEW_CUSTOMER_ERROR = 'FETCH_PREVIEW_CUSTOMER_ERROR'

export const FETCH_AVATAR_START = 'FETCH_AVATAR_START'
export const FETCH_AVATAR_SUCCESS = 'FETCH_AVATAR_SUCCESS'
export const FETCH_AVATAR_ERROR = 'FETCH_AVATAR_ERROR'
