export const SEARCH_USERS_START = 'SEARCH_USERS_START'
export const SEARCH_USERS_SUCCESS = 'SEARCH_USERS_SUCCESS'
export const SEARCH_USERS_ERROR = 'SEARCH_USERS_ERROR'

export const SEARCH_TICKETS_START = 'SEARCH_TICKETS_START'
export const SEARCH_TICKETS_SUCCESS = 'SEARCH_TICKETS_SUCCESS'
export const SEARCH_TICKETS_ERROR = 'SEARCH_TICKETS_ERROR'

export const RESET_SEARCH = 'RESET_SEARCH'

export const FETCH_PREVIEW_USER_START = 'FETCH_PREVIEW_USER_START'
export const FETCH_PREVIEW_USER_SUCCESS = 'FETCH_PREVIEW_USER_SUCCESS'
export const FETCH_PREVIEW_USER_ERROR = 'FETCH_PREVIEW_USER_ERROR'

export const FETCH_USER_PICTURE_START = 'FETCH_USER_PICTURE_START'
export const FETCH_USER_PICTURE_SUCCESS = 'FETCH_USER_PICTURE_SUCCESS'
export const FETCH_USER_PICTURE_ERROR = 'FETCH_USER_PICTURE_ERROR'

export const SET_INFOBAR_MODE = 'SET_INFOBAR_MODE'
