import {
    ColumnSourceCsvOnly,
    ColumnSourceCsvOrAutoGenerated,
    CsvColumnPreview,
    LocaleCode,
} from '../../../../../../../models/helpCenter/types'

export interface GorgiasFieldsMappings {
    ArticleTitle?: ColumnSourceCsvOnly
    ArticleContent?: ColumnSourceCsvOnly
    ArticleSlug?: ColumnSourceCsvOrAutoGenerated
    ArticleExcerpt?: ColumnSourceCsvOrAutoGenerated
    CategoryName?: ColumnSourceCsvOnly
    CategoryDescription?: ColumnSourceCsvOnly
    CategorySlug?: ColumnSourceCsvOrAutoGenerated
}

export type GorgiasFields = keyof GorgiasFieldsMappings
export type GorgiasFieldsAutoGeneratable = Extract<
    GorgiasFields,
    'ArticleSlug' | 'ArticleExcerpt' | 'CategorySlug'
>

export type GorgiasFieldsMappingsLocalized = Array<{
    localeCode: LocaleCode
    mappings: GorgiasFieldsMappings
}>

export type CsvColumnsByName = Map<string, CsvColumnPreview>
