import {
    isColumnSourceCsv,
    LocaleCode,
} from '../../../../../../../models/helpCenter/types'
import {slugify} from '../../../../utils/helpCenter.utils'
import {CsvSourceSoftware} from '../../types'
import {guessCsvSourceSoftware} from '../../utils/guess-csv-source-software'

import {
    CsvColumnsByName,
    GorgiasFields,
    GorgiasFieldsMappings,
    GorgiasFieldsMappingsLocalized,
} from './types'

export const updateGorgiasFieldsMappingsLocalized = (
    mappings: GorgiasFieldsMappingsLocalized,
    localeCode: LocaleCode,
    updatedFields: Partial<GorgiasFieldsMappings>
): GorgiasFieldsMappingsLocalized => {
    const updatedMappings = mappings.map((localeMappings) =>
        localeMappings.localeCode !== localeCode
            ? localeMappings
            : {
                  localeCode,
                  mappings: {
                      ...localeMappings.mappings,
                      ...updatedFields,
                  },
              }
    )

    const isNewLocale =
        updatedMappings.find(
            ({localeCode: existingLocaleCode}) =>
                existingLocaleCode === localeCode
        ) === undefined

    if (isNewLocale) {
        return [
            ...updatedMappings,
            {
                localeCode,
                mappings: {
                    ...updatedFields,
                },
            },
        ]
    }

    return updatedMappings
}

const NUM_PREVIEWED_VALUES_PER_COLUMN = 2

const previewFieldCsvColumn = (
    csvColumn: string,
    csvColumnsByName: CsvColumnsByName
): string[] =>
    csvColumnsByName
        .get(csvColumn)
        ?.samples?.slice(0, NUM_PREVIEWED_VALUES_PER_COLUMN) ?? []

// this is a gross approximation of what excerpt generation does in reality during import
// but since the preview column is truncated to 50 characters anyway, there is no need to truncate the excerpt
// the other option would be to duplicate the excerpt function from help-center's API,
// with the risk of having discrepancies in the future between the two
const previewFieldExcerpt = (
    csvColumnsByName: CsvColumnsByName,
    mappings: GorgiasFieldsMappings
): string[] => previewField('ArticleContent', csvColumnsByName, mappings)

const previewFieldArticleSlug = (
    csvColumnsByName: CsvColumnsByName,
    mappings: GorgiasFieldsMappings
): string[] => {
    const articleTitleSamples = previewField(
        'ArticleTitle',
        csvColumnsByName,
        mappings
    )

    return articleTitleSamples.map(slugify)
}

const previewFieldCategorySlug = (
    csvColumnsByName: CsvColumnsByName,
    mappings: GorgiasFieldsMappings
): string[] => {
    const categoryNameSamples = previewField(
        'CategoryName',
        csvColumnsByName,
        mappings
    )

    return categoryNameSamples.map(slugify)
}

const previewFieldAutoGenerated = (
    target: GorgiasFields,
    csvColumnsByName: CsvColumnsByName,
    mappings: GorgiasFieldsMappings
): string[] => {
    switch (target) {
        case 'ArticleSlug':
            return previewFieldArticleSlug(csvColumnsByName, mappings)
        case 'ArticleExcerpt':
            return previewFieldExcerpt(csvColumnsByName, mappings)
        case 'CategorySlug':
            return previewFieldCategorySlug(csvColumnsByName, mappings)
        default:
            return []
    }
}

export const previewField = (
    target: GorgiasFields,
    csvColumnsByName: CsvColumnsByName,
    mappings: GorgiasFieldsMappings
): string[] => {
    const mapping = mappings[target]
    if (mapping === undefined) {
        return []
    }

    return isColumnSourceCsv(mapping.source)
        ? previewFieldCsvColumn(mapping.source.csv_column, csvColumnsByName)
        : previewFieldAutoGenerated(target, csvColumnsByName, mappings)
}

export const mappingsComplete = (
    mappings: GorgiasFieldsMappingsLocalized
): boolean =>
    mappings.every(
        ({mappings: localeMappings}) =>
            localeMappings.ArticleTitle !== undefined &&
            localeMappings.ArticleContent !== undefined &&
            localeMappings.ArticleSlug !== undefined
    )

const initialMappingsForGorgiasTemplate = (
    defaultLocale: LocaleCode
): GorgiasFieldsMappingsLocalized => [
    {
        localeCode: defaultLocale,
        mappings: {
            ArticleTitle: {
                source: {
                    kind: 'CSV_COLUMN',
                    csv_column: 'article_title',
                },
            },
            ArticleContent: {
                source: {
                    kind: 'CSV_COLUMN',
                    csv_column: 'article_body',
                },
            },
            ArticleSlug: {
                source: {
                    kind: 'CSV_COLUMN',
                    csv_column: 'article_slug',
                },
            },
            ArticleExcerpt: {
                source: {
                    kind: 'CSV_COLUMN',
                    csv_column: 'article_excerpt',
                },
            },
            CategoryName: {
                source: {
                    kind: 'CSV_COLUMN',
                    csv_column: 'category_title',
                },
            },
            CategorySlug: {
                source: {
                    kind: 'CSV_COLUMN',
                    csv_column: 'category_slug',
                },
            },
            CategoryDescription: {
                source: {
                    kind: 'CSV_COLUMN',
                    csv_column: 'category_description',
                },
            },
        },
    },
]

const initialMappingsForHelpdocs = (
    defaultLocale: LocaleCode
): GorgiasFieldsMappingsLocalized => [
    {
        localeCode: defaultLocale,
        mappings: {
            ArticleTitle: {
                source: {
                    kind: 'CSV_COLUMN',
                    csv_column: 'title',
                },
            },
            ArticleContent: {
                source: {
                    kind: 'CSV_COLUMN',
                    csv_column: 'body',
                },
            },
            ArticleSlug: {
                source: {
                    kind: 'AUTO_GENERATED',
                },
            },
            ArticleExcerpt: {
                source: {
                    kind: 'AUTO_GENERATED',
                },
            },
            CategoryName: {
                source: {
                    kind: 'CSV_COLUMN',
                    csv_column: 'category_title',
                },
            },
            CategorySlug: {
                source: {
                    kind: 'AUTO_GENERATED',
                },
            },
        },
    },
]

export const initialMappings = (
    defaultLocale: LocaleCode,
    csvColumnsNames: string[]
): GorgiasFieldsMappingsLocalized => {
    const sourceSoftware = guessCsvSourceSoftware(csvColumnsNames)

    switch (sourceSoftware) {
        case CsvSourceSoftware.Helpdocs:
            return initialMappingsForHelpdocs(defaultLocale)
        case CsvSourceSoftware.GorgiasTemplate:
            return initialMappingsForGorgiasTemplate(defaultLocale)
        case CsvSourceSoftware.Unknown:
            return [
                {
                    localeCode: defaultLocale,
                    mappings: {
                        ArticleSlug: {
                            source: {
                                kind: 'AUTO_GENERATED',
                            },
                        },
                        ArticleExcerpt: {
                            source: {
                                kind: 'AUTO_GENERATED',
                            },
                        },
                        CategorySlug: {
                            source: {
                                kind: 'AUTO_GENERATED',
                            },
                        },
                    },
                },
            ]
    }
}
