import { ReportingGranularity } from 'domains/reporting/models/types'
import { LogicalOperatorEnum } from 'domains/reporting/pages/common/components/Filter/constants'
import { exampleResponseData } from 'domains/reporting/pages/convert/components/DownloadOverviewData/__tests__/DownloadOverviewData.spec'
import {
    CampaignReportContext,
    fetchCampaignReportData,
} from 'domains/reporting/pages/convert/components/DownloadOverviewData/GenerateReportService'
import { fetchGetTableStat } from 'domains/reporting/pages/convert/hooks/stats/useGetTableStat'
import { campaign } from 'fixtures/campaign'
import { shopifyIntegration } from 'fixtures/integrations'
import { CampaignPreview } from 'models/convert/campaign/types'
import { assumeMock } from 'utils/testing'

jest.mock('domains/reporting/pages/convert/hooks/stats/useGetTableStat')
const fetchGetTableStatMock = assumeMock(fetchGetTableStat)

describe('GenerateReportService', () => {
    const statsFilters = {
        period: {
            start_datetime: '2024-01-01T00:00:00.000Z',
            end_datetime: '2024-01-31T23:59:59.999Z',
        },
    }
    const timezone = 'UTC'
    const granularity = ReportingGranularity.Day

    const campaignsReportContext: CampaignReportContext = {
        selectedPeriod: statsFilters.period,
        namespacedShopName: shopifyIntegration.meta.shop_name,
        selectedCampaignsOperator: LogicalOperatorEnum.ONE_OF,
        selectedCampaignIds: [],
        campaigns: [campaign as CampaignPreview],
    }
    const mockedCSV =
        '"Campaign name","Status","Total revenue","Impressions","Engagement","Click-through rate","Orders","Total conversion rate","Tickets created","Tickets creation rate","Tickets converted","Tickets conversion rate","Revenue generated by tickets","Clicks","Click rate","Clicks converted","Clicks conversion rate","Revenue generated by campaign clicks","Discount codes used","Revenue generated by discount codes"\r\n"Welcome to the internet","active","39.28","868","23","2.65%","1","4.35%","0","0%","0","0%","0","23","2.65%","1","4.35%","39.28","0","0"'

    describe('fetchCampaignReportData', () => {
        beforeEach(() => {
            jest.useFakeTimers().setSystemTime(new Date('2024-09-23T00:00:00Z'))
            fetchGetTableStatMock.mockResolvedValue({
                data: exampleResponseData,
                isFetching: false,
                isError: false,
            })
        })
        it('should fetch data and return formatted report', async () => {
            const result = await fetchCampaignReportData(
                statsFilters,
                timezone,
                granularity,
                {
                    campaignsReportContext,
                },
            )

            expect(result).toEqual({
                files: { 'performance-2024-09-23.csv': mockedCSV },
                fileName: 'campaign-performance-2024-09-23',
                isLoading: false,
            })
        })
    })
})
