export const CREATE_AGENT_SUCCESS = 'CREATE_AGENT_SUCCESS'
export const UPDATE_AGENT_SUCCESS = 'UPDATE_AGENT_SUCCESS'
export const DELETE_AGENT_SUCCESS = 'DELETE_AGENT_SUCCESS'

export const FETCH_AGENT_ERROR = 'FETCH_AGENT_ERROR'

export const FETCH_USER_LIST_START = 'FETCH_USER_LIST_START'
export const FETCH_USER_LIST_SUCCESS = 'FETCH_USER_LIST_SUCCESS'
export const FETCH_USER_LIST_ERROR = 'FETCH_USER_LIST_ERROR'

export const AI_AGENT_CLIENT_ID = '658d6f54fbff9b7c6f2d0321'

export const AUTOMATION_BOT_EMAIL_ACROSS_ALL_ACCOUNTS = [
    'bot@658d6f54fbff9b7c6f2d0321',
    'bot@658d6f54fbff9b7c6f2d0321.gorgias.com',
]

export const SET_AGENT_FEEDBACK_MESSAGE_STATUS =
    'SET_AGENT_FEEDBACK_MESSAGE_STATUS'
