// Reply to a ticket
export const NEW_MESSAGE_SUBMIT_TICKET_START = 'NEW_MESSAGE_SUBMIT_TICKET_START'
export const NEW_MESSAGE_SUBMIT_TICKET_SUCCESS =
    'NEW_MESSAGE_SUBMIT_TICKET_SUCCESS'
export const NEW_MESSAGE_SUBMIT_TICKET_ERROR = 'NEW_MESSAGE_SUBMIT_TICKET_ERROR'

export const NEW_MESSAGE_SUBMIT_TICKET_MESSAGE_START =
    'NEW_MESSAGE_SUBMIT_TICKET_MESSAGE_START'
export const NEW_MESSAGE_SUBMIT_TICKET_MESSAGE_SUCCESS =
    'NEW_MESSAGE_SUBMIT_TICKET_MESSAGE_SUCCESS'
export const NEW_MESSAGE_SUBMIT_TICKET_MESSAGE_ERROR =
    'NEW_MESSAGE_SUBMIT_TICKET_MESSAGE_ERROR'

// Macro actions
export const SET_RESPONSE_TEXT = 'setResponseText'
export const ADD_ATTACHMENTS = 'addAttachments'

export const NEW_MESSAGE_FETCH_TICKET_SUCCESS =
    'NEW_MESSAGE_FETCH_TICKET_SUCCESS'

export const NEW_MESSAGE_SET_SOURCE_TYPE = 'NEW_MESSAGE_SET_SOURCE_TYPE'
export const NEW_MESSAGE_SET_SOURCE_EXTRA = 'NEW_MESSAGE_SET_SOURCE_EXTRA'
export const NEW_MESSAGE_SET_RECEIVERS = 'NEW_MESSAGE_SET_RECEIVERS'
export const NEW_MESSAGE_SET_SENDER = 'NEW_MESSAGE_SET_SENDER'
export const NEW_MESSAGE_SET_SUBJECT = 'NEW_MESSAGE_SET_SUBJECT'

export const NEW_MESSAGE_RESET_FROM_TICKET = 'NEW_MESSAGE_RESET_FROM_TICKET'

export const NEW_MESSAGE_RECORD_MACRO = 'NEW_MESSAGE_RECORD_MACRO'

// Action related to attachments
export const NEW_MESSAGE_ADD_ATTACHMENT_START =
    'NEW_MESSAGE_ADD_ATTACHMENT_START'
export const NEW_MESSAGE_ADD_ATTACHMENT_SUCCESS =
    'NEW_MESSAGE_ADD_ATTACHMENT_SUCCESS'
export const NEW_MESSAGE_ADD_ATTACHMENT_ERROR =
    'NEW_MESSAGE_ADD_ATTACHMENT_ERROR'

export const NEW_MESSAGE_DELETE_ATTACHMENT = 'NEW_MESSAGE_DELETE_ATTACHMENT'

export const NEW_MESSAGE_ADD_EMAIL_EXTRA = 'NEW_MESSAGE_ADD_EMAIL_EXTRA'

export const NEW_MESSAGE_RESET_FROM_MESSAGE = 'NEW_MESSAGE_RESET_FROM_MESSAGE'
