export { CustomerInfo } from './components/ShopifyCustomer/components/CustomerInfo'
export type { OrderSidePanelRenderProps } from './components/ShopifyCustomer/components/CustomerInfo'
export type { EditShippingAddressModalRenderProps } from './components/ShopifyCustomer/components/CustomerInfo/orders/sidePanel/OrderSidePanelPreview'
export { OrderSidePanelContent } from './components/ShopifyCustomer/components/CustomerInfo/orders/sidePanel/OrderSidePanelContent'
export type { OrderData } from './components/ShopifyCustomer/components/CustomerInfo/orders/sidePanel/OrderSidePanelContent'
export { OrderSidePanelPreview } from './components/ShopifyCustomer/components/CustomerInfo/orders/sidePanel/OrderSidePanelPreview'
export { ShopifyCustomer } from './components/ShopifyCustomer'
export { ShopifyCustomerProvider } from './components/ShopifyCustomer/ShopifyCustomerProvider'
export { NotificationStatus } from './components/ShopifyCustomer/ShopifyCustomerContext'
export type { ShopifyCustomerContextType } from './components/ShopifyCustomer/ShopifyCustomerContext'
export type { ShopperData } from './components/ShopifyCustomer/types'
