export const FETCH_CURRENT_PRODUCTS_USAGE_ERROR =
    'FETCH_CURRENT_PRODUCTS_USAGE_ERROR'
export const FETCH_CURRENT_PRODUCTS_USAGE_SUCCESS =
    'FETCH_CURRENT_PRODUCTS_USAGE_SUCCESS'

export const FETCH_INVOICES_ERROR = 'FETCH_INVOICES_ERROR'
export const FETCH_INVOICES_SUCCESS = 'FETCH_INVOICES_SUCCESS'

export const UPDATE_BILLING_CONTACT_ERROR = 'UPDATE_BILLING_CONTACT_ERROR'

export const UPDATE_INVOICE_IN_LIST = 'UPDATE_INVOICE_IN_LIST'

export const FETCH_BILLING_STATE_ERROR = 'FETCH_BILLING_STATE_ERROR'
