export const FETCH_CURRENT_PRODUCTS_USAGE_ERROR =
    'FETCH_CURRENT_PRODUCTS_USAGE_ERROR'
export const FETCH_CURRENT_PRODUCTS_USAGE_SUCCESS =
    'FETCH_CURRENT_PRODUCTS_USAGE_SUCCESS'

export const UPDATE_BILLING_CONTACT_ERROR = 'UPDATE_BILLING_CONTACT_ERROR'

export const FETCH_BILLING_STATE_ERROR = 'FETCH_BILLING_STATE_ERROR'
