export { THEME_NAME, themeTokenMap } from '@gorgias/design-tokens'
export type { ColorTokens, ThemeName } from '@gorgias/design-tokens'

export { THEME_CONFIGS } from './constants'
export type { HelpdeskThemeName } from './types'
export { ThemeProvider } from './ThemeProvider'
export { useApplyTheme } from './useApplyTheme'
export { useSetTheme } from './useSetTheme'
export { useTheme } from './useTheme'
export { withTheme } from './withTheme'
export type { WithThemeProps } from './withTheme'
