export const UPDATE_ACCOUNT_START = 'UPDATE_ACCOUNT_START'
export const UPDATE_ACCOUNT_SUCCESS = 'UPDATE_ACCOUNT_SUCCESS'
export const UPDATE_ACCOUNT_ERROR = 'UPDATE_ACCOUNT_ERROR'

export const UPDATE_ACCOUNT_SETTING = 'UPDATE_ACCOUNT_SETTING'
export const UPDATE_ACCOUNT_SETTING_ERROR = 'UPDATE_ACCOUNT_SETTING_ERROR'
