export const UPDATE_ACCOUNT_START = 'UPDATE_ACCOUNT_START'
export const UPDATE_ACCOUNT_SUCCESS = 'UPDATE_ACCOUNT_SUCCESS'
export const UPDATE_ACCOUNT_ERROR = 'UPDATE_ACCOUNT_ERROR'

export const UPDATE_ACCOUNT_SETTING = 'UPDATE_ACCOUNT_SETTING'
export const UPDATE_ACCOUNT_SETTING_ERROR = 'UPDATE_ACCOUNT_SETTING_ERROR'

export const UPDATE_SUBSCRIPTION_ERROR = 'UPDATE_SUBSCRIPTION_ERROR'
export const UPDATE_SUBSCRIPTION_SUCCESS = 'UPDATE_SUBSCRIPTION_SUCCESS'

export const SETTING_TYPE_SATISFACTION_SURVEYS = 'satisfaction-surveys'
export const SETTING_TYPE_BUSINESS_HOURS = 'business-hours'
