// Fetch individual view definitions
export const FETCH_USER_START = 'FETCH_USER_START'
export const FETCH_USER_SUCCESS = 'FETCH_USER_SUCCESS'
export const FETCH_USER_ERROR = 'FETCH_USER_ERROR'

export const FETCH_CURRENT_USER_START = 'FETCH_CURRENT_USER_START'
export const FETCH_CURRENT_USER_SUCCESS = 'FETCH_CURRENT_USER_SUCCESS'
export const FETCH_CURRENT_USER_ERROR = 'FETCH_CURRENT_USER_ERROR'

export const FETCH_USER_LIST_START = 'FETCH_USER_LIST_START'
export const FETCH_USER_LIST_SUCCESS = 'FETCH_USER_LIST_SUCCESS'
export const FETCH_USER_LIST_ERROR = 'FETCH_USER_LIST_ERROR'

export const SUBMIT_USER_START = 'SUBMIT_USER_START'
export const SUBMIT_USER_SUCCESS = 'SUBMIT_USER_SUCCESS'
export const SUBMIT_USER_ERROR = 'SUBMIT_USER_ERROR'

export const SUBMIT_CURRENT_USER_START = 'SUBMIT_CURRENT_USER_START'
export const SUBMIT_CURRENT_USER_SUCCESS = 'SUBMIT_CURRENT_USER_SUCCESS'
export const SUBMIT_CURRENT_USER_ERROR = 'SUBMIT_CURRENT_USER_ERROR'

export const DELETE_USER_START = 'DELETE_USER_START'
export const DELETE_USER_SUCCESS = 'DELETE_USER_SUCCESS'
export const DELETE_USER_ERROR = 'DELETE_USER_ERROR'

// Action related to user history (timeline)
export const FETCH_USER_HISTORY_START = 'FETCH_USER_HISTORY_START'
export const FETCH_USER_HISTORY_SUCCESS = 'FETCH_USER_HISTORY_SUCCESS'
export const FETCH_USER_HISTORY_ERROR = 'FETCH_USER_HISTORY_ERROR'

export const CLEAR_USER = 'CLEAR_USER'
