export enum Tab {
    EmailForwarding = 'forwarding',
    EmailVerification = 'verification',
    EmailDomainVerification = 'dns',
    EmailOutboundVerification = 'outbound-verification',
    EmailCustom = 'custom',
    FacebookCustomerChat = 'customer_chat',
    Preferences = 'preferences',
    FacebookAds = 'ads',
    HttpEvents = 'events',
    Installation = 'installation',
    QuickReplies = 'quick_replies',
    Campaigns = 'campaigns',
    Appearance = 'appearance',
    PhoneVoicemail = 'voicemail',
    PhoneGreetingMessage = 'greeting-message',
    PhoneIvr = 'ivr',
    CreateWizard = 'create-wizard',
    Languages = 'languages',
}
