export const SECTIONS_FETCHED = 'SECTIONS/SECTIONS_FETCHED'
export const SECTION_CREATED = 'SECTIONS/SECTION_CREATED'
export const SECTION_UPDATED = 'SECTIONS/SECTION_UPDATED'
export const SECTION_DELETED = 'SECTIONS/SECTION_DELETED'
