export const ADD_RULE_START = 'ADD_RULE_START'
export const ADD_RULE_END = 'ADD_RULE_END'

export const RULES_REQUESTS_POSTS = 'RULES_REQUESTS_POSTS'
export const RULES_RECEIVE_POSTS = 'RULES_RECEIVE_POSTS'

export const ERROR_MESSAGE = 'ERROR_MESSAGE'

export const RULES_UPDATE_CODE_AST = 'RULES_UPDATE_CODE_AST'