import type { ArticleOrigin } from 'pages/settings/helpCenter/types/articleOrigin.enum'
import type { Components } from 'rest_api/help_center_api/client.generated'

// GENERAL

export type Locale = Components.Schemas.LocaleDto
export type LocaleCode = Components.Schemas.LocaleDto['code']

// HELP CENTER

export type CreateHelpCenterDto = Omit<
    Components.Schemas.CreateHelpCenterWithAccountIdDto,
    'account_id'
>
export type UpdateHelpCenterDto = Components.Schemas.UpdateHelpCenterDto
export type CreateHelpCenterTranslationDto =
    Components.Schemas.CreateHelpCenterTranslationDto

export type HelpCentersListPage = Components.Schemas.HelpCentersListPageDto
export type HelpCenterTranslation = Components.Schemas.HelpCenterTranslationDto
export type HelpCenterTranslationSeoMeta =
    Components.Schemas.HelpCenterTranslationSeoMeta

export type HelpCenter = Omit<
    Components.Schemas.GetHelpCenterDto,
    'contact_form' | 'account_id'
> & {
    customDomain?: CustomDomain
    translations?: HelpCenterTranslation[]
}

// CONTACT INFO

export type ContactInfoDto = Components.Schemas.ContactInfoDto
export type ChatContactInfoDto = Components.Schemas.ChatContactInfoDto
export type EmailContactInfoDto = Components.Schemas.EmailContactInfoDto
export type PhoneContactInfoDto = Components.Schemas.PhoneContactInfoDto
export type ContactPhoneNumber = Components.Schemas.ContactPhoneNumber

export type EmailIntegration = {
    email: string | null
    id: number | null
}

// CATEGORIES

export type CreateCategoryDto = Components.Schemas.CreateCategoryDto
export type CreateCategoryTranslationDto =
    Components.Schemas.CreateCategoryTranslationDto
export type UpdateCategoryTranslationDto =
    Components.Schemas.UpdateCategoryTranslationDto

export type CategoriesListPage = Components.Schemas.CategoriesListPageDto
export type CategoryWithLocalTranslation = Components.Schemas.CategoryTreeDto
export type CategoryTranslation = Components.Schemas.CategoryTranslationDto
export type CategoryTranslationSeoMeta =
    Components.Schemas.CategoryTranslationSeoMeta
export type LocalCategoryTranslation =
    Components.Schemas.LocalCategoryTranslation

export type Category = Omit<CategoryWithLocalTranslation, 'children'> & {
    children: number[]
    articleCount: number
}

export type NonRootCategory = Omit<Category, 'translation'> & {
    translation: NonNullable<Category['translation']>
}

// ARTICLES

export type CreateArticleDto = Components.Schemas.CreateArticleDto
export type CreateArticleTranslationDto =
    Components.Schemas.CreateArticleTranslationDto
export type UpdateArticleTranslationDto =
    Components.Schemas.UpdateArticleTranslationDto

export type ArticleTranslationResponseDto =
    Components.Schemas.ArticleTranslationResponseDto

export type ArticlesListPage = Components.Schemas.ArticlesListPageDto
export type ArticleWithLocalTranslationAndRating =
    Components.Schemas.ArticleListDataDto
export type ArticleWithLocalTranslation =
    Components.Schemas.ArticleWithLocalTranslation
export type Rating = Components.Schemas.Rating

export type ArticleTranslationWithRating =
    Components.Schemas.ArticleTranslationWithRating
export type ArticleTranslationSeoMeta =
    Components.Schemas.ArticleTranslationSeoMeta
export type LocalArticleTranslation = Components.Schemas.LocalArticleTranslation

export type Article = ArticleWithLocalTranslationAndRating & {
    position: number
}

export type VisibilityStatus =
    Components.Schemas.LocalArticleTranslation['visibility_status']

export type CustomerVisibility = NonNullable<
    Components.Schemas.LocalArticleTranslation['customer_visibility']
>

// NAVIGATION

export type CreateNavigationLinkDto = Components.Schemas.CreateNavigationLinkDto
export type UpdateNavigationLinkDto = Components.Schemas.UpdateNavigationLinkDto

export type NavigationLinksListPage =
    Components.Schemas.NavigationLinksListPageDto
export type NavigationLink = Components.Schemas.NavigationLinkDto
export type NavigationLinkMeta = Components.Schemas.NavigationLinkMeta
export type NavigationLinkGroup = Components.Schemas.NavigationLinkDto['group']

export type LocalNavigationLink = Pick<
    Components.Schemas.NavigationLinkDto,
    | 'id'
    | 'label'
    | 'value'
    | 'locale'
    | 'group'
    | 'created_datetime'
    | 'updated_datetime'
> & {
    key: string
}
export type LocalSocialNavigationLink = Pick<
    Components.Schemas.NavigationLinkDto,
    | 'id'
    | 'label'
    | 'value'
    | 'group'
    | 'meta'
    | 'created_datetime'
    | 'updated_datetime'
>

// CUSTOM DOMAIN

export type CustomDomain = Components.Schemas.CustomDomain
export type CustomDomainsListPage = Components.Schemas.CustomDomainsListPageDto

// IMPORTS

export type CsvColumnPreview = Components.Schemas.AnalyseCsvResponseColumnDto

export type ColumnSourceCsv = Components.Schemas.ColumnSourceCsv
export type ColumnSourceAutoGenerated =
    Components.Schemas.ColumnSourceAutoGenerated
export type ColumnSourceCsvOrAutoGenerated =
    Components.Schemas.ColumnSourceCsvOrAutoGenerated
export type ColumnSourceCsvOnly = Components.Schemas.ColumnSourceCsvOnly

export const isColumnSourceCsv = (
    value: ColumnSourceCsv | ColumnSourceAutoGenerated,
): value is ColumnSourceCsv => value.kind === 'CSV_COLUMN'

export const isArticleWithExistingTranslation = (
    value: Article | Components.Schemas.CreateArticleDto,
): value is Article =>
    'translation' in value && 'updated_datetime' in value.translation

// EXTRA HTML

export type ExtraHTML = Components.Schemas.ExtraHTML
export type ExtraHTMLDto = Components.Schemas.ExtraHTMLDto
export type UpdateExtraHTMLDto = Components.Schemas.UpdateExtraHTMLDto

// AUTOMATE SETTINGS

export type HelpCenterAutomationSettings =
    Components.Schemas.AutomationSettingsDto

// PAGE EMBEDMENT
export type HelpCenterPageEmbedment = Components.Schemas.PageEmbedmentDto

// ARTICLE TEMPLATE
export type ArticleTemplate = Components.Schemas.ArticleTemplateDto

// AI ARTICLE
export type AIArticle = Components.Schemas.AIArticleTemplateDto

export type ArticleTemplateReviewAction =
    Components.Schemas.UpsertArticleTemplateReviewDto['action']

// HELP CENTER CREATION WIZARD
export enum HelpCenterCreationWizardStep {
    Initialization = 'initialization',
    Basics = 'basics',
    Branding = 'branding',
    Articles = 'articles',
    Automate = 'automate',
}

export enum HelpCenterAutomateType {
    NON_AUTOMATE = 'non-automate',
    AUTOMATE_NO_STORE = 'automate-no-store',
    AUTOMATE = 'automate',
}

export const ARTICLE_TEMPLATES_KEYS = [
    'applyDiscount',
    'cancelMembership',
    'cancellationPolicy',
    'damagedItem',
    'editOrder',
    'expeditedShipping',
    'freeShipping',
    'howLongDelivery',
    'howToCancelOrder',
    'howToReturn',
    'howToTrackOrder',
    'loginIssue',
    'missingDelivery',
    'packageLostOrDamaged',
    'refundPolicy',
    'refundTiming',
    'refundsOrExchanges',
    'rewards',
    'shippingCost',
    'shippingPolicy',
    'skipShipment',
    'startReturn',
    'trackOrder',
    'updateSubscription',
    'worldwideShipping',
    'wrongItem',
] as const

export type ArticleTemplateKey = (typeof ARTICLE_TEMPLATES_KEYS)[number]

export enum ArticleTemplateType {
    Template = 'template',
    AI = 'ai',
}

export type HelpCenterArticleItem = Partial<LocalArticleTranslation> &
    Partial<AIArticle> & {
        key: string
        id?: number
        isSelected?: boolean
        category?: string
        isTouched?: boolean
        availableLocales?: LocaleCode[]
        shouldCreateTranslation?: boolean
        type: ArticleTemplateType
        origin?: ArticleOrigin
    }

export enum AIArticleToggleOptionValue {
    New = 'new',
    Old = 'old',
    All = 'all',
}

export type AIArticleToggleOption = {
    label: string | JSX.Element
    value: AIArticleToggleOptionValue
}

export type AILibraryArticleItem = AIArticle & {
    isNew: boolean
}

// KNOWLEDGE HUB

export enum KnowledgeHubArticleSourceType {
    GuidanceHelpCenter = 'guidance-helpcenter',
    FaqHelpCenter = 'faq-helpcenter',
    StoreDomain = 'store-domain',
    Url = 'url',
    Document = 'document',
}

export type KnowledgeHubArticle = {
    id: number
    title: string
    source: string
    localeCode: LocaleCode
    visibilityStatus: VisibilityStatus
    shopName: string | null
    createdDatetime: string
    updatedDatetime: string
    type: KnowledgeHubArticleSourceType
    draftVersionId?: number | null
    publishedVersionId?: number | null
}

export type KnowledgeHubArticlesResponse = {
    articles: KnowledgeHubArticle[]
}

export type KnowledgeHubArticlesQueryParams = {
    account_id: number
    guidance_help_center_id?: number | null
    snippet_help_center_id?: number | null
    faq_help_center_id?: number | null
}
