export const SET_TWILIO_DEVICE = 'SET_TWILIO_DEVICE'
export const SET_TWILIO_CALL = 'SET_TWILIO_CALL'
export const SET_TWILIO_IS_DIALING = 'SET_TWILIO_IS_DIALING'
export const SET_TWILIO_IS_RINGING = 'SET_TWILIO_IS_RINGING'
export const SET_TWILIO_IS_RECORDING = 'SET_TWILIO_IS_RECORDING'
export const SET_TWILIO_PREFLIGHT_CHECK_STATUS =
    'SET_TWILIO_PREFLIGHT_CHECK_STATUS'
