name: Build docker image

on:
  workflow_run:
    workflows: [CICD]
    types: [completed]

env:
  GH_TOKEN: ${{ github.token }}
  NODE_VERSION: "24.15.0"

permissions:
  actions: read
  contents: read
  statuses: write

concurrency:
  # Only one side branch run at a time. Every commit runs in parallel on main and staging branch
  group: ${{ github.workflow }}-${{ github.event.workflow_run.head_branch }}-${{ contains(fromJSON('["main", "staging"]'), github.event.workflow_run.head_branch) && github.event.workflow_run.head_sha || '' }}
  cancel-in-progress: true

jobs:
  workspace-setup:
    name: Workspace setup
    if: github.event.workflow_run.conclusion == 'success'
    runs-on: gh-actions-4cpu4gb-runner-set
    outputs:
      cache-key: ${{ env.CACHE_KEY }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v6
        with:
          ref: ${{ github.event.workflow_run.head_sha }}

      - name: Install dependencies
        uses: ./.github/actions/install-dependencies
        with:
          node-version: ${{ env.NODE_VERSION }}
          npm-token: ${{ secrets.GH_READ_PACKAGES_TOKEN }}

  build-docker-assets:
    name: Build docker assets
    needs: workspace-setup
    uses: ./.github/workflows/build.yml
    secrets: inherit
    with:
      cache-key: ${{ needs.workspace-setup.outputs.cache-key }}
      node-version: "24.15.0"
      assets-url: ""
      release: ""
      build-dir: apps/helpdesk/build
      artifact: docker-build
      no-content-hash: true
      force-deploy-commit: ${{ github.event.workflow_run.head_sha }}

  build-docker-image:
    name: Build docker image
    needs: build-docker-assets
    uses: gorgias/reusable-actions/.github/workflows/image-build-multiarch.yml@main
    with:
      image-names: us-east1-docker.pkg.dev/gorgias-helpdesk-staging/container-images/web-app
      docker-file-path: deployment/docker/Dockerfile
      build-args: RELEASE=${{ github.event.workflow_run.head_sha }}
      artifact: docker-build
      artifact-download-path: apps/helpdesk/build
    secrets: inherit
