name: Build

on:
  workflow_call:
    inputs:
      cache-key:
        description: Node modules cache key
        required: true
        type: string
      node-version:
        description: Node version
        required: true
        type: string
      assets-url:
        description: Assets URL
        required: true
        type: string
      release:
        description: Release version
        required: true
        type: string
      build-dir:
        description: Path to the build dir
        required: true
        type: string
      artifact:
        description: Build artifact name
        required: true
        type: string
      no-content-hash:
        description: Disable content hash in bundle filenames for predictable URLs
        type: boolean
        required: false
        default: false
      force-deploy-commit:
        description: Force deploy commit
        type: string
        required: false
        default: ''

env:
  GH_TOKEN: ${{ github.token }}

jobs:
  build:
    name: Build
    runs-on: gh-actions-default-runner-set
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          ref: ${{ inputs.force-deploy-commit != '' && inputs.force-deploy-commit || github.sha }}

      - name: Setup workspace
        uses: ./.github/actions/setup-workspace
        with:
          node-version: ${{ inputs.node-version }}
          cache-key: ${{ inputs.cache-key }}
          npm-token: ${{ secrets.GH_READ_PACKAGES_TOKEN }}

      - name: Build
        env:
          GORGIAS_ASSETS_URL: ${{ inputs.assets-url }}
          WEB_APP_RELEASE: ${{ inputs.release }}
          NO_CONTENT_HASH: ${{ inputs.no-content-hash && '1' || '' }}
        run: pnpm build

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          path: ${{ inputs.build-dir }}
          name: ${{ inputs.artifact }}
