name: CICD

on: [push]

permissions:
  contents: read

concurrency:
  # Only one side branch run at a time. Every commit runs in parallel on main and staging branch
  group: ${{ github.workflow }}-${{ github.ref }}-${{ contains(fromJSON('["refs/heads/main", "refs/heads/staging"]'), github.ref) && github.sha || '' }}
  cancel-in-progress: true

jobs:
  workspace-vars:
    name: Workspace vars
    runs-on: gh-actions-small-runner-set
    outputs:
      assets-dir: src/assets
      build-dir: build
      bucket-path: web-app
      node-version: 22
    steps:
      - name: Workspace vars
        run: echo "empty step"

  install-dependencies:
    name: Install dependencies
    needs: workspace-vars
    runs-on: gh-actions-large-runner-set
    outputs:
      cache-key: ${{ env.CACHE_KEY }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install dependencies
        uses: ./.github/actions/install-dependencies
        id: install-dependencies
        with:
          node-version: ${{ needs.workspace-vars.outputs.node-version }}
          npm-token: ${{ secrets.GH_READ_PACKAGES_TOKEN }}

  quality-check:
    name: Quality check
    needs:
      - workspace-vars
      - install-dependencies
    uses: ./.github/workflows/quality-check.yml
    secrets: inherit
    with:
      cache-key: ${{ needs.install-dependencies.outputs.cache-key }}
      node-version: ${{ needs.workspace-vars.outputs.node-version }}

  build-smoke-test:
    name: Build smoke test
    if: github.ref != 'refs/heads/staging' && github.ref != 'refs/heads/main'
    needs:
      - workspace-vars
      - install-dependencies
    uses: ./.github/workflows/build.yml
    with:
      cache-key: ${{ needs.install-dependencies.outputs.cache-key }}
      node-version: ${{ needs.workspace-vars.outputs.node-version }}
      assets-url: https://gorgias-assets.gorgias.xyz/preview/${{ github.sha }}/${{ needs.workspace-vars.outputs.bucket-path }}
      release: smoke-test-${{ github.sha }}
      build-dir: ${{ needs.workspace-vars.outputs.build-dir }}
      artifact: smoke-test-build

  build-staging:
    name: Build staging
    if: github.ref == 'refs/heads/staging'
    needs:
      - workspace-vars
      - install-dependencies
    uses: ./.github/workflows/build.yml
    with:
      cache-key: ${{ needs.install-dependencies.outputs.cache-key }}
      node-version: ${{ needs.workspace-vars.outputs.node-version }}
      assets-url: https://gorgias-assets.gorgias.xyz/${{ needs.workspace-vars.outputs.bucket-path }}
      build-dir: ${{ needs.workspace-vars.outputs.build-dir }}
      artifact: staging-build
      release: staging-${{ github.sha }}

  deploy-staging:
    name: Deploy staging
    if: github.ref == 'refs/heads/staging'
    needs:
      - workspace-vars
      - install-dependencies
      - build-staging
    uses: ./.github/workflows/deploy.yml
    secrets: inherit
    with:
      cache-key: ${{ needs.install-dependencies.outputs.cache-key}}
      node-version: ${{ needs.workspace-vars.outputs.node-version }}
      gcloud-project: gorgias-helpdesk-staging
      bucket: gs://gorgias-assets-staging
      clusters: gorgias-helpdesk-staging-us-east1-86cc
      bucket-path: ${{ needs.workspace-vars.outputs.bucket-path }}
      assets-dir: ${{ needs.workspace-vars.outputs.assets-dir }}
      build-dir: ${{ needs.workspace-vars.outputs.build-dir }}
      artifact: staging-build
      sentry-project: helpdesk-staging
      release: staging-${{ github.sha }}

  build-docker-image:
    name: Build docker image
    if: github.ref == 'refs/heads/main'
    uses: gorgias/reusable-actions/.github/workflows/image-build.yml@main
    with:
      image-names: us-east1-docker.pkg.dev/gorgias-helpdesk-staging/container-images/web-app
      docker-file-path: deployment/docker/Dockerfile
      build-args: RELEASE=${{ github.sha }}
    secrets: inherit

  build-production:
    name: Build production
    if: github.ref == 'refs/heads/main'
    needs:
      - workspace-vars
      - install-dependencies
    uses: ./.github/workflows/build.yml
    with:
      cache-key: ${{ needs.install-dependencies.outputs.cache-key }}
      node-version: ${{ needs.workspace-vars.outputs.node-version }}
      assets-url: https://gorgias-assets.gorgias.io/${{ needs.workspace-vars.outputs.bucket-path }}
      build-dir: ${{ needs.workspace-vars.outputs.build-dir }}
      artifact: production-build
      release: production-${{ github.sha }}

  deploy-production:
    name: Deploy production
    if: github.ref == 'refs/heads/main'
    needs:
      - workspace-vars
      - install-dependencies
      - quality-check
      - build-production
    uses: ./.github/workflows/deploy.yml
    secrets: inherit
    with:
      cache-key: ${{ needs.install-dependencies.outputs.cache-key}}
      node-version: ${{ needs.workspace-vars.outputs.node-version }}
      bucket: gs://gorgias-assets-production
      gcloud-project: gorgias-helpdesk-production
      clusters: >-
        gorgias-helpdesk-production-aus-southeast1-fcb9
        gorgias-helpdesk-production-europe-west1-c511
        gorgias-helpdesk-production-europe-west3-86c1
        gorgias-helpdesk-production-us-central1-c433
        gorgias-helpdesk-production-us-central1-d8ff
        gorgias-helpdesk-production-us-east1-2607
        gorgias-helpdesk-production-us-east1-c94b
        gorgias-helpdesk-production-us-east4-5f09
        gorgias-helpdesk-production-us-east4-65cd
        gorgias-helpdesk-production-europe-west4-e7f4
        gorgias-main-us-east1-635c
      bucket-path: ${{ needs.workspace-vars.outputs.bucket-path }}
      assets-dir: ${{ needs.workspace-vars.outputs.assets-dir }}
      build-dir: ${{ needs.workspace-vars.outputs.build-dir }}
      artifact: production-build
      sentry-project: helpdesk-web-app
      release: production-${{ github.sha }}

  Chromatic:
    name: Upload Chromatic
    needs:
      - workspace-vars
      - install-dependencies
      - quality-check
    runs-on: gh-actions-small-runner-set
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Restore cache
        uses: actions/cache@v4
        with:
          key: ${{ needs.install-dependencies.outputs.cache-key }}
          path: node_modules

      - name: Install node
        uses: gorgias/reusable-actions/.github/actions/setup-node@main
        with:
          node-version: ${{ needs.workspace-vars.outputs.node-version }}

      - name: Upload Chromatic
        run: pnpm chromatic --zip --exit-once-uploaded --project-token=${{ secrets.CHROMATIC_PROJECT_TOKEN }}

  security-sast:
    name: "Security: Static Code Analysis"
    uses: gorgias/reusable-actions/.github/workflows/sast-scans.yml@main
    # Skip any PR created by dependabot to avoid permission issues:
    if: (github.actor != 'dependabot[bot]' )
    secrets: inherit
    with:
        semgrep-fail-on-severity: CRITICAL
        semgrep-fail-on-confidence: HIGH
        exit-zero: false
        pr-mode: ${{ github.ref_name != 'main' }}
        current-ref: ${{ github.head_ref }}
        base-ref: ${{ github.base_ref }}
