name: Deploy

on:
  workflow_call:
    inputs:
      cache-key:
        description: Node modules cache key
        type: string
        required: true
      node-version:
        description: Node version
        type: string
        required: true
      gcloud-project:
        description: GCloud project
        type: string
        required: true
      bucket:
        description: GCloud storage URL
        type: string
        required: true
      bucket-path:
        description: Path in the GCloud storage to upload the assets and build
        type: string
        required: true
      clusters:
        description: Clusters to deploy to
        type: string
        required: true
      assets-dir:
        description: Assets directory
        type: string
        required: true
      build-dir:
        description: Build directory
        type: string
        required: true
      artifact:
        description: Build artifact name
        type: string
        required: true
      sentry-project:
        description: Sentry project
        type: string
        required: true
      release:
        description: Release version
        type: string
        required: true
      force-deploy-commit:
        description: Force deploy commit
        type: string
        required: false
        default: ''

jobs:
  deploy:
    name: Deploy
    runs-on: gh-actions-default-runner-set
    container:
      image: us-central1-docker.pkg.dev/gorgias-ops-production/container-images/toolbox:latest
      credentials:
        username: _json_key
        password: ${{ secrets.GCLOUD_SERVICE_KEY_FILE }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          ref: ${{ inputs.force-deploy-commit != '' && inputs.force-deploy-commit || github.sha }}

      - name: Download the artifacts
        uses: actions/download-artifact@v4
        with:
          path: ${{ inputs.build-dir }}
          name: ${{ inputs.artifact }}

      - name: Prepare service account
        shell: bash
        run: |
          cat <<EOF > key.json
            ${{ secrets.GCLOUD_SERVICE_KEY_FILE }}
          EOF
          gcloud auth activate-service-account ${{ secrets.GCLOUD_SERVICE_ACCOUNT }} --key-file=key.json --project=${{ inputs.gcloud-project }}

      - name: Publish assets and build artifacts
        shell: bash
        run: |
          . deployment/bin/deploy-utils.sh
          . deploy-argo-utils.sh

          find_and_publish_to_gcs ${{ inputs.assets-dir }} ${{ inputs.bucket }}/${{ inputs.bucket-path }}/assets
          find_and_publish_to_gcs ${{ inputs.build-dir }} ${{ inputs.bucket }}/${{ inputs.bucket-path }}/build

      - name: Deploy configmaps
        shell: bash
        env:
          GCLOUD_SERVICE_ACCOUNT: ${{ secrets.GCLOUD_SERVICE_ACCOUNT }}
        run: |
          . deployment/bin/deploy-utils.sh
          . deploy-argo-utils.sh

          for CLUSTER in ${{ inputs.clusters }}; do
            echo "Publishing manifest configmap to $CLUSTER"
            setup_helpdesk_kubecontext $CLUSTER
            publish_manifest_configmap $CLUSTER default ${{ inputs.build-dir }} /${{inputs.bucket-path }}/build
          done

  create-release:
    name: Create release
    needs: deploy
    runs-on: gh-actions-small-runner-set
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          ref: ${{ inputs.force-deploy-commit != '' && inputs.force-deploy-commit || github.sha }}

      - name: Setup workspace
        uses: ./.github/actions/setup-workspace
        with:
          node-version: ${{ inputs.node-version }}
          cache-key: ${{ inputs.cache-key }}
          npm-token: ${{ secrets.GH_READ_PACKAGES_TOKEN }}

      - name: Download the artifacts
        uses: actions/download-artifact@v4
        with:
          path: ${{ inputs.build-dir }}
          name: ${{ inputs.artifact }}

      - name: Create sentry release
        env:
          SENTRY_AUTH_TOKEN: ${{ secrets.SENTRY_AUTH_TOKEN }}
          SENTRY_ORG: ${{ secrets.SENTRY_ORG }}
          SENTRY_PROJECT: ${{ inputs.sentry-project }}
        shell: bash
        run: |
          pnpm exec sentry-cli releases new "${{ inputs.release }}"
          pnpm exec sentry-cli releases set-commits "${{ inputs.release }}" --auto --ignore-missing
          pnpm exec sentry-cli releases files "${{ inputs.release }}" upload-sourcemaps "${{ inputs.build-dir }}"
          pnpm exec sentry-cli releases finalize "${{ inputs.release }}"
