import omit from 'lodash/omit'

import client from '../api/resources'
import type { ApiListResponseLegacyPagination } from '../api/types'
import type { Rule, RuleDraft, RulePriority } from './types'

export const fetchRules = async (): Promise<
    ApiListResponseLegacyPagination<Rule[]>
> => {
    const res = await client.get('/api/rules/')
    return res.data as ApiListResponseLegacyPagination<Rule[]>
}

export const fetchRule = async (id: number): Promise<Rule> => {
    const res = await client.get(`/api/rules/${id}/`)
    return res.data as Rule
}

export const createRule = async (rule: RuleDraft): Promise<Rule> => {
    // Omit code_ast to have it generated by the backend
    // This way the backend is the source of truth for the code_ast
    const res = await client.post('/api/rules/', omit(rule, 'code_ast'))
    return res.data as Rule
}

export const updateRule = async (
    rule: Partial<RuleDraft> & { id: number },
): Promise<Rule> => {
    // Omit code_ast to have it generated by the backend
    // This way the backend is the source of truth for the code_ast
    const res = await client.put(
        `/api/rules/${rule.id}/`,
        omit(rule, 'code_ast'),
    )
    return res.data as Rule
}

export const deleteRule = async (id: number): Promise<void> => {
    await client.delete(`/api/rules/${id}/`)
}

export const reorderRules = async (
    priorities: RulePriority[],
): Promise<Rule[]> => {
    const res = await client.post('/api/rules/priorities/', { priorities })
    return res.data as Rule[]
}

export const deactivateRule = async (id: number): Promise<Rule> => {
    const res = await client.put(`/api/rules/${id}/`, {
        deactivated_datetime: new Date(),
    })
    return res.data as Rule
}

export const activateRule = async (id: number): Promise<Rule> => {
    const res = await client.put(`/api/rules/${id}/`, {
        deactivated_datetime: null,
    })
    return res.data as Rule
}
