import type { Field } from './types'

export const data: Field[] = [
    {
        id: '1',
        key: 'delivery_type',
        name: 'Delivery type',
        type: 'single_line_text_field',
        category: 'Order',
        isVisible: true,
    },
    {
        id: '2',
        key: 'integer_field',
        name: 'Integer field',
        type: 'number_integer',
        category: 'Order',
        isVisible: true,
    },
    {
        id: '3',
        key: 'order_package_size',
        name: 'Order package size',
        type: 'volume',
        category: 'Order',
        isVisible: true,
    },
    {
        id: '4',
        key: 'order_date_and_time',
        name: 'Order date and time',
        type: 'date_time',
        category: 'Order',
        isVisible: true,
    },
    {
        id: '5',
        key: 'express_delivery',
        name: 'Express delivery',
        type: 'boolean',
        category: 'Order',
        isVisible: true,
    },
    {
        id: '6',
        key: 'package_color',
        name: 'Package color',
        type: 'color',
        category: 'Order',
        isVisible: true,
    },
    {
        id: '12',
        key: 'gift_wrap_option',
        name: 'Gift wrap option',
        type: 'boolean',
        category: 'Order',
        isVisible: true,
    },
    {
        id: '13',
        key: 'shipping_method',
        name: 'Shipping method',
        type: 'single_line_text_field',
        category: 'Order',
        isVisible: true,
    },
    {
        id: '14',
        key: 'order_priority',
        name: 'Order priority',
        type: 'number_integer',
        category: 'Order',
        isVisible: true,
    },
    {
        id: '15',
        key: 'special_instructions',
        name: 'Special instructions',
        type: 'multi_line_text_field',
        category: 'Order',
        isVisible: true,
    },
    {
        id: '7',
        key: 'vip',
        name: 'VIP',
        type: 'boolean',
        category: 'Customer',
        isVisible: true,
    },
    {
        id: '8',
        key: 'status',
        name: 'Status',
        type: 'single_line_text_field',
        category: 'Customer',
        isVisible: true,
    },
    {
        id: '9',
        key: 'dob',
        name: 'DOB',
        type: 'single_line_text_field',
        category: 'Customer',
        isVisible: true,
    },
    {
        id: '10',
        key: 'allergies',
        name: 'allergies',
        type: 'single_line_text_field',
        category: 'Customer',
        isVisible: true,
    },
    {
        id: '11',
        key: 'region',
        name: 'Region',
        type: 'single_line_text_field',
        category: 'Customer',
        isVisible: true,
    },
    {
        id: '111',
        key: 'draft_order_region',
        name: 'Region',
        type: 'single_line_text_field',
        category: 'DraftOrder',
        isVisible: true,
    },
    {
        id: '112',
        key: 'draft_order_region_2',
        name: 'Region',
        type: 'single_line_text_field',
        category: 'DraftOrder',
        isVisible: true,
    },
    {
        id: '113',
        key: 'draft_order_region_3',
        name: 'Region',
        type: 'single_line_text_field',
        category: 'DraftOrder',
        isVisible: true,
    },
]
