import type { Field } from './types'

export const data: Field[] = [
    {
        id: '1',
        name: 'Delivery type',
        type: 'single_line_text_field',
        category: 'Order',
        isVisible: true,
    },
    {
        id: '2',
        name: 'Integer field',
        type: 'number_integer',
        category: 'Order',
        isVisible: true,
    },
    {
        id: '3',
        name: 'Order package size',
        type: 'volume',
        category: 'Order',
        isVisible: true,
    },
    {
        id: '4',
        name: 'Order date and time',
        type: 'date_time',
        category: 'Order',
        isVisible: true,
    },
    {
        id: '5',
        name: 'Express delivery',
        type: 'boolean',
        category: 'Order',
        isVisible: true,
    },
    {
        id: '6',
        name: 'Package color',
        type: 'color',
        category: 'Order',
        isVisible: true,
    },
    {
        id: '12',
        name: 'Gift wrap option',
        type: 'boolean',
        category: 'Order',
        isVisible: true,
    },
    {
        id: '13',
        name: 'Shipping method',
        type: 'single_line_text_field',
        category: 'Order',
        isVisible: true,
    },
    {
        id: '14',
        name: 'Order priority',
        type: 'number_integer',
        category: 'Order',
        isVisible: true,
    },
    {
        id: '15',
        name: 'Special instructions',
        type: 'multi_line_text_field',
        category: 'Order',
        isVisible: true,
    },
    {
        id: '7',
        name: 'VIP',
        type: 'boolean',
        category: 'Customer',
        isVisible: true,
    },
    {
        id: '8',
        name: 'Status',
        type: 'single_line_text_field',
        category: 'Customer',
        isVisible: true,
    },
    {
        id: '9',
        name: 'DOB',
        type: 'single_line_text_field',
        category: 'Customer',
        isVisible: true,
    },
    {
        id: '10',
        name: 'allergies',
        type: 'single_line_text_field',
        category: 'Customer',
        isVisible: true,
    },
    {
        id: '11',
        name: 'Region',
        type: 'single_line_text_field',
        category: 'Customer',
        isVisible: true,
    },
    {
        id: '111',
        name: 'Region',
        type: 'single_line_text_field',
        category: 'DraftOrder',
        isVisible: true,
    },
    {
        id: '112',
        name: 'Region',
        type: 'single_line_text_field',
        category: 'DraftOrder',
        isVisible: true,
    },
    {
        id: '113',
        name: 'Region',
        type: 'single_line_text_field',
        category: 'DraftOrder',
        isVisible: true,
    },
]
