import { Field } from './types'

export const data: Field[] = [
    {
        id: '1',
        name: 'Delivery type',
        type: 'single_line_text',
        category: 'order',
        isVisible: true,
    },
    {
        id: '2',
        name: 'Integer field',
        type: 'integer',
        category: 'order',
        isVisible: true,
    },
    {
        id: '3',
        name: 'Order package size',
        type: 'volume',
        category: 'order',
        isVisible: true,
    },
    {
        id: '4',
        name: 'Order date and time',
        type: 'date_time',
        category: 'order',
        isVisible: true,
    },
    {
        id: '5',
        name: 'Express delivery',
        type: 'boolean',
        category: 'order',
        isVisible: true,
    },
    {
        id: '6',
        name: 'Package color',
        type: 'color',
        category: 'order',
        isVisible: true,
    },
    {
        id: '7',
        name: 'VIP',
        type: 'boolean',
        category: 'customer',
        isVisible: true,
    },
    {
        id: '8',
        name: 'Status',
        type: 'single_line_text',
        category: 'customer',
        isVisible: true,
    },
    {
        id: '9',
        name: 'DOB',
        type: 'single_line_text',
        category: 'customer',
        isVisible: true,
    },
    {
        id: '10',
        name: 'allergies',
        type: 'single_line_text',
        category: 'customer',
        isVisible: true,
    },
    {
        id: '11',
        name: 'Region',
        type: 'single_line_text',
        category: 'customer',
        isVisible: true,
    },
    {
        id: '12',
        name: 'Last click date',
        type: 'date',
        category: 'customer',
        isVisible: true,
    },
    {
        id: '13',
        name: 'Last order date',
        type: 'date',
        category: 'draft_order',
        isVisible: true,
    },
    {
        id: '14',
        name: 'Order rating',
        type: 'rating',
        category: 'draft_order',
        isVisible: true,
    },
]
