export const NEW_QUICK_RESPONSE_SYMBOL = Symbol()

export const QUICK_RESPONSE_TITLE_MAX_LENGTH = 50
export const QUICK_RESPONSE_RESPONSE_MESSAGE_TEXT_MAX_LENGTH = 5000
export const QUICK_RESPONSE_RESPONSE_MESSAGE_HTML_MAX_LENGTH = 15000
